// frontend/src/views/Data/Charts/WebOfTransnationalDeals.vue
<template>
  <ChartsContainer>
    <template #default>
      <LoadingPulse v-if="$apollo.queries.transnational_deals.loading" />
      <div id="svg-container">
        <svg></svg>
      </div>
    </template>
    <template #ContextBar>
      <ContextBarWebOfTransnationalDeals :filters="filtered_filtersForGQL" />
    </template>
  </ChartsContainer>
</template>

<script>
  import ContextBarWebOfTransnationalDeals from "$components/Charts/ContextBarWebOfTransnationalDeals";
  import LoadingPulse from "$components/Data/LoadingPulse";
  import gql from "graphql-tag";
  import ChartsContainer from "./ChartsContainer";
  import { LandMatrixRadialSpider } from "./d3_hierarchical_edge_bundling";

  export default {
    name: "WebOfTransnationalDeals",
    components: { ChartsContainer, LoadingPulse, ContextBarWebOfTransnationalDeals },
    apollo: {
      transnational_deals: {
        query: gql`
          query WebOfTransnationalDeals($filters: [Filter]) {
            transnational_deals(filters: $filters)
          }
        `,
        variables() {
          return {
            filters: this.filtered_filtersForGQL,
          };
        },
      },
    },
    metaInfo() {
      return { title: this.$t("Web of transnational deals") };
    },
    beforeRouteEnter(to, from, next) {
      next((vm) => {
        vm.$store.dispatch("showContextBar", true);
      });
    },
    data() {
      return {
        transnational_deals: [],
      };
    },
    computed: {
      filtered_filtersForGQL() {
        return this.$store.getters.filtersForGQL.filter(
          (f) => f.field !== "country_id" && f.field !== "country.fk_region_id"
        );
      },
      filtered_country_id() {
        return this.$store.state.filters.filters.country_id;
      },
    },
    watch: {
      transnational_deals() {
        this.redrawSpider();
      },
      filtered_country_id() {
        this.redrawSpider();
      },
    },
    methods: {
      redrawSpider() {
        LandMatrixRadialSpider(
          this.transnational_deals,
          "#svg-container > svg",
          this.filtered_country_id,
          (country) => {
            this.$store.dispatch("setFilter", {
              filter: "country_id",
              value: +country,
            });
          }
        );
      },
    },
  };
</script>
<style lang="scss">
  @import "src/scss/colors";

  #svg-container {
    max-height: 100%;
    width: 100%;
    padding: 4em 2em 2em 2em;

    > svg {
      width: 100%;
      height: 100%;

      #incoming-marker {
        fill: $primary;
      }

      #outgoing-marker {
        fill: $lm_investor;
      }

      text {
        font-size: 14px;
        cursor: pointer;

        &.incoming-highlighted {
          font-weight: bold;
          fill: $primary;
        }

        &.outgoing-highlighted {
          font-weight: bold;
          fill: $lm_investor;
        }
      }

      path {
        &.incoming-highlighted {
          stroke: $primary;
          stroke-width: 2;
          marker-start: url(#incoming-marker);
        }

        &.outgoing-highlighted {
          stroke: $lm_investor;
          stroke-width: 2;
          marker-start: url(#outgoing-marker);
        }

        &.incoming-permahighlight {
          stroke: $primary;
          stroke-width: 2.5;
          marker-start: url(#incoming-marker);
        }

        &.outgoing-permahighlight {
          stroke: $lm_investor;
          stroke-width: 2.5;
          marker-start: url(#outgoing-marker);
        }
      }
    }
  }
</style>

// newfront/src/routes/charts/web-of-transnational-deals/+page.svelte
<script lang="ts">
  import { Client, gql } from "@urql/svelte";
  import { onMount } from "svelte";
  import { _ } from "svelte-i18n";
  import { browser } from "$app/env";
  import { page } from "$app/stores";
  import { LandMatrixRadialSpider } from "$lib/data/charts/d3_hierarchical_edge_bundling";
  import type { EdgeBundlingData } from "$lib/data/charts/d3_hierarchical_edge_bundling";
  import { filters } from "$lib/filters";
  import { showContextBar } from "$components/Data";
  import ChartsContainer from "$components/Data/Charts/ChartsContainer.svelte";
  import ContextBarWebOfTransnationalDeals from "$components/Data/Charts/ContextBarWebOfTransnationalDeals.svelte";
  import LoadingPulse from "$components/LoadingPulse.svelte";

  let transnational_deals: EdgeBundlingData | undefined = undefined;

  function redrawSpider(deals, country_id): void {
    LandMatrixRadialSpider(
      deals,
      "#svg-container > svg",
      country_id,
      (country) => ($filters.country_id = +country)
    );
  }

  const grabTransnationalDeals = async () => {
    const { data } = await ($page.data.urqlClient as Client)
      .query<{ transnational_deals: EdgeBundlingData }>(
        gql`
          query ($filters: [Filter]) {
            transnational_deals(filters: $filters)
          }
        `,
        {
          filters: $filters
            .toGQLFilterArray()
            .filter((f) => f.field !== "country_id" && f.field !== "country.region_id"),
        }
      )
      .toPromise();
    transnational_deals = data?.transnational_deals;
  };

  $: $filters && grabTransnationalDeals();
  $: browser && redrawSpider(transnational_deals, $filters.country_id);
  onMount(() => showContextBar.set(false));
</script>

<svelte:head>
  <title>{$_("Web of transnational deals | Land Matrix")}</title>
</svelte:head>

<ChartsContainer>
  {#if !transnational_deals}
    <div class="absolute inset-0">
      <LoadingPulse data-v-if="$apollo.queries.transnational_deals.loading" />
    </div>
  {/if}

  <div id="svg-container" class="max-h-full w-full p-8 pt-16">
    <svg />
  </div>

  <div slot="ContextBar">
    <ContextBarWebOfTransnationalDeals />
  </div>
</ChartsContainer>

<!--suppress CssUnusedSymbol, CssUnknownTarget -->
<style>
  :global(#incoming-marker) {
    fill: var(--color-lm-orange);
  }
  :global(#outgoing-marker) {
    fill: var(--color-lm-investor);
  }

  :global(path.incoming-highlighted) {
    stroke: var(--color-lm-orange);
    stroke-width: 2;
    marker-start: url(#incoming-marker);
  }
  :global(path.outgoing-highlighted) {
    stroke: var(--color-lm-investor);
    stroke-width: 2;
    marker-start: url(#outgoing-marker);
  }

  :global(path.incoming-permahighlight) {
    stroke: var(--color-lm-orange);
    stroke-width: 2.5;
    marker-start: url(#incoming-marker);
  }
  :global(path.outgoing-permahighlight) {
    stroke: var(--color-lm-investor);
    stroke-width: 2.5;
    marker-start: url(#outgoing-marker);
  }

  :global(text.incoming-highlighted) {
    font-size: 14px;
    cursor: pointer;
    font-weight: bold;
    fill: var(--color-lm-orange);
  }
  :global(text.outgoing-highlighted) {
    font-size: 14px;
    cursor: pointer;
    font-weight: bold;
    fill: var(--color-lm-investor);
  }
</style>
