// newfront/src/components/Management/DealManageHeader.svelte
<script lang="ts">
  import { gql } from "graphql-tag";
  import { createEventDispatcher } from "svelte";
  import { _ } from "svelte-i18n";
  import { goto } from "$app/navigation";
  import { page } from "$app/stores";
  import { isAuthorized } from "$lib/helpers";
  import type { Deal } from "$lib/types/deal";
  import type { User } from "$lib/types/user";
  import CheckCircleIcon from "$components/icons/CheckCircleIcon.svelte";
  import CheckIcon from "$components/icons/CheckIcon.svelte";
  import EyeIcon from "$components/icons/EyeIcon.svelte";
  import EyeSlashIcon from "$components/icons/EyeSlashIcon.svelte";
  import MinusIcon from "$components/icons/MinusIcon.svelte";
  import XIcon from "$components/icons/XIcon.svelte";
  import CheckboxSwitch from "$components/LowLevel/CheckboxSwitch.svelte";
  import ManageOverlay from "$components/Management/ManageOverlay.svelte";
  import ManageHeader from "./ManageHeader.svelte";

  const dispatch = createEventDispatcher();

  export let deal: Deal;
  export let dealVersion: number;

  let fully_updated = false;

  $: isEditable =
    !dealVersion && deal.status === 4
      ? false
      : !dealVersion && !!deal.draft_status
      ? false
      : isAuthorized($page.stuff.user, deal);

  let showSendToReviewOverlay = false;
  async function sendToReview({ detail: { comment } }) {
    await changeStatus({ detail: { transition: "TO_REVIEW", comment } });
    showSendToReviewOverlay = false;
  }

  let showCopyOverlay = false;

  async function copyDeal() {
    $page.stuff.secureApolloClient
      .mutate({
        mutation: gql`
          mutation ($id: Int!) {
            object_copy(otype: "deal", obj_id: $id) {
              objId
              objVersion
            }
          }
        `,
        variables: { id: deal.id },
      })
      .then(({ data: { object_copy } }) => {
        window.open(`/deal/${object_copy.objId}/${object_copy.objVersion}`, "_blank");
      });
    showCopyOverlay = false;
  }

  let showConfidentialOverlay = false;
  async function toggleConfidential(data: {
    force: boolean;
    comment;
    string;
    to_user: User;
  }) {
    if (!isEditable) return;

    if (data.force) {
      if (deal.confidential) {
        setConfidential(false);
        showConfidentialOverlay = false;
      } else {
        setConfidential(true, data.comment);
        showConfidentialOverlay = false;
      }
    } else {
      showConfidentialOverlay = true;
    }
  }
  function setConfidential(confidential, comment = ""): void {
    $page.stuff.secureApolloClient
      .mutate({
        mutation: gql`
          mutation (
            $id: Int!
            $confidential: Boolean!
            $version: Int
            $comment: String
          ) {
            deal_set_confidential(
              id: $id
              confidential: $confidential
              version: $version
              comment: $comment
            )
          }
        `,
        variables: { id: deal.id, version: dealVersion, confidential, comment },
      })
      .then(() => dispatch("reload"));
  }

  function changeStatus({ detail: { transition, comment = "", to_user = null } }) {
    $page.stuff.secureApolloClient
      .mutate({
        mutation: gql`
          mutation (
            $id: Int!
            $version: Int!
            $transition: WorkflowTransition!
            $comment: String
            $to_user_id: Int
            $fully_updated: Boolean
          ) {
            change_deal_status(
              id: $id
              version: $version
              transition: $transition
              comment: $comment
              to_user_id: $to_user_id
              fully_updated: $fully_updated
            ) {
              dealId
              dealVersion
            }
          }
        `,
        variables: {
          id: deal.id,
          version: dealVersion,
          transition,
          comment,
          to_user_id: to_user?.id,
          fully_updated,
        },
      })
      .then(async ({ data: { change_deal_status } }) => {
        console.log(change_deal_status);
        if (transition === "ACTIVATE") {
          await goto(`/deal/${change_deal_status.dealId}/`);
        } else {
          if (dealVersion !== change_deal_status.dealVersion)
            await goto(
              `/deal/${change_deal_status.dealId}/${change_deal_status.dealVersion}/`
            );
          else dispatch("reload");
        }
      })
      .catch((error) => console.error(error));
  }
  async function deleteDeal({ detail: { comment } }) {
    $page.stuff.secureApolloClient
      .mutate({
        mutation: gql`
          mutation ($id: Int!, $version: Int, $comment: String) {
            deal_delete(id: $id, version: $version, comment: $comment)
          }
        `,
        variables: { id: deal.id, version: dealVersion, comment },
      })
      .then(async (dat) => {
        //todo: if it was just a draft, and we deleted the whole thing, jump to deal list
        console.log(dat);
        if (dealVersion) await goto(`/deal/${deal.id}`);
        dispatch("reload");
      });
  }

  function addComment({ detail: { comment, send_to_user } }) {
    $page.stuff.secureApolloClient
      .mutate({
        mutation: gql`
          mutation ($id: Int!, $version: Int, $comment: String!, $to_user_id: Int) {
            add_deal_comment(
              id: $id
              version: $version
              comment: $comment
              to_user_id: $to_user_id
            ) {
              dealId
              dealVersion
            }
          }
        `,
        variables: {
          id: deal.id,
          version: dealVersion ?? null,
          comment: comment,
          to_user_id: send_to_user?.id,
        },
      })
      .then(() => dispatch("reload"))
      .catch((error) => console.error(error));
  }
</script>

<ManageHeader
  object={deal}
  objectVersion={dealVersion}
  on:addComment={addComment}
  on:changeStatus={changeStatus}
  on:copy={() => (showCopyOverlay = true)}
  on:delete={deleteDeal}
  on:sendToReview={() => (showSendToReviewOverlay = true)}
>
  <div slot="heading">
    {$_("Deal")} #{deal.id}
    {#if deal.country}
      <span class="whitespace-nowrap block text-base font-normal">
        {deal.country.name}
      </span>
    {/if}
  </div>
  <div slot="visibility" class="flex-auto">
    <div class="flex items-center gap-1 mb-2 text-lg">
      {#if deal.is_public}
        <EyeIcon class="h-6 w-6 text-orange" /> {$_("Publicly visible")}
      {:else}
        <EyeSlashIcon class="h-6 w-6 text-gray-500" />
        <span class="text-gray-500">{$_("Not publicly visible")}</span>
      {/if}
    </div>

    {#if isEditable}
      <CheckboxSwitch
        checked={deal.confidential}
        title={deal.confidential_comment}
        on:change={toggleConfidential}
      >
        {deal.confidential ? $_("Confidential") : $_("Not confidential")}
      </CheckboxSwitch>
    {/if}
    <ul>
      {#if !isEditable}
        <li class="flex items-center gap-1">
          {#if !deal.confidential}
            <CheckIcon class="h-4 w-4 mx-1" /> {$_("Not confidential")}
          {:else}
            <XIcon class="h-4 w-4 mx-1" /> {$_("Confidential")}
          {/if}
        </li>
      {/if}

      <li class="flex items-center gap-1">
        {#if deal.country}
          <CheckIcon class="h-4 w-4 mx-1" /> {$_("Target country is set")}
        {:else}
          <XIcon class="h-4 w-4 mx-1" /> {$_("Target country is NOT set")}
        {/if}
      </li>

      <li class="flex items-center gap-1 whitespace-nowrap">
        {#if deal.datasources?.length > 0}
          <CheckIcon class="h-4 w-4 mx-1" />
          {$_("At least one data source")} ({deal.datasources.length})
        {:else}
          <XIcon class="h-4 w-4 mx-1" /> {$_("No data source")}
        {/if}
      </li>

      <li class="flex items-center gap-1">
        {#if deal.has_known_investor}
          <CheckIcon class="h-4 w-4 mx-1" /> {$_("At least one investor")}
        {:else}
          <XIcon class="h-4 w-4 mx-1" /> {$_("No known investor")}
        {/if}
      </li>
    </ul>

    <div class="flex items-center gap-1 font-bold mt-2">
      {#if deal.fully_updated}
        <CheckCircleIcon class="h-6 w-6 text-orange" />
        <span>{$_("Fully updated")}</span>
      {:else}
        <MinusIcon class="h-6 w-6 text-gray-500" />
        <span class="text-gray-500">{$_("Not fully updated")}</span>
      {/if}
    </div>
  </div>
</ManageHeader>

<ManageOverlay
  bind:visible={showSendToReviewOverlay}
  title={$_("Submit for review")}
  commentInput
  on:submit={sendToReview}
>
  <div class="mb-6">
    <div class="underline">{$_("Full update")}</div>
    <p class="mb-1">
      {$_(
        'If you have checked the information entered for every single variable, please tick the box beside "I fully updated this deal" - even if no additional information was found, but a complete search through the deal was conducted.'
      )}
    </p>
    <label class="my-1">
      <input bind:checked={fully_updated} type="checkbox" />
      {$_("I fully updated this deal.")}
    </label>
  </div>
  <div class="mb-6">
    <label for="data-policy-checkbox" class="underline">{$_("Data policy")}</label>
    <label class="font-bold block mt-1">
      <input required type="checkbox" id="data-policy-checkbox" />
      {$_("I've read and agree to the")}
      <a href="/about/data-policy/" target="_blank">{$_("Data policy")} </a>.
    </label>
  </div>
</ManageOverlay>

<ManageOverlay
  bind:visible={showCopyOverlay}
  title={$_("Copy deal")}
  on:submit={copyDeal}
>
  <p>
    {$_(
      "This creates a completely identical copy of the deal. The copy must then be edited and adjusted to prevent identical duplicates."
    )}
  </p>
  <div class="font-medium">{$_("Do you really want to copy this deal?")}</div>
</ManageOverlay>

<ManageOverlay
  bind:visible={showConfidentialOverlay}
  on:submit={({ detail }) => toggleConfidential({ ...detail, force: true })}
  on:close={() => (deal.confidential = deal.confidential)}
  title={deal.confidential ? $_("Unset confidential") : $_("Set confidential")}
  commentRequired={!deal.confidential}
>
  <p>
    {#if deal.confidential}
      {$_(
        "If you unset the confidential flag, this deal will be publicly visible once it is set active. If you want to keep it confidential, click on 'Cancel'."
      )}
    {:else}
      {$_(
        "If you set the confidential flag, this deal will not be publicly visible anymore. If you want to keep it public, click on 'Cancel'."
      )}
    {/if}
  </p>
</ManageOverlay>

// frontend/src/components/Deal/DealManageHeader.vue
<template>
  <ManageHeader
    :object="deal"
    :object-version="dealVersion"
    @add_comment="add_comment"
    @change_status="$emit('change_status', $event)"
    @delete="$emit('delete', $event)"
    @copy="$emit('copy', $event)"
    @send_to_review="show_send_to_review_overlay = true"
  >
    <template #heading>
      Deal #{{ deal.id }}
      <span v-if="deal.country" class="headercountry">{{ deal.country.name }}</span>
    </template>

    <template #visibility>
      <div class="visibility-container">
        <div v-if="deal.is_public" class="visibility">
          <i class="fas fa-eye fa-fw fa-lg orange"></i>
          <span>{{ $t("Publicly visible") }}</span>
        </div>
        <div v-else class="visibility">
          <i class="fas fa-eye-slash fa-fw fa-lg orange"></i>
          <span>{{ $t("Not publicly visible") }}</span>
        </div>
        <div v-if="is_editable" class="confidential-toggle">
          <b-form-checkbox
            :checked="deal.confidential"
            :class="{ active: deal.confidential }"
            class="confidential-switch"
            name="check-button"
            switch
            :title="$t('Toggle deal confidentiality')"
            @click.native.prevent="toggle_confidential({ force: false })"
          >
            {{ deal.confidential ? $t("Confidential") : $t("Not confidential") }}
          </b-form-checkbox>
          <a id="confidential-reason">
            <span v-if="deal.confidential">({{ $t("reason") }})</span>
          </a>
          <b-tooltip target="confidential-reason" triggers="click">
            <!-- <strong>{{ get_confidential_reason }}</strong> <br /> -->
            {{ deal.confidential_comment }}
          </b-tooltip>
        </div>
        <ul>
          <template v-if="!is_editable">
            <li v-if="!deal.confidential">
              <i class="fas fa-check fa-fw"></i>
              {{ $t("Not confidential") }}
            </li>
            <li v-else>
              <i class="fas fa-times fa-fw"></i>
              {{ $t("Confidential") }}
            </li>
          </template>
          <li v-if="deal.country">
            <i class="fas fa-check fa-fw"></i>
            {{ $t("Target country is set") }}
          </li>
          <li v-else>
            <i class="fas fa-times fa-fw"></i>
            {{ $t("Target country is NOT set") }}
          </li>

          <li v-if="deal.datasources.length > 0" class="whitespace-nowrap">
            <i class="fas fa-check fa-fw"></i>
            {{ $t("At least one data source") }} ({{ deal.datasources.length }})
          </li>
          <li v-else><i class="fas fa-times fa-fw"></i> {{ $t("No data source") }}</li>

          <li v-if="deal.has_known_investor">
            <i class="fas fa-check fa-fw"></i>
            {{ $t("At least one investor") }}
          </li>
          <li v-else>
            <i class="fas fa-times fa-fw"></i> {{ $t("No known investor") }}
          </li>
        </ul>

        <div v-if="deal.fully_updated" class="visibility">
          <i class="fas fa-check-circle fa-fw fa-lg orange"></i>
          <span>{{ $t("Fully updated") }}</span>
        </div>
        <div v-else class="visibility" style="color: gray !important">
          <i class="fas fa-minus fa-fw fa-lg"></i>
          <span>{{ $t("Not fully updated") }}</span>
        </div>
      </div>
    </template>
    <template #overlays>
      <Overlay
        v-if="show_send_to_review_overlay"
        :title="$t('Submit for review').toString()"
        :comment-input="true"
        @cancel="show_send_to_review_overlay = false"
        @submit="send_to_review"
      >
        <p class="mb-1">
          If you have checked the information entered for every single variable, please
          tick the box beside "I fully updated this deal" - even if no additional
          information was found, but a complete search through the deal was conducted.
        </p>
        <label>
          <input v-model="deal.fully_updated" type="checkbox" />
          {{ $t("I fully updated this deal.") }}
        </label>
        <div class="my-4" style="font-weight: bold">
          <label>
            <input required type="checkbox" />
            {{ $t("I've read and agree to the") }}
            <a href="/about/data-policy/" target="_blank">{{ $t("Data policy") }}</a
            >.
          </label>
        </div>
      </Overlay>
      <Overlay
        v-if="show_confidential_overlay"
        :title="
          $t(deal.confidential ? 'Unset confidential' : 'Set confidential').toString()
        "
        :comment-input="!deal.confidential"
        :comment-required="!deal.confidential"
        @cancel="show_confidential_overlay = false"
        @submit="toggle_confidential"
      >
        <p v-if="deal.confidential">
          {{
            $t(
              "If you unset the confidential flag, this deal will be publicly visible once it is set active. If you want to keep it confidential, click on 'Cancel'."
            )
          }}
        </p>
        <p v-else>
          {{
            $t(
              "If you set the confidential flag, this deal will not be publicly visible anymore. If you want to keep it public, click on 'Cancel'."
            )
          }}
        </p>
      </Overlay>
    </template>
  </ManageHeader>
</template>

<script lang="ts">
  import Overlay from "$components/Overlay.vue";
  import gql from "graphql-tag";
  import { is_authorized } from "$utils/user";
  import ManageHeader from "../Management/ManageHeader.vue";
  import Vue from "vue";
  import type { PropType } from "vue";
  import type { Deal } from "$types/deal";
  import type { User } from "$types/user";

  export default Vue.extend({
    name: "DealManageHeader",
    components: {
      ManageHeader,
      Overlay,
    },
    props: {
      deal: { type: Object as PropType<Deal>, required: true },
      dealVersion: { type: [Number, String], default: null },
    },
    data() {
      return {
        show_confidential_overlay: false,
        show_send_to_review_overlay: false,
        is_authorized,
      };
    },
    computed: {
      is_active_with_draft(): boolean {
        return !this.dealVersion && !!this.deal.draft_status;
      },
      is_editable(): boolean {
        // deal ist deleted
        if (!this.dealVersion && this.deal.status === 4) return false;
        if (this.is_active_with_draft) return false;
        return this.is_authorized(this.deal);
      },
    },
    methods: {
      send_to_review(args) {
        this.$emit("change_status", { ...args, transition: "TO_REVIEW" });
        this.show_send_to_review_overlay = false;
      },
      add_comment({ comment, send_to_user }: { comment: string; send_to_user: User }) {
        this.$apollo
          .mutate({
            mutation: gql`
              mutation ($id: Int!, $version: Int, $comment: String!, $to_user_id: Int) {
                add_deal_comment(
                  id: $id
                  version: $version
                  comment: $comment
                  to_user_id: $to_user_id
                ) {
                  dealId
                  dealVersion
                }
              }
            `,
            variables: {
              id: +this.deal.id,
              version: this.dealVersion ? +this.dealVersion : null,
              comment: comment,
              to_user_id: send_to_user ? +send_to_user.id : null,
            },
          })
          .then(() => {
            this.$emit("reload");
          })
          .catch((error) => console.error(error));
      },
      toggle_confidential(data: { [key: string]: string | boolean }) {
        if (!this.is_editable) return;
        if (data.force) {
          if (this.deal.confidential) {
            this.$emit("set_confidential", { confidential: false });
            this.show_confidential_overlay = false;
          } else {
            this.$emit("set_confidential", {
              confidential: true,
              comment: data.comment,
            });
            this.show_confidential_overlay = false;
          }
        } else {
          this.show_confidential_overlay = true;
        }
      },
    },
  });
</script>

<style scoped lang="scss">
  .headercountry {
    white-space: nowrap;
    display: block;
    font-size: 1rem;
  }
  .visibility-container {
    flex-grow: 1;
    width: 100%;
    .visibility {
      font-size: 0.9em;

      i {
        font-size: 1.8em;
      }

      span {
        font-size: 1.1em;
        font-weight: bold;
        padding-left: 0.5em;
      }
    }

    ul {
      font-size: 0.8em;
      list-style: none;
      padding: 0;

      li {
        margin-left: 0.8em;

        i {
          font-size: 0.8em;
          margin-right: 11px;
        }
      }

      .fa-check {
        color: black;
      }
    }
  }
</style>

<style lang="scss">
  .confidential-toggle {
    margin-left: 0.45em;
    margin-bottom: -3px;
    display: flex;
    align-items: center;

    .confidential-switch {
      padding-left: 2rem;
      font-size: 0.8em;
      display: flex;
      align-items: center;
      label {
        font-weight: normal;
        line-height: 1.9em;

        &:hover {
          cursor: pointer;
        }
      }
    }

    a#confidential-reason {
      font-size: 0.8em;
      padding-left: 0.3em;
      text-decoration: underline;

      &:hover {
        cursor: pointer;
      }
    }
  }
</style>
