// frontend/src/components/Deal/DealLocationsSection.svelte
<script lang="ts">
  import type {
    Map,
    GeoJSONOptions,
    GeoJSON,
    StyleFunction,
    PathOptions,
    LatLngBoundsExpression,
  } from "leaflet"
  import { latLngBounds, geoJson, DomUtil } from "leaflet?client"
  import type { Feature, Geometry } from "geojson"

  import type { Deal, AreaType } from "$lib/types/deal"

  import BigMap from "$components/Map/BigMap.svelte"
  import LocationTooltip from "$components/Deal/LocationTooltip.svelte"

  import DealSubmodelSection from "./DealSubmodelSection.svelte"

  export let deal: Deal

  interface FeatureProperties {
    id: string
    name: string
    type: AreaType
    year: number
  }

  let bigmap: Map
  let geoJsonLayer: GeoJSON<FeatureProperties>

  const styleFunction: StyleFunction<FeatureProperties> = feature => {
    const commonStyles: PathOptions = {
      weight: 2,
      color: "#000000",
      opacity: 1,
      fillOpacity: 0.2,
    }
    const areaTypeStylesMap: { [key in AreaType]: PathOptions } = {
      contract_area: { dashArray: "5, 5", dashOffset: "0", fillColor: "#ff00ff" },
      intended_area: { dashArray: "5, 5", dashOffset: "0", fillColor: "#66ff33" },
      production_area: { fillColor: "#ff0000" },
    }
    return {
      ...commonStyles,
      ...areaTypeStylesMap[feature?.properties.type],
    }
  }

  const createTooltip = (
    feature: Feature<Geometry, FeatureProperties>,
  ): HTMLElement => {
    const container = DomUtil.create("div")
    new LocationTooltip({
      props: { feature },
      target: container,
    })
    return container
  }

  const geoJsonOptions: GeoJSONOptions<FeatureProperties> = {
    style: styleFunction,
    onEachFeature: (feature, layer) => {
      const tooltip = createTooltip(feature)

      layer.bindPopup(tooltip, { permanent: false, sticky: true, keepInView: true })
      layer.on("mouseover", () => layer.openPopup())
      layer.on("mouseout", () => layer.closePopup())
    },
  }

  const computeBounds = (geoJsonLayer: GeoJSON): LatLngBoundsExpression => {
    const bounds = geoJsonLayer.getBounds()

    let ne = bounds.getNorthEast()
    let sw = bounds.getSouthWest()
    if (ne && sw) {
      if (ne.equals(sw)) {
        ne.lat += 10
        ne.lng += 10
        sw.lat -= 10
        sw.lng -= 10
        return latLngBounds(ne, sw)
      }
      return bounds.pad(1.2)
    }
    return
  }

  const refreshMap = async (): Promise<void> => {
    if (!(deal && deal.country && bigmap)) {
      return
    }

    if (geoJsonLayer) {
      bigmap.removeLayer(geoJsonLayer)
    }
    geoJsonLayer = geoJson(deal.geojson, geoJsonOptions)
    bigmap.addLayer(geoJsonLayer)

    const bounds = computeBounds(geoJsonLayer)
    if (bounds) {
      bigmap.fitBounds(bounds, { animate: false })
    }
  }

  const onMapReady = async (event: CustomEvent<Map>) => {
    bigmap = event.detail
    await refreshMap()
  }
</script>

<DealSubmodelSection model="location" modelName="Location" entries={deal.locations}>
  <div class="min-h-[20rem] w-full lg:w-1/2">
    <BigMap
      containerClass="min-h-full h-full mt-5"
      options={{ center: [0, 0] }}
      on:ready={onMapReady}
    />
  </div>
</DealSubmodelSection>

// frontend/src/components/Deal/DealLocationsSection.vue
<template>
  <DealSubmodelSection
    model="location"
    model-name="Location"
    :entries="deal.locations"
    :fields="fields"
    :label-classes="['display-field-label', 'col-md-6']"
    :value-classes="['display-field-value', 'col-md-6']"
  >
    <div class="locations col-md-12 col-lg-5 col-xl-6">
      <BigMap
        :container-style="{ 'max-height': '90%', height: '90%' }"
        :center="[0, 0]"
        @ready="mapIsReady"
      />
    </div>
  </DealSubmodelSection>
</template>

<script lang="ts">
  import BigMap from "$components/BigMap.vue";

  import { area } from "@turf/turf";
  import { GeoJSON, LatLngBounds } from "leaflet";
  import DealSubmodelSection from "./DealSubmodelSection.vue";
  import Vue from "vue";

  let styles = {
    contract_area: {
      dashArray: "5, 5",
      dashOffset: "0",
      fillColor: "#ff00ff",
    },
    intended_area: {
      dashArray: "5, 5",
      dashOffset: "0",
      fillColor: "#66ff33",
    },
    production_area: {
      fillColor: "#ff0000",
    },
  };

  export default Vue.extend({
    components: {
      DealSubmodelSection,
      BigMap,
    },
    props: {
      fields: { type: Array, required: true },
      deal: { type: Object, required: true },
      active: { type: Boolean, default: false },
    },
    data() {
      return {
        bigmap: null,
        layer: null,
        geojson_options: {
          style: (feature) => {
            return {
              weight: 2,
              color: "#000000",
              opacity: 1,
              fillOpacity: 0.2,
              ...styles[feature.properties.type],
            };
          },
          onEachFeature: (feature, layer) => {
            let tooltip = "<div>";

            tooltip += `<div>Location #${feature.properties.id}</div>
                      <div>Name: ${feature.properties.name}</div>
                      <div>Type: ${feature.properties.type}</div>`;

            if (feature.geometry.type !== "Point") {
              let farea = (area(layer.toGeoJSON()) / 10000)
                .toFixed(2)
                .toString()
                .replace(/\B(?=(\d{3})+(?!\d))/g, " ");
              tooltip += `<div>Area: ${farea} ha</div>`;
            }
            tooltip += "</div>";

            layer.bindPopup(tooltip, {
              permanent: false,
              sticky: true,
              keepInView: true,
            });
            layer.on("mouseover", () => layer.openPopup());
            layer.on("mouseout", () => layer.closePopup());
          },
        },
      };
    },
    watch: {
      deal() {
        this.refreshMap();
      },
    },
    methods: {
      activateTab() {
        this.$emit("activated");
        this.$nextTick(() => this.bigmap.invalidateSize());
      },
      refreshMap() {
        if (this.deal && this.deal.country && this.bigmap) {
          if (this.layer) {
            this.bigmap.removeLayer(this.layer);
          }
          this.layer = new GeoJSON(this.deal.geojson, this.geojson_options);
          let mybounds = this.layer.getBounds();
          let ne = mybounds.getNorthEast();
          let sw = mybounds.getSouthWest();
          if (ne && sw) {
            if (ne.equals(sw)) {
              ne.lat += 10;
              ne.lng += 10;
              sw.lat -= 10;
              sw.lng -= 10;
              this.bigmap.fitBounds(new LatLngBounds(ne, sw), { animate: false });
            }
            this.bigmap.fitBounds(mybounds.pad(1.2), { animate: false });
          }
          this.bigmap.addLayer(this.layer);
        }
      },
      mapIsReady(map) {
        this.bigmap = map;
        this.refreshMap();
      },
    },
  });
</script>

<style lang="scss">
  .locations {
    .map-container {
      min-height: 250px;

      #bigMap {
        max-height: 50vh;
        margin-top: 2em;
      }
    }
  }
</style>
