// frontend/src/components/Deal/DealSection.svelte
<script lang="ts">
  import { isEmpty } from "$lib/helpers"
  import type { Section } from "$lib/sections"
  import type { Deal } from "$lib/types/deal"

  import ExpandableDisplayField from "$components/Fields/ExpandableDisplayField.svelte"

  export let deal: Deal
  export let sections: Section[] = []

  function sectionFieldsWithValues(subsection: Section) {
    return subsection.fields.filter(field =>
      typeof field === "object" ? !isEmpty(deal[field.name]) : !isEmpty(deal[field]),
    )
  }

  $: subsectionsWithAtLeastOneField = sections.filter(
    section => sectionFieldsWithValues(section).length > 0,
  )
</script>

<section>
  {#each subsectionsWithAtLeastOneField as subsection}
    <div class="mt-2 space-y-4">
      <h3 class="my-0">{subsection.name}</h3>
      {#each sectionFieldsWithValues(subsection) as field}
        <ExpandableDisplayField {field} {deal} />
      {/each}
    </div>
  {/each}
  <slot />
</section>

// frontend/src/components/Deal/DealSection.vue
<template>
  <b-tab :title="title" v-if="any_field_at_all(sections)" @click="$emit('activated')">
    <div>
      <div
        v-for="section in sections"
        class="panel-body"
        v-if="any_field_in_section(section)"
      >
        <h3>{{ section.name }}</h3>
        <Field
          :fieldname="fieldname"
          :readonly="!!readonly"
          v-model="deal[fieldname]"
          v-for="fieldname in section.fields"
        />
      </div>
    </div>
    <slot></slot>
  </b-tab>
</template>

<script>
  import Field from "/components/Fields/Field";

  export default {
    props: ["title", "sections", "deal", "readonly"],
    components: { Field },
    methods: {
      custom_is_null(field) {
        return !(
          field === undefined ||
          field === null ||
          field === "" ||
          (Array.isArray(field) && field.length === 0)
        );
      },
      any_field_in_section(section) {
        return !!section.fields.filter((field) => {
          return this.custom_is_null(this.deal[field]);
        }).length;
      },
      any_field_at_all(sections) {
        return !!sections.filter((section) => this.any_field_in_section(section))
          .length;
      },
    },
  };
</script>
