// newfront/src/components/Deal/DealSection.svelte
<script lang="ts">
  import { isEmpty } from "$lib/helpers"
  import type { Section } from "$lib/sections"
  import type { Deal } from "$lib/types/deal"

  import DisplayField from "$components/Fields/DisplayField.svelte"

  export let deal: Deal
  export let sections: Section[] = []

  function sectionFieldsWithValues(subsection: Section) {
    return subsection.fields.filter(field => !isEmpty(deal[field]))
  }

  $: subsectionsWithAtLeastOneField = sections.filter(
    section => sectionFieldsWithValues(section).length > 0,
  )
</script>

<section>
  {#each subsectionsWithAtLeastOneField as subsection}
    <div class="mt-2 space-y-4">
      <h3 class="my-0">{subsection.name}</h3>
      {#each sectionFieldsWithValues(subsection) as fieldname}
        <DisplayField {fieldname} value={deal[fieldname]} showLabel />
      {/each}
    </div>
  {/each}
  <slot />
</section>

// frontend/src/components/Deal/DealSection.vue
<template>
  <b-tab
    v-if="any_field_in_sections(sections)"
    :title="title"
    :active="active"
    @click="$emit('activated')"
  >
    <div>
      <div
        v-for="section in sections_with_filled_fields"
        :key="section.name"
        class="panel-body"
      >
        <h3>{{ section.name }}</h3>
        <DisplayField
          v-for="fieldname in section_fields_with_values(section)"
          :key="fieldname"
          :fieldname="fieldname"
          :value="deal[fieldname]"
        />
      </div>
    </div>
    <slot />
  </b-tab>
</template>

<script>
  import DisplayField from "components/Fields/DisplayField";

  export default {
    components: { DisplayField },
    props: ["title", "sections", "deal", "active"],
    computed: {
      sections_with_filled_fields() {
        return this.sections.filter((section) => {
          return this.section_fields_with_values(section).length > 0;
        });
      },
    },
    methods: {
      any_field_in_sections(sections) {
        return (
          sections.filter(
            (section) => this.section_fields_with_values(section).length > 0
          ).length > 0
        );
      },
      section_fields_with_values(section) {
        return section.fields.filter((field) => {
          return !this.custom_is_null(this.deal[field]);
        });
      },
      custom_is_null(field) {
        return (
          field === undefined ||
          field === null ||
          field === "" ||
          (Array.isArray(field) && field.length === 0)
        );
      },
    },
  };
</script>
