// frontend/src/components/Fields/Display/JSONJobsField.vue
<template>
  <div class="nowrap">
    <div v-for="val in vals" :class="{ 'font-weight-bold': val.current }">
      <span>{{ date_and_current(val) }}</span>
      <span v-if="val.jobs" class="mx-2"> {{ val.jobs.toLocaleString() }} jobs </span>
      <span v-if="val.employees" class="mx-2">
        {{ val.employees.toLocaleString() }} employees
      </span>
      <span v-if="val.workers" class="mx-2">
        {{ val.workers.toLocaleString() }} workers
      </span>
    </div>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";

  export default {
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ date: null, value: null }],
      };
    },
  };
</script>

// frontend/src/components/Fields/Display2/JSONJobsField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import type { JSONJobsFieldType } from "$lib/types/data"

  import { dateCurrentFormat } from "$components/Fields/Display2/jsonHelpers"

  export let value: JSONJobsFieldType[]
</script>

<ul>
  {#each value ?? [] as val}
    <li class:font-bold={val.current}>
      {dateCurrentFormat(val)}
      {#if val.jobs}
        <span class="mx-2">
          {val.jobs.toLocaleString("fr").replace(",", ".")}
          {$_("jobs")}
        </span>
      {/if}
      {#if val.employees}
        <span class="mx-2">
          {val.employees.toLocaleString("fr").replace(",", ".")}
          {$_("employees")}
        </span>
      {/if}
      {#if val.workers}
        <span class="mx-2">
          {val.workers.toLocaleString("fr").replace(",", ".")}
          {$_("workers")}
        </span>
      {/if}
    </li>
  {/each}
</ul>
