// frontend/src/components/Fields/Display/PointField.vue
<template>
  <div>
    <div v-if="value.lat">Lat: {{ parseFloat(value.lat.toFixed(8)) }}</div>
    <div v-if="value.lng">Lng: {{ parseFloat(value.lng.toFixed(8)) }}</div>
  </div>
</template>

<script>
  export default {
    props: {
      formfield: { type: Object, required: true },
      value: { type: Object, required: true },
      model: { type: String, required: true },
    },
  };
</script>

// frontend/src/components/Fields/Display2/PointField.svelte
<script lang="ts">
  import type { Point } from "geojson"

  interface Props {
    value: Point | null
  }

  let { value }: Props = $props()
</script>

{#if value}
  <div>Long: {parseFloat(value.coordinates[0].toFixed(6))}</div>
  <div>Lat: {parseFloat(value.coordinates[1].toFixed(6))}</div>
{/if}
