// frontend/src/components/Investor/InvestorManageHeader.vue
<template>
  <div>
    <ManageHeader
      :object="investor"
      :object-version="investorVersion"
      otype="investor"
      @add_comment="add_comment"
      @change_status="$emit('change_status', $event)"
      @delete="$emit('delete', $event)"
      @copy="$emit('copy', $event)"
      @send_to_review="show_send_to_review_overlay = true"
    >
      <template #heading>
        {{ investor.name }} <small>#{{ investor.id }}</small>
      </template>
      <template #overlays>
        <Overlay
          v-if="show_send_to_review_overlay"
          :title="$t('Submit for review')"
          @cancel="show_send_to_review_overlay = false"
          @submit="send_to_review"
        >
          <div class="mt-2" style="font-weight: bold">
            <label>
              <input required type="checkbox" />
              {{ $t("I've read and agree to the") }}
              <a href="/about/data-policy/" target="_blank">{{ $t("Data policy") }} </a
              >.
            </label>
          </div>
        </Overlay>
      </template>
    </ManageHeader>
  </div>
</template>

<script>
  import ManageHeader from "$components/Management/ManageHeader";
  import Overlay from "$components/Overlay";
  import gql from "graphql-tag";

  export default {
    name: "InvestorManageHeader",
    components: {
      Overlay,
      ManageHeader,
    },
    props: {
      investor: { type: Object, required: true },
      investorVersion: { type: [Number, String], default: null },
    },
    data() {
      return {
        show_send_to_review_overlay: false,
      };
    },
    methods: {
      send_to_review() {
        this.$emit("change_status", { transition: "TO_REVIEW" });
        this.show_send_to_review_overlay = false;
      },
      add_comment({ comment, send_to_user }) {
        this.$apollo
          .mutate({
            mutation: gql`
              mutation ($id: Int!, $version: Int, $comment: String!, $to_user_id: Int) {
                add_investor_comment(
                  id: $id
                  version: $version
                  comment: $comment
                  to_user_id: $to_user_id
                ) {
                  investorId
                  investorVersion
                }
              }
            `,
            variables: {
              id: +this.investor.id,
              version: this.investorVersion ? +this.investorVersion : null,
              comment: comment,
              to_user_id: send_to_user ? +send_to_user.id : null,
            },
          })
          .then(() => {
            this.$emit("reload");
          })
          .catch((error) => console.error(error));
      },
    },
  };
</script>

// frontend/src/components/Management/InvestorManageHeader.svelte
<script lang="ts">
  import { Client, gql } from "@urql/svelte"
  import { toast } from "@zerodevx/svelte-toast"
  import { createEventDispatcher } from "svelte"
  import { _ } from "svelte-i18n"

  import { goto } from "$app/navigation"
  import { page } from "$app/stores"

  import type { Investor } from "$lib/types/investor"

  import ManageOverlay from "$components/Management/ManageOverlay.svelte"

  import ManageHeader from "./ManageHeader.svelte"

  const dispatch = createEventDispatcher()

  export let investor: Investor
  export let investorVersion: number | undefined

  let showSendToReviewOverlay = false
  async function sendToReview({ detail: { comment } }) {
    await changeStatus({ detail: { transition: "TO_REVIEW", comment } })
    showSendToReviewOverlay = false
  }

  async function changeStatus({ detail: { transition, comment = "", toUser = null } }) {
    const { data, error } = await ($page.data.urqlClient as Client)
      .mutation<{
        change_investor_status: { investorId: number; investorVersion: number }
      }>(
        gql`
          mutation (
            $id: Int!
            $version: Int!
            $transition: WorkflowTransition!
            $comment: String
            $to_user_id: Int
          ) {
            change_investor_status(
              id: $id
              version: $version
              transition: $transition
              comment: $comment
              to_user_id: $to_user_id
            ) {
              investorId
              investorVersion
            }
          }
        `,
        {
          id: investor.id,
          version: investorVersion,
          transition,
          comment,
          to_user_id: toUser?.id,
        },
      )
      .toPromise()
    if (error) {
      if (error.graphQLErrors[0].message === "EDITING_OLD_VERSION")
        toast.push("You are trying to edit an old version!", { classes: ["error"] })
      else toast.push(`Unknown Problem: ${error}`, { classes: ["error"] })
      return
    }
    if (!data) {
      toast.push(`Unknown Problem: ${error}`, { classes: ["error"] })
      return
    }

    if (transition === "ACTIVATE") {
      await goto(`/investor/${data.change_investor_status.investorId}/`)
    } else if (investorVersion !== data.change_investor_status.investorVersion) {
      await goto(
        `/investor/${data.change_investor_status.investorId}/${data.change_investor_status.investorVersion}/`,
      )
    } else {
      dispatch("reload")
    }
  }

  function addComment({ detail: { comment, toUser } }) {
    $page.data.urqlClient
      .mutation(
        gql`
          mutation ($id: Int!, $version: Int, $comment: String!, $to_user_id: Int) {
            add_investor_comment(
              id: $id
              version: $version
              comment: $comment
              to_user_id: $to_user_id
            ) {
              investorId
              investorVersion
            }
          }
        `,
        {
          id: investor.id,
          version: investorVersion ?? null,
          comment: comment,
          to_user_id: toUser?.id,
        },
      )
      .toPromise()
      .then(() => dispatch("reload"))
      .catch(error => console.error(error))
  }

  function deleteInvestor({ detail: { comment } }) {
    // TODO this would be the place for issue #489
    $page.data.urqlClient
      .mutation(
        gql`
          mutation ($id: Int!, $version: Int, $comment: String) {
            investor_delete(id: $id, version: $version, comment: $comment)
          }
        `,
        { id: investor.id, version: investorVersion, comment },
      )
      .toPromise()
      .then(async dat => {
        //todo: if it was just a draft, and we deleted the whole thing, jump to investor list
        console.log(dat)
        if (investorVersion) await goto(`/investor/${investor.id}`)
        dispatch("reload")
      })
  }
</script>

<ManageHeader
  object={investor}
  objectVersion={investorVersion}
  otype="investor"
  on:addComment={addComment}
  on:changeStatus={changeStatus}
  on:delete={deleteInvestor}
  on:sendToReview={() => (showSendToReviewOverlay = true)}
>
  <div slot="heading">
    {investor.name}
    <small>#{investor.id}</small>
  </div>
</ManageHeader>

{#if showSendToReviewOverlay}
  <ManageOverlay
    bind:visible={showSendToReviewOverlay}
    title={$_("Submit for review")}
    commentInput
    on:submit={sendToReview}
  >
    <div class="mb-6">
      <label for="data-policy-checkbox" class="underline">{$_("Data policy")}</label>
      <label class="mt-1 block font-bold">
        <input required type="checkbox" id="data-policy-checkbox" />
        {$_("I've read and agree to the")}
        <a href="/about/data-policy/" target="_blank">{$_("Data policy")}</a>
        .
      </label>
    </div>
  </ManageOverlay>
{/if}
