// frontend/src/components/DataContainer.vue
<template>
  <div class="datacontainer">
    <ViewSwitcher />
    <FilterBar>
      <slot name="FilterBar"></slot>
    </FilterBar>
    <ContextBarMap />
    <div class="main-content">
      <slot></slot>
    </div>
  </div>
</template>

<script>
  import ContextBarMap from "$components/Data/ContextBarMap";
  import FilterBar from "$components/Data/FilterBar";
  import ViewSwitcher from "$components/Data/ViewSwitcher";

  export default {
    name: "DataContainer",
    components: { ContextBarMap, FilterBar, ViewSwitcher },
  };
</script>
<style lang="scss" scoped>
  .datacontainer {
    position: relative;
    padding: 0;
    width: 100%;
    height: calc(100vh - 60px - 31px);
    .main-content {
      width: 100%;
      height: 100%;
    }
  }
</style>

// frontend/src/components/Data/DataContainer.svelte
<script lang="ts">
  import ContextBarMap from "./ContextBarMap.svelte"
  import FilterBar from "./FilterBar.svelte"
  import ViewSwitcher from "./ViewSwitcher.svelte"
</script>

<div class="relative h-full w-full p-0">
  <ViewSwitcher />
  <FilterBar>
    <slot name="FilterBar" />
  </FilterBar>
  <ContextBarMap />
  <div class="h-full w-full">
    <slot />
  </div>
</div>
