// frontend/src/components/Fields/DisplayField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import { formfields } from "$lib/stores"

  import ArrayField from "$components/Fields/Display/ArrayField.svelte"
  import AutoField from "$components/Fields/Display/AutoField.svelte"
  import BooleanField from "$components/Fields/Display/BooleanField.svelte"
  import DateTimeField from "$components/Fields/Display/DateTimeField.svelte"
  import DecimalField from "$components/Fields/Display/DecimalField.svelte"
  import FileField from "$components/Fields/Display/FileField.svelte"
  import ForeignKeyField from "$components/Fields/Display/ForeignKeyField.svelte"
  import JSONActorsField from "$components/Fields/Display/JSONActorsField.svelte"
  import JSONDateAreaChoicesField from "$components/Fields/Display/JSONDateAreaChoicesField.svelte"
  import JSONDateAreaField from "$components/Fields/Display/JSONDateAreaField.svelte"
  import JSONDateChoiceField from "$components/Fields/Display/JSONDateChoiceField.svelte"
  import JSONExportsField from "$components/Fields/Display/JSONExportsField.svelte"
  import JSONJobsField from "$components/Fields/Display/JSONJobsField.svelte"
  import JSONLeaseField from "$components/Fields/Display/JSONLeaseField.svelte"
  import JSONLocationAreasField from "$components/Fields/Display/JSONLocationAreasField.svelte"
  import LengthField from "$components/Fields/Display/LengthField.svelte"
  import ManyToManyField from "$components/Fields/Display/ManyToManyField.svelte"
  import NanoIDField from "$components/Fields/Display/NanoIDField.svelte"
  import OCIDField from "$components/Fields/Display/OCIDField.svelte"
  import PointField from "$components/Fields/Display/PointField.svelte"
  import TextField from "$components/Fields/Display/TextField.svelte"
  import TypedChoiceField from "$components/Fields/Display/TypedChoiceField.svelte"
  import WorkflowInfosField from "$components/Fields/Display/WorkflowInfosField.svelte"
  import type { FormField } from "$components/Fields/fields"

  export let fieldname: string
  export let value
  export let model:
    | "deal"
    | "location"
    | "contract"
    | "datasource"
    | "investor"
    | "involvement" = "deal"

  export let showLabel = false
  export let wrapperClasses = "mb-3 leading-5 flex flex-wrap"
  export let labelClasses = "font-medium md:w-5/12 lg:w-4/12"
  export let valueClasses = "text-lm-dark dark:text-white md:w-7/12 lg:w-8/12"

  export let fileNotPublic = false
  export let targetBlank = false
  export let objectVersion: number | undefined = undefined

  let formfield: FormField
  $: formfield = { name: fieldname, ...$formfields[model][fieldname] }

  $: field = {
    DateField: DateTimeField,
    DateTimeField: DateTimeField,
    JSONActorsField: JSONActorsField,
    JSONDateAreaChoicesField: JSONDateAreaChoicesField,
    JSONDateAreaField: JSONDateAreaField,
    JSONDateChoiceField: JSONDateChoiceField,
    JSONExportsField: JSONExportsField,
    JSONJobsField: JSONJobsField,
    JSONLeaseField: JSONLeaseField,
    ManyToManyField: ManyToManyField,
    OCIDField: OCIDField,
  }[formfield.class]
</script>

<div
  data-class={formfield?.class ?? ""}
  data-name={formfield?.name ?? ""}
  class={wrapperClasses}
>
  {#if showLabel}
    <div class={labelClasses}>
      {$_(formfield.label)}
    </div>
  {/if}
  <div class={valueClasses}>
    {#if formfield.class === "AutoField"}
      <AutoField {value} {model} {formfield} {targetBlank} {objectVersion} />
    {:else if ["BooleanField", "NullBooleanField"].includes(formfield.class)}
      <BooleanField {value} {formfield} />
    {:else if ["ArrayField", "SimpleArrayField"].includes(formfield.class)}
      <ArrayField {value} {formfield} />
    {:else if formfield.class === "TypedChoiceField"}
      <TypedChoiceField {value} {formfield} />
    {:else if formfield.class === "PointField"}
      <PointField {value} {formfield} />
    {:else if formfield.class === "WorkflowInfosField"}
      <WorkflowInfosField {value} {formfield} />
    {:else if formfield.class === "NanoIDField"}
      <NanoIDField {value} {formfield} />
    {:else if ["CharField", "EmailField", "TextField", "URLField"].includes(formfield.class)}
      <TextField {value} {formfield} />
    {:else if ["DecimalField", "FloatField", "IntegerField"].includes(formfield.class)}
      <DecimalField {value} {formfield} />
    {:else if formfield.class === "LengthField"}
      <LengthField {value} {formfield} />
    {:else if ["CountryForeignKey", "CurrencyForeignKey", "ForeignKey", "InvestorForeignKey", "ModelChoiceField"].includes(formfield.class)}
      <ForeignKeyField {value} {formfield} />
    {:else if formfield.class === "FileField"}
      <FileField {value} {formfield} {fileNotPublic} />
    {:else if formfield.class === "JSONLocationAreasField"}
      <JSONLocationAreasField {value} {formfield} {model} on:toggleVisibility />
    {:else if field}
      <svelte:component this={field} {value} {model} {formfield} />
    {:else}
      <span class="italic text-red-600">Unknown field: {formfield.class}</span>
    {/if}
  </div>
</div>

// frontend/src/components/Fields/DisplayField.vue
<template>
  <div v-if="_visible" :class="wrapperClasses">
    <FieldLabel
      v-if="showLabel"
      :fieldname="fieldname"
      :label-classes="labelClasses"
      :model="model"
    />
    <div :class="valueClasses">
      <component
        :is="formfield.class"
        v-if="!custom_is_null(value)"
        :value="value"
        :formfield="formfield"
        :model="model"
        :file-not-public="fileNotPublic"
        :target-blank="targetBlank"
        :object-id="objectId"
      />
    </div>
  </div>
</template>

<script lang="ts">
  import ArrayField from "./Display/ArrayField.vue";
  import AutoField from "./Display/AutoField.vue";
  import BooleanField from "./Display/BooleanField.vue";
  import NullBooleanField from "./Display/BooleanField.vue";
  import DateField from "./Display/DateField.vue";
  import DateTimeField from "./Display/DateField.vue";
  import DecimalField from "./Display/DecimalField.vue";
  import FloatField from "./Display/DecimalField.vue";
  import IntegerField from "./Display/DecimalField.vue";
  import FileField from "./Display/FileField.vue";
  import ForeignKey from "./Display/ForeignKeyField.vue";
  import CountryForeignKey from "./Display/ForeignKeyField.vue";
  import InvestorForeignKey from "./Display/ForeignKeyField.vue";
  import WorkflowInfosField from "./Display/WorkflowInfosField.vue";

  import JSONActorsField from "./Display/JSONActorsField.vue";
  import JSONDateAreaChoicesField from "./Display/JSONDateAreaChoicesField.vue";
  import JSONDateAreaField from "./Display/JSONDateAreaField.vue";
  import JSONDateChoiceField from "./Display/JSONDateChoiceField.vue";
  import JSONExportsField from "./Display/JSONExportsField.vue";
  import JSONField from "./Display/JSONField.vue";
  import JSONJobsField from "./Display/JSONJobsField.vue";
  import JSONLeaseField from "./Display/JSONLeaseField.vue";
  import LengthField from "./Display/LengthField.vue";
  import ManyToManyField from "./Display/ManyToManyField.vue";
  import OCIDField from "./Display/OCIDField.vue";
  import PointField from "./Display/PointField.vue";
  import CharField from "./Display/TextField.vue";
  import EmailField from "./Display/TextField.vue";
  import TextField from "./Display/TextField.vue";
  import StatusField from "./Display/StatusField.vue";
  import URLField from "./Display/TextField.vue";
  import FieldLabel from "./FieldLabel.vue";
  import Vue from "vue";
  import type { FormField } from "$components/Fields/fields";
  import { custom_is_null } from "$utils/data_processing";

  export default Vue.extend({
    name: "DisplayField",
    components: {
      ArrayField,
      AutoField,
      BooleanField,
      CharField,
      DateField,
      DateTimeField,
      DecimalField,
      EmailField,
      FieldLabel,
      FileField,
      FloatField,
      ForeignKey,
      CountryForeignKey,
      InvestorForeignKey,
      IntegerField,
      JSONActorsField,
      JSONDateAreaChoicesField,
      JSONDateAreaField,
      JSONDateChoiceField,
      JSONExportsField,
      JSONField,
      JSONJobsField,
      JSONLeaseField,
      LengthField,
      ManyToManyField,
      NullBooleanField,
      PointField,
      StatusField,
      TextField,
      URLField,
      OCIDField,
      WorkflowInfosField,
    },
    props: {
      fieldname: { type: String, required: true },
      value: { required: true },
      model: { type: String, default: "deal" },
      showLabel: { type: Boolean, default: true },
      wrapperClasses: {
        type: Array,
        default: () => ["display-field-wrapper", "form-field", "row"],
      },
      labelClasses: {
        type: Array,
        default: () => ["display-field-label", "col-md-5", "col-lg-4"],
      },
      valueClasses: {
        type: Array,
        default: () => ["display-field-value", "col-md-7", "col-lg-8"],
      },
      fileNotPublic: { type: Boolean, default: false },
      visible: { type: Boolean, default: true },
      targetBlank: { type: Boolean, default: false },
      objectId: { type: Number, default: null, required: false },
    },
    data() {
      return { custom_is_null };
    },
    computed: {
      _visible(): boolean {
        if (!this.visible) return false;
        if (this.fieldname === "file_not_public") return false;
        if (this.formfield.class === "FileField") {
          return !this.fileNotPublic || this.$store.getters.userAuthenticated;
        }
        return true;
      },
      formfield(): FormField {
        return {
          name: this.fieldname,
          ...this.$store.state.formfields[this.model][this.fieldname],
        };
      },
    },
  });
</script>

<style lang="scss">
  .display-field-wrapper {
    margin-bottom: 0.7em;
    line-height: 1.2;
  }
  .display-field-label {
    font-weight: 500;
  }
  .display-field-value {
    line-height: 1.2;
    color: var(--color-lm-dark);
  }
</style>
