// newfront/src/components/Fields/Display/FileField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields";
  import { _ } from "svelte-i18n";

  export let formfield: FormField;
  export let value: string;
  export let model: string;
  export let fileNotPublic: boolean;

  // export default Vue.extend({
  //
  //   data() {
  //     return { media_url: import.meta.env.VITE_MEDIA_URL };
  //   },
</script>

<div class="file_field">
  <a href="{media_url}{value}" target="_blank">
    {#if fileNotPublic}
      <p class="fas fa-eye-slash mr-1 italic" />
      <p class="far fa-file-pdf" />

      {() => {
        value.replace("uploads/", "");
      }}
    {/if}
  </a>
</div>

// frontend/src/components/Fields/FileField.vue
<template>
  <div>
    <div v-if="readonly">
    <a :href="`${MEDIA_URL}${val}`" target="_blank">
      <i class="far fa-file-pdf"></i>
    </a>

    </div>
  </div>
</template>

<script>

  export default {
    props: ["formfield", "value", "readonly"],
    data() {
      return {
        val: this.value,
        MEDIA_URL: MEDIA_URL,
      };
    },
    methods: {
      emitVal() {
        this.$emit("input", this.val);
      },

    },
  };
</script>
