// frontend/src/views/Account/PasswordReset.vue
<template>
  <div>
    <PageTitle>{{ $t("Reset password") }}</PageTitle>
    <div class="flex justify-center items-center h-full w-full mb-4">
      <div class="w-[clamp(300px,80%,600px)] p-6 rounded border-2 border-[#4b4b4b]">
        <div v-if="form_submitted">
          If your email-address is registered with LandMatrix you should receive an
          email shortly
        </div>
        <form v-else @submit.prevent="submit">
          <label class="mb-4 block">
            {{ $t("Email") }}
            <input
              v-model="email"
              autocomplete="email"
              class="form-control block"
              :placeholder="$t('Email')"
              type="email"
            />
          </label>
          <button class="btn btn-primary block" type="submit">
            {{ $t("Reset password") }}
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import Vue from "vue";
  import PageTitle from "$components/PageTitle.vue";
  import { apolloClient } from "$utils/apolloclient";
  import gql from "graphql-tag";

  export default Vue.extend({
    name: "PasswordReset",
    components: { PageTitle },
    data() {
      return {
        email: null,
        form_submitted: false,
      };
    },
    created() {
      if (this.$store.getters.userAuthenticated) {
        if (this.$route.query.next)
          this.$router.push(this.$route.query.next.toString());
      }
    },
    methods: {
      submit() {
        apolloClient
          .mutate({
            mutation: gql`
              mutation ($email: String!) {
                password_reset(email: $email)
              }
            `,
            variables: { email: this.email },
          })
          .then(({ data }) => {
            if (data.password_reset) {
              this.form_submitted = true;
            }
          });
      },
    },
  });
</script>

// newfront/src/routes/account/password_reset/+page.svelte
<script lang="ts">
  import { Client, gql } from "@urql/svelte";
  import { _ } from "svelte-i18n";
  import { page } from "$app/stores";
  import HCaptcha from "$components/HCaptcha.svelte";
  import PageTitle from "$components/PageTitle.svelte";

  let email = "";
  let form_submitted = false;

  function submit() {
    ($page.data.urqlClient as Client)
      .mutation(
        gql`
          mutation ($email: String!, $token: String!) {
            password_reset(email: $email, token: $token)
          }
        `,
        { email, token }
      )
      .toPromise()
      .then(({ data }) => {
        if (data.password_reset) form_submitted = true;
      });
  }
  let token: string;
  let disabled = true;
  function captchaVerified(e: CustomEvent<{ token: string }>) {
    token = e.detail.token;
    disabled = false;
    console.log(token);
  }
</script>

<PageTitle>{$_("Reset password")}</PageTitle>
{#if form_submitted}
  <div class="text-center">
    {$_(
      "If your email-address is registered with Land Matrix you should receive an email shortly."
    )}
  </div>
{:else}
  <form on:submit|preventDefault={() => submit()}>
    <label class="mb-4 block">
      {$_("Email")}
      <input
        bind:value={email}
        autocomplete="email"
        class="inpt block"
        placeholder={$_("Email")}
        type="email"
      />
    </label>
    <div class="grid grid-cols-2 gap-4">
      <HCaptcha
        class="flex w-full justify-center"
        sitekey={import.meta.env.VITE_HCAPTCHA_SITEKEY ||
          "10000000-ffff-ffff-ffff-000000000001"}
        on:success={captchaVerified}
      />
      <div class="flex items-center justify-center">
        <button class="btn btn-primary w-full" type="submit" {disabled}>
          {$_("Reset password")}
        </button>
      </div>
    </div>
  </form>
{/if}
