// frontend/src/components/Shared/DealDisplayToggle.vue
<template>
  <div class="toggle-buttons">
    <a
      href=""
      :class="{ active: displayDealsCount }"
      @click.prevent="displayDealsCount = true"
      >No. of deals</a
    >
    <a
      href=""
      :class="{ active: !displayDealsCount }"
      @click.prevent="displayDealsCount = false"
      >Deal size</a
    >
  </div>
</template>

<script>
  export default {
    name: "DealDisplayToggle",
    computed: {
      displayDealsCount: {
        get() {
          return this.$store.state.map.displayDealsCount;
        },
        set(value) {
          this.$store.commit("setDisplayDealsCount", value);
        },
      },
    },
  };
</script>

<style lang="scss" scoped>
  .toggle-buttons {
    margin-top: 1.5em;
    margin-bottom: 5px;
    width: 100%;
    text-align: center;
    display: flex;
    justify-content: center;

    a {
      padding: 0.3em 0.5em;
      background-color: white;
      border: 1px solid var(--color-lm-light);
      color: black;
      font-weight: bold;
      font-size: 14px;

      &.active {
        background-color: var(--color-lm-orange);
        color: white;
      }
    }
  }
</style>

// frontend/src/components/DealDisplayToggle.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import { displayDealsCount } from "$components/Map/map_helper"

  $: displayDeals = $displayDealsCount ? "bg-orange text-white" : "bg-white"
  $: displaySize = !$displayDealsCount ? "bg-orange text-white" : "bg-white"
</script>

<div class="mt-8 flex justify-center text-center">
  <button
    type="button"
    on:click={() => displayDealsCount.set(true)}
    class="my-2 transform border py-2 px-3 font-bold duration-100 hover:underline {displayDeals}"
  >
    {$_("No. of deals")}
  </button>
  <button
    type="button"
    on:click={() => displayDealsCount.set(false)}
    class="my-2 transform border py-2 px-3 font-bold duration-100 hover:underline {displaySize}"
  >
    {$_("Deal size")}
  </button>
</div>
