// newfront/src/components/Footer.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import FacebookIcon from "$components/icons/FacebookIcon.svelte";
  import TwitterIcon from "$components/icons/TwitterIcon.svelte";
</script>

<footer class="px-4 py-1.5 relative bg-lm-dark text-sm text-white">
  <div class="text-center">
    <p class="mb-0">
      &copy; {new Date().getFullYear()} The Land Matrix |
      {$_("All rights reserved")}
    </p>
  </div>
  <div class="absolute right-4 top-[5px]">
    <a
      class="hover:text-orange-light"
      target="_blank"
      href="https://twitter.com/Land_Matrix"
    >
      <TwitterIcon />
    </a>
    <a
      class="ml-2 hover:text-orange-light"
      target="_blank"
      href="https://www.facebook.com/LandMatrix"
    >
      <FacebookIcon />
    </a>
  </div>
</footer>

// frontend/src/components/Footer.vue
<template>
  <footer>
    <div class="container">
      <div id="footer-etc" class="row">
        <div class="col-12 text-center">
          <p class="mb-0">
            <a :href="legacy_link">&copy; {{ currentyear }}</a>
            The Land Matrix | {{ $t("All rights reserved") }}
          </p>
        </div>
        <div class="social-buttons">
          <a target="_blank" href="https://twitter.com/Land_Matrix">
            <i class="lm-footer lm-twitter-square"></i>
          </a>
          <a target="_blank" href="https://www.facebook.com/LandMatrix">
            <i class="lm-footer lm-facebook-square"></i>
          </a>
        </div>
      </div>
    </div>
  </footer>
</template>

<script>
  export default {
    name: "Footer",
    data() {
      return {
        currentyear: new Date().getFullYear(),
      };
    },
    computed: {
      legacy_link() {
        let base = "/legacy";
        return base + this.$route.path;
      },
    },
  };
</script>

<style lang="scss" scoped>
  footer {
    background: var(--color-lm-dark);
    padding: 0 10px;
    font-size: 14px;
    color: white;
    font-weight: 400 !important;
    margin-top: 0;
    position: relative;

    .container {
      padding-top: 5px;
      padding-bottom: 5px;
    }
    hr {
      border-top: 1px solid #9b9b9b;
    }

    .lm-footer {
      font-size: 20px;
    }
    .social-buttons {
      position: absolute;
      right: 15px;
      bottom: 1px;
      a {
        margin-left: 1em;
        &:hover {
          text-decoration: none;
          color: var(--color-lm-orange-light);
        }
      }
    }
  }
</style>
