// frontend/src/components/Navbar/NavbarSearch.svelte
<script lang="ts">
  import cn from "classnames"
  import { onMount } from "svelte"
  import { _ } from "svelte-i18n"

  import { goto } from "$app/navigation"

  import type { Deal } from "$lib/types/deal"
  import type { Investor } from "$lib/types/investor"

  import NavDropDown from "$components/Navbar/NavDropDown.svelte"

  import SearchIcon from "../icons/SearchIcon.svelte"

  // $: user = $page.data.user

  interface SearchResult {
    id: number
    name: string
    url: string
    is_public?: boolean
    investor?: boolean
  }

  let searchString = ""
  let selectedSearchIndex = 0
  let searchResult: SearchResult[] = []
  let searchResultContainer: HTMLUListElement
  let deals: Deal[] = []
  let investors: Investor[] = []

  //  TODO do this with async typeahead to save on bandwidth
  async function getDeals() {
    // const { error, data } = await $page.data.urqlClient
    //   .query<{ deals: Deal[] }>(
    //     gql`
    //       query SDeals($subset: Subset) {
    //         deals(limit: 0, subset: $subset) {
    //           id
    //           country {
    //             id
    //             name
    //           }
    //           is_public
    //         }
    //       }
    //     `,
    //     {
    //       subset: user?.is_authenticated ? "UNFILTERED" : "PUBLIC",
    //     },
    //   )
    //   .toPromise()
    //
    // if (error || !data) {
    //   console.error(error)
    //   return
    // }
    //
    // deals = data.deals
  }

  async function getInvestors() {
    // const { error, data } = await $page.data.urqlClient
    //   .query<{ investors: Investor[] }>(
    //     gql`
    //       query SInvestors($subset: Subset) {
    //         investors(
    //           limit: 0
    //           subset: $subset
    //           filters: [{ field: "status", value: 4, exclusion: true }]
    //         ) {
    //           id
    //           name
    //         }
    //       }
    //     `,
    //     { subset: user?.is_authenticated ? "UNFILTERED" : "PUBLIC" },
    //   )
    //   .toPromise()
    //
    // if (error || !data) {
    //   console.error(error)
    //   return
    // }
    //
    // investors = data.investors
  }

  $: {
    // on search change
    selectedSearchIndex = 0
    searchResult =
      searchString.length >= 2
        ? [
            ...deals
              .filter(d => d.id.toString().includes(searchString))
              .map<SearchResult>(d => {
                let name = `#${d.id}`
                if (d.country) name += ` in ${d.country?.name}`
                return {
                  id: d.id,
                  name,
                  is_public: d.is_public,
                  url: `/deal/${d.id}/`,
                }
              }),
            ...investors
              .filter(
                i =>
                  i.id.toString().includes(searchString) ||
                  i.name.toLowerCase().includes(searchString.toLowerCase()),
              )
              .map<SearchResult>(i => {
                return {
                  id: i.id,
                  name: `${i.name} #${i.id}`,
                  url: `/investor/${i.id}/`,
                  investor: true,
                }
              }),
          ]
        : []
  }

  function searchKeyboardEvent(e) {
    if (["ArrowDown", "ArrowUp", "Enter"].includes(e.code)) {
      e.preventDefault()

      if (!searchResult.length) {
        return
      }

      switch (e.code) {
        case "ArrowDown":
          selectedSearchIndex = (selectedSearchIndex + 1) % searchResult.length
          searchResultContainer.children[selectedSearchIndex].scrollIntoView(false)
          return
        case "ArrowUp":
          selectedSearchIndex =
            selectedSearchIndex === 0
              ? searchResult.length - 1
              : selectedSearchIndex - 1
          searchResultContainer.children[selectedSearchIndex].scrollIntoView(false)
          return
        case "Enter":
          goto(searchResult[selectedSearchIndex].url)
          return
        default:
          return
      }
    }
  }

  onMount(() => {
    getDeals()
    getInvestors()
  })
</script>

<NavDropDown>
  <svelte:fragment slot="title">
    <div
      class="flex items-center justify-end bg-white px-2 lg:w-[250px] dark:bg-gray-900"
    >
      <input
        autocomplete="off"
        bind:value={searchString}
        class="inpt mr-3 hidden rounded xl:block"
        id="search"
        on:keydown={searchKeyboardEvent}
        placeholder={$_("Search for...")}
      />
      <SearchIcon class="h-6" />
    </div>
  </svelte:fragment>
  <div
    class="relative w-[300px] rounded bg-white p-2 shadow-lg xl:hidden dark:bg-gray-900"
  >
    <input
      autocomplete="off"
      bind:value={searchString}
      class="inpt"
      id="search"
      on:keydown={searchKeyboardEvent}
      placeholder={$_("Search")}
    />
  </div>
  {#if searchResult.length}
    <ul
      bind:this={searchResultContainer}
      id="search-result"
      class="w-full overflow-y-auto border-t-orange bg-white xl:absolute xl:z-50 xl:max-h-[55vh] xl:w-[300px] xl:shadow-xl dark:bg-gray-800"
    >
      {#each searchResult.filter((item, index) => index < 10) as item, index}
        <li>
          <a
            href={item.url}
            class={cn(
              "block border-2 px-1.5 py-1 transition duration-100 hover:text-white",
              selectedSearchIndex === index ? "border-gray-200" : "border-transparent",
              item.investor
                ? "text-pelorous hover:bg-pelorous"
                : "text-orange hover:bg-orange",
            )}
            class:opacity-40={!item.investor && !item.is_public}
          >
            {item.name}
          </a>
        </li>
      {/each}
    </ul>
  {/if}
</NavDropDown>

<style>
  :global(#search + button) {
    margin-left: -30px;
  }
</style>

// frontend/src/components/NavbarSearch.vue
<template>
  <li class="nav-item dropdown">
    <a
      id="searchDropdown"
      role="button"
      class="nav-link dropdown-toggle"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false"
      @click="focusSearch"
    >
      <i class="fa fa-search"></i>
    </a>
    <div class="dropdown-menu search-menu" style="padding: 0.5rem 1rem">
      <form class="input-group">
        <label for="search" class="nowrap">
          {{ $t("Search deals and investors") }}
          <input
            id="search"
            v-model="search"
            type="text"
            class="form-control"
            :placeholder="$t('ID or Name')"
            @keydown="searchKeyboardEvent"
          />
        </label>
      </form>
      <ul v-if="searchResult.length > 0" id="ulle">
        <li
          v-for="(d, i) in searchResult"
          :id="`${d.id}${d.investor}`"
          :key="`${d.id}${d.investor}`"
          :class="{ investor: d.investor, selected: selectedSearchIndex === i }"
        >
          <router-link :class="{ not_public: d.is_public === false }" :to="d.url">
            {{ d.name }}
          </router-link>
        </li>
      </ul>
    </div>
  </li>
</template>
<script>
  import gql from "graphql-tag";

  export default {
    name: "NavbarSearch",
    data() {
      return {
        search: "",
        showSearch: false,
        selectedSearchIndex: 0,
        deals: [],
        investors: [],
      };
    },
    apollo: {
      deals: {
        query: gql`
          query SDeals($subset: Subset) {
            deals(limit: 0, subset: $subset) {
              id
              country {
                id
                name
              }
              is_public
            }
          }
        `,
        variables() {
          return {
            subset: this.$store.getters.userAuthenticated ? "UNFILTERED" : "PUBLIC",
          };
        },
      },
      investors: {
        query: gql`
          query SInvestors($subset: Subset) {
            investors(limit: 0, subset: $subset) {
              id
              name
            }
          }
        `,
        variables() {
          return {
            subset: this.$store.getters.userAuthenticated ? "UNFILTERED" : "PUBLIC",
          };
        },
      },
    },
    computed: {
      searchResult() {
        if (this.search.length >= 2) {
          return [
            ...this.deals
              .filter((d) => d.id.toString().includes(this.search))
              .map((d) => {
                let name = `#${d.id}`;
                if (d.country) name += ` in ${d.country?.name}`;
                return {
                  id: d.id,
                  name,
                  is_public: d.is_public,
                  url: `/deal/${d.id}/`,
                };
              }),
            ...this.investors
              .filter(
                (i) =>
                  i.id.toString().includes(this.search) ||
                  i.name.toLowerCase().includes(this.search.toLowerCase())
              )
              .map((i) => {
                return {
                  id: i.id,
                  name: `${i.name} #${i.id}`,
                  url: `/investor/${i.id}/`,
                  investor: true,
                };
              }),
          ];
        }
        return [];
      },
    },
    watch: {
      search(newS, oldS) {
        if (newS.length !== oldS.length) this.selectedSearchIndex = 0;
      },
    },
    methods: {
      focusSearch() {
        setTimeout(() => document.getElementById("search").focus(), 100);
      },
      searchKeyboardEvent(e) {
        if (["ArrowDown", "ArrowUp"].includes(e.code)) {
          e.preventDefault();

          if (e.code === "ArrowDown") {
            this.selectedSearchIndex =
              (this.selectedSearchIndex + 1) % this.searchResult.length;
          } else {
            if (this.selectedSearchIndex === 0)
              this.selectedSearchIndex = this.searchResult.length - 1;
            else
              this.selectedSearchIndex =
                (this.selectedSearchIndex - 1) % this.searchResult.length;
          }

          let liel = this.searchResult[this.selectedSearchIndex];
          let offset = document.getElementById(`${liel.id}${liel.investor}`).offsetTop;
          document.getElementById("ulle").scrollTop = offset - 100;
        }

        if (e.code === "Enter") {
          this.$router.push(this.searchResult[this.selectedSearchIndex].url);
          e.preventDefault();
          document.getElementById("searchDropdown").click();
        }
      },
    },
  };
</script>

<style scoped lang="scss">
  .search-menu {
    //max-height: 60vh;

    ul {
      position: relative;
      max-height: 55vh;
      overflow-y: auto;
      margin: 1em 0 0;
      border-top: 1px solid var(--color-lm-orange);
      list-style: none;
      padding: 0.5em 0 0;
      li {
        &.selected {
          background: var(--color-lm-orange);
          a {
            color: white !important;
          }
        }
        &.investor {
          a {
            color: var(--color-lm-investor);
          }
        }
        &.investor.selected {
          background: var(--color-lm-investor);
          a {
            color: white !important;
          }
        }
      }
    }
  }
  .not_public {
    opacity: 0.4;
  }
</style>
