// newfront/src/components/Overlay.svelte
<script>
  import { createEventDispatcher } from "svelte";
  import { _ } from "svelte-i18n";
  import { fade, slide } from "svelte/transition";
  import { browser } from "$app/environment";

  const dispatch = createEventDispatcher();

  export let visible = false;
  export let hideable = true;
  export let title = null;

  export let showSubmit = false;
  export let submitDisabled = false;

  export let closeButtonText = $_("Cancel");

  function close() {
    if (hideable) {
      dispatch("close");
      visible = false;
    }
  }

  function escape_key(e) {
    if (e.key === "Escape") close();
  }

  $: if (browser) {
    if (visible) document.addEventListener("keydown", escape_key);
    else document.removeEventListener("keydown", escape_key);
  }
</script>

{#if visible}
  <div
    transition:fade={{ duration: 100 }}
    class="fixed inset-0 z-10 flex h-screen max-h-screen w-screen items-center justify-center bg-[rgba(0,0,0,0.3)] backdrop-blur-sm"
    on:click|self={close}
  >
    <div
      transition:slide={{ duration: 150 }}
      class="max-h-[99vh] w-[clamp(300px,70vw,800px)] overflow-y-auto border bg-white text-black shadow-xl {$$props.class ??
        ''}"
    >
      <form on:submit|preventDefault>
        {#if $$slots.header || title}
          <div class="border-b px-7 py-5">
            <slot name="header"><span class="font-bold">{title}</span></slot>
          </div>
        {/if}
        <div class="p-7">
          <slot />
        </div>

        <div class="border-t px-7 py-5 text-right">
          <button type="button" class="btn btn-cancel" on:click={close}>
            {closeButtonText}
          </button>
          {#if showSubmit}
            <button disabled={submitDisabled} type="submit" class="btn btn-primary">
              {title}
            </button>
          {/if}
        </div>
      </form>
    </div>
  </div>
{/if}

// frontend/src/components/Overlay.vue
<template>
  <div class="overlay-bg" @click.self="$emit('cancel')">
    <div class="overlay">
      <h3 v-if="title">{{ title }}</h3>
      <slot></slot>

      <div class="actions">
        <a class="btn btn-primary" @click.stop="submit">{{ title || $t("Submit") }}</a>
        <a class="btn btn-secondary" @click.stop="$emit('cancel')">
          {{ $t("Cancel") }}
        </a>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: "Overlay",
    props: {
      title: { type: String, default: "" },
    },
    data() {
      return {
        comment: "",
        confidential_reason: null,
        to_user_selected: null,
      };
    },
    created() {
      document.addEventListener("keydown", this.cancel);
    },
    beforeDestroy() {
      document.removeEventListener("keydown", this.cancel);
    },
    methods: {
      cancel(e) {
        if (e.key === "Escape") this.$emit("cancel");
      },
      submit() {
        this.$emit("submit");
      },
    },
  };
</script>

<style lang="scss" scoped>
  @import "../scss/colors";
  @import "node_modules/bootstrap/scss/functions";
  @import "node_modules/bootstrap/scss/variables";
  @import "node_modules/bootstrap/scss/mixins/_breakpoints";

  .overlay-bg {
    position: fixed;
    top: 0;
    width: 100vw;
    height: 100vh;
    z-index: 2000;
    background-color: rgba(black, 0.3);
    backdrop-filter: blur(3px);
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .overlay {
    width: 70vw;
    max-width: 800px;
    min-width: 300px;

    @include media-breakpoint-down(sm) {
      width: 85vw;
    }

    padding: 0.8em 1.8em 1.8em;
    box-shadow: 0 0 15px rgba(black, 0.5);
    color: $lm_dark;
    border-color: $lm_orange;
    background-color: $lm_light;

    .actions {
      margin-top: 1em;
      text-align: right;

      .btn {
        margin-left: 0.5em;
      }
    }
  }
</style>
