// newfront/src/components/Data/Charts/WebOfTransnationalDeals.svelte
<script lang="ts">
  import { onMount } from "svelte"

  import { LandMatrixRadialSpider } from "$lib/data/charts/webOfTransnationalDeals"
  import type { EdgeBundlingData } from "$lib/data/charts/webOfTransnationalDeals"
  import { filters } from "$lib/filters"

  import ChartWrapper from "$components/Data/Charts/ChartWrapper.svelte"
  import type { DownloadEvent } from "$components/Data/Charts/utils"

  export let title = ""
  export let deals: EdgeBundlingData

  let svgComp: SVGElement

  const redrawSpider = (deals, country_id): void =>
    LandMatrixRadialSpider(
      svgComp,
      deals,
      country_id,
      country => ($filters.country_id = +country),
    )

  const handleDownload = ({ detail: fileType }: DownloadEvent) => {
    console.log(fileType)
  }

  $: $filters && redrawSpider(deals, $filters.country_id)

  onMount(() => redrawSpider(deals, $filters.country_id))
</script>

<ChartWrapper {title} wrapperClasses="w-3/4" on:download={handleDownload}>
  <svg id="web-of-transnational-deals" bind:this={svgComp} />
</ChartWrapper>

<!--suppress CssUnusedSymbol, CssUnknownTarget -->
<style>
  :global(#incoming-marker) {
    fill: var(--color-lm-orange);
  }
  :global(#outgoing-marker) {
    fill: var(--color-lm-investor);
  }

  :global(path.incoming-highlighted) {
    stroke: var(--color-lm-orange);
    stroke-width: 2;
    marker-start: url(#incoming-marker);
  }
  :global(path.outgoing-highlighted) {
    stroke: var(--color-lm-investor);
    stroke-width: 2;
    marker-start: url(#outgoing-marker);
  }

  :global(path.incoming-permahighlight) {
    stroke: var(--color-lm-orange);
    stroke-width: 2.5;
    marker-start: url(#incoming-marker);
  }
  :global(path.outgoing-permahighlight) {
    stroke: var(--color-lm-investor);
    stroke-width: 2.5;
    marker-start: url(#outgoing-marker);
  }

  :global(text.incoming-highlighted) {
    font-size: 14px;
    cursor: pointer;
    font-weight: bold;
    fill: var(--color-lm-orange);
  }
  :global(text.outgoing-highlighted) {
    font-size: 14px;
    cursor: pointer;
    font-weight: bold;
    fill: var(--color-lm-investor);
  }
</style>

// frontend/src/views/Data/Charts/WebOfTransnationalDeals.vue
<template>
  <ChartsContainer>
    <template #default>
      <LoadingPulse v-if="$apollo.queries.transnational_deals.loading" />
      <div id="svg-container">
        <svg></svg>
      </div>
    </template>
    <template #ContextBar>
      <ContextBarWebOfTransnationalDeals :filters="filtered_filtersForGQL" />
    </template>
  </ChartsContainer>
</template>

<script>
  import ContextBarWebOfTransnationalDeals from "$components/Charts/ContextBarWebOfTransnationalDeals";
  import LoadingPulse from "$components/Data/LoadingPulse";
  import gql from "graphql-tag";
  import ChartsContainer from "./ChartsContainer";
  import { LandMatrixRadialSpider } from "./d3_hierarchical_edge_bundling";

  export default {
    name: "WebOfTransnationalDeals",
    components: { ChartsContainer, LoadingPulse, ContextBarWebOfTransnationalDeals },
    apollo: {
      transnational_deals: {
        query: gql`
          query WebOfTransnationalDeals($filters: [Filter]) {
            transnational_deals(filters: $filters)
          }
        `,
        variables() {
          return {
            filters: this.filtered_filtersForGQL,
          };
        },
      },
    },
    metaInfo() {
      return { title: this.$t("Web of transnational deals") };
    },
    beforeRouteEnter(to, from, next) {
      next((vm) => {
        vm.$store.dispatch("showContextBar", true);
      });
    },
    data() {
      return {
        transnational_deals: [],
      };
    },
    computed: {
      filtered_filtersForGQL() {
        return this.$store.getters.filtersForGQL.filter(
          (f) => f.field !== "country_id" && f.field !== "country.fk_region_id"
        );
      },
      filtered_country_id() {
        return this.$store.state.filters.filters.country_id;
      },
    },
    watch: {
      transnational_deals() {
        this.redrawSpider();
      },
      filtered_country_id() {
        this.redrawSpider();
      },
    },
    methods: {
      redrawSpider() {
        LandMatrixRadialSpider(
          this.transnational_deals,
          "#svg-container > svg",
          this.filtered_country_id,
          (country) => {
            this.$store.dispatch("setFilter", {
              filter: "country_id",
              value: +country,
            });
          }
        );
      },
    },
  };
</script>
<style lang="scss">
  @import "src/scss/colors";

  #svg-container {
    max-height: 100%;
    width: 100%;
    padding: 4em 2em 2em 2em;

    > svg {
      width: 100%;
      height: 100%;

      #incoming-marker {
        fill: $primary;
      }

      #outgoing-marker {
        fill: $lm_investor;
      }

      text {
        font-size: 14px;
        cursor: pointer;

        &.incoming-highlighted {
          font-weight: bold;
          fill: $primary;
        }

        &.outgoing-highlighted {
          font-weight: bold;
          fill: $lm_investor;
        }
      }

      path {
        &.incoming-highlighted {
          stroke: $primary;
          stroke-width: 2;
          marker-start: url(#incoming-marker);
        }

        &.outgoing-highlighted {
          stroke: $lm_investor;
          stroke-width: 2;
          marker-start: url(#outgoing-marker);
        }

        &.incoming-permahighlight {
          stroke: $primary;
          stroke-width: 2.5;
          marker-start: url(#incoming-marker);
        }

        &.outgoing-permahighlight {
          stroke: $lm_investor;
          stroke-width: 2.5;
          marker-start: url(#outgoing-marker);
        }
      }
    }
  }
</style>
