// frontend/src/components/Fields/Edit/LocationGoogleField.vue
<template>
  <div class="input-group">
    <input
      id="location-input"
      v-model="val"
      :placeholder="$t('Location')"
      :aria-label="$t('Location')"
      class="form-control"
    />
  </div>
</template>

<script>
  import { Loader } from "@googlemaps/js-api-loader";

  const loader = new Loader({
    apiKey: import.meta.env.VITE_GAPI_KEY,
    libraries: ["places"],
  });

  export default {
    props: {
      value: { type: String, required: false, default: "" },
      countryCode: { type: String, required: false, default: "" },
    },
    data() {
      return { autocomplete: null };
    },
    computed: {
      val: {
        get() {
          return this.value;
        },
        set() {},
      },
    },
    watch: {
      countryCode(cCode) {
        this.autocomplete.setComponentRestrictions({ country: cCode });
      },
    },
    created() {
      this.$nextTick(() => {
        const input_field = document.getElementById("location-input");

        let opts = { fields: ["geometry"], strictBounds: true };
        if (this.countryCode)
          opts.componentRestrictions = { country: this.countryCode };

        loader.load().then(() => {
          // eslint-disable-next-line no-undef
          this.autocomplete = new google.maps.places.Autocomplete(input_field, opts);
          this.autocomplete.addListener("place_changed", () => {
            const geometry = this.autocomplete.getPlace().geometry;
            this.$emit("change", {
              latLng: [geometry.location.lat(), geometry.location.lng()],
              viewport: geometry.viewport,
            });
            this.$emit("input", input_field.value);
          });
        });
      });
    },
  };
</script>

// frontend/src/routes/(main)/deal/edit/[...IDs]/LocationGoogleField.svelte
<script lang="ts">
  import { Loader } from "@googlemaps/js-api-loader?client"
  import { createEventDispatcher, onMount } from "svelte"
  import { _ } from "svelte-i18n"

  import { LABEL_CLASS, VALUE_CLASS, WRAPPER_CLASS } from "$components/Fields/consts"
  import Label2 from "$components/Fields/Display2/Label2.svelte"

  export let value = ""
  export let countryCode = ""
  export let fieldname: string
  export let label = ""
  export let wrapperClass = WRAPPER_CLASS
  export let labelClass = LABEL_CLASS
  export let valueClass = VALUE_CLASS

  let autocomplete: google.maps.places.Autocomplete
  let inputField: HTMLInputElement

  const dispatch = createEventDispatcher()

  let apiKey = import.meta.env.VITE_GAPI_KEY
  let loader: Loader

  function locationAutocomplete() {
    if (!apiKey) return
    if (!loader)
      loader = new Loader({
        apiKey,
        libraries: ["places"],
      })
    loader.load().then(google => {
      // noinspection TypeScriptUnresolvedVariable,TypeScriptUnresolvedFunction
      autocomplete = new google.maps.places.Autocomplete(inputField, {
        fields: ["geometry"],
        strictBounds: true,
        componentRestrictions: countryCode ? { country: countryCode } : undefined,
      })
      autocomplete?.addListener("place_changed", () => {
        const geometry = autocomplete.getPlace().geometry
        if (!geometry) return
        dispatch("change", {
          latLng: [geometry.location?.lat(), geometry.location?.lng()],
          viewport: geometry.viewport,
        })
        value = inputField.value
      })
    })
  }

  onMount(locationAutocomplete)

  $: autocomplete?.setComponentRestrictions({ country: countryCode })
</script>

<div class={wrapperClass} data-fieldname={fieldname}>
  {#if label}
    <Label2 value={label} class={labelClass} />
  {/if}
  <div class={valueClass}>
    <input
      bind:this={inputField}
      bind:value
      placeholder={$_("Location")}
      class="inpt"
    />
  </div>
</div>
