// frontend/src/components/Data/ContextBarContainer.vue
<template>
  <div class="context-bar-container" :class="{ collapsed: !showContextBar }">
    <Wimpel
      :showing="showContextBar"
      :flipped="true"
      @click="showContextBar = !showContextBar"
    />
    <div class="context-bar-container-content">
      <slot></slot>
    </div>
  </div>
</template>

<script lang="ts">
  import Wimpel from "$components/Wimpel.vue";
  import Vue from "vue";

  export default Vue.extend({
    name: "ContextBarContainer",
    components: { Wimpel },
    data() {
      return {};
    },
    computed: {
      showContextBar: {
        get() {
          return this.$store.state.showContextBar;
        },
        set(value) {
          this.$store.dispatch("showContextBar", value);
        },
      },
    },
    watch: {
      showContextBar(state) {
        this.$emit("visibility-changed", state);
      },
    },
  });
</script>

<style lang="scss" scoped>
  .context-bar-container {
    //border-left: 1px dotted var(--color-lm-dark);
    position: absolute;
    background-color: rgba(255, 255, 255, 0.95);
    top: 0;
    right: 0;
    bottom: 0;
    z-index: 10;
    display: flex;
    //transition: width 0.5s, min-width 0.5s;
    width: 20%;
    min-width: 220px;
    max-width: 300px;
    filter: drop-shadow(-3px 3px 3px rgba(0, 0, 0, 0.3));

    .context-bar-container-content {
      overflow-y: auto;
      padding: 0.5rem;
      width: 100%;
      text-align: center;

      h2.bar-title {
        font-size: 22px;
        margin-top: 0.5em;
        margin-bottom: 0.5em;
        line-height: 1.2;
      }

      h2,
      p,
      a {
        text-align: left;
      }

      p {
        font-size: 0.9rem;
      }
    }

    &.collapsed {
      width: 0;
      min-width: 0;

      .context-bar-container-content {
        display: none;
      }
    }
  }
</style>

// newfront/src/components/Data/ContextBarContainer.svelte
<script lang="ts">
  import { showContextBar } from "./index";
  import Wimpel from "./Wimpel.svelte";

  // showContextBar(state) {
  //   this.$emit("visibility-changed", state);
  // },
</script>

<div
  class="absolute bg-white/90 top-0 right-0 bottom-0 z-10 flex text-sm drop-shadow-[-3px_3px_3px_rgba(0,0,0,0.3)] {$showContextBar
    ? 'w-[clamp(220px,20%,300px)]'
    : 'w-0'}"
>
  <Wimpel
    showing={$showContextBar}
    flipped={true}
    on:click={() => showContextBar.set(!$showContextBar)}
  />
  <div
    class="w-full h-full overflow-y-auto overflow-x-hidden p-2"
    class:hidden={!$showContextBar}
  >
    <slot />
  </div>
</div>
