// frontend/src/components/Fields/Edit/LowLevelDateYearField.vue
<template>
  <div class="whitespace-nowrap input-group">
    <input
      ref="inputfield"
      v-model="val"
      type="text"
      class="form-control"
      :class="valid_state"
      placeholder="YYYY-MM-DD"
      :required="required"
    />
  </div>
</template>

<script>
  import dayjs from "dayjs";
  import customParseFormat from "dayjs/plugin/customParseFormat";

  dayjs.extend(customParseFormat);

  export default {
    name: "LowLevelDateYearField",
    props: {
      label: { type: String, required: false, default: "" },
      unit: { type: String, required: false, default: "" },
      required: { type: Boolean, default: false },
      value: { type: [String, Date], required: false, default: null },
    },
    data() {
      return {
        val: this.value,
        valid_state: null,
      };
    },
    watch: {
      value(newValue) {
        this.val = newValue;
      },
      val(v) {
        if (!v) {
          this.$emit("input", null);
          this.valid_state = "";
          this.$refs.inputfield.setCustomValidity("");
          return;
        }
        v = v.replace("/", "-").replace(".", "-").replace(",", "-").trim();
        this.checkValidity();
        this.$emit("input", v);
      },
    },
    mounted() {
      this.checkValidity();
    },
    methods: {
      checkValidity() {
        let field_valid =
          this.val === "" ||
          this.val === null ||
          dayjs(
            this.val,
            ["YYYY", "YYYY-M", "YYYY-M-D", "YYYY-MM", "YYYY-MM-D", "YYYY-MM-DD"],
            true
          ).isValid();

        if (field_valid) {
          this.valid_state = "";
          this.$refs.inputfield.setCustomValidity("");
        } else {
          this.valid_state = "is-invalid";
          this.$refs.inputfield.setCustomValidity(
            "Invalid format. Use YYYY, YYYY-MM or YYYY-MM-DD"
          );
        }
      },
    },
  };
</script>

// frontend/src/components/Fields/Edit2/LowLevelDateYearField.svelte
<script lang="ts">
  import dayjs from "dayjs"
  import customParseFormat from "dayjs/plugin/customParseFormat"
  import { onMount } from "svelte"
  import { _ } from "svelte-i18n"

  dayjs.extend(customParseFormat)

  export let name: string
  export let value: string | null
  export let required = false

  let inputField: HTMLInputElement

  let isValid: boolean
  const checkValidity = () => {
    isValid =
      !value ||
      dayjs(
        value,
        [
          "YYYY",
          "YYYY-MM",
          "YYYY-MM-DD",
          "YYYY-MM-D",
          "YYYY-M",
          "YYYY-M-DD",
          "YYYY-M-D",
        ],
        true,
      ).isValid()

    if (isValid) {
      inputField.setCustomValidity("")
    } else {
      inputField.setCustomValidity(
        $_("Invalid format. Use YYYY, YYYY-MM or YYYY-MM-DD"),
      )
    }
  }

  const onInput = (event: Event) => {
    const targetValue = (event.target as HTMLInputElement).value

    value =
      targetValue === ""
        ? null
        : targetValue
            .replaceAll("/", "-")
            .replaceAll(".", "-")
            .replaceAll(",", "-")
            .trim()

    checkValidity()
  }

  onMount(checkValidity)
</script>

<div class="relative">
  <input
    bind:this={inputField}
    class="inpt w-36 {$$props.class ?? ''}"
    maxlength="10"
    {name}
    on:input|preventDefault={onInput}
    placeholder={$_("YYYY-MM-DD")}
    {required}
    type="text"
    value={value ?? ""}
  />
  {#if !isValid}
    <span class="absolute right-0 top-full whitespace-nowrap text-xs text-red-700">
      YYYY, YYYY-MM or YYYY-MM-DD
    </span>
  {/if}
</div>
