// frontend/src/components/Fields/Display/DecimalField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import type { FormField } from "$components/Fields/fields"

  export let formfield: FormField
  export let value: number
</script>

<div class="decimal_field whitespace-nowrap" data-name={formfield?.name ?? ""}>
  {value?.toLocaleString("fr") ?? "—"}
  {#if value && formfield.unit}
    <span>{$_(formfield.unit)}</span>
  {/if}
</div>

// frontend/src/components/Fields/Display/DecimalField.vue
<template>
  <div class="decimal_field whitespace-nowrap">
    {{ val }}
    <span v-if="formfield.unit">{{ formfield.unit }}</span>
  </div>
</template>

<script lang="ts">
  import Vue, { PropType } from "vue";
  import type { FormField } from "$components/Fields/fields";

  export default Vue.extend({
    props: {
      formfield: { type: Object as PropType<FormField>, required: true },
      value: { type: Number, required: true },
      model: { type: String, required: true },
    },
    computed: {
      val(): string {
        if (this.formfield.choices) {
          return this.formfield.choices[this.value];
        }
        return this.value.toLocaleString("fr");
      },
    },
  });
</script>
