// frontend/src/components/Fields/Display/FileField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields"
  import EyeSlashIcon from "$components/icons/EyeSlashIcon.svelte"
  import FilePdfIcon from "$components/icons/FilePdfIcon.svelte"

  export let value: string
  export let formfield: FormField
  export let fileNotPublic = false
</script>

<div class="file_field" data-name={formfield?.name ?? ""}>
  {#if value}
    <a href="{import.meta.env.VITE_MEDIA_URL}{value}" rel="noreferrer" target="_blank">
      {#if fileNotPublic}
        <EyeSlashIcon />
      {/if}
      <FilePdfIcon />
      {value.replace("uploads/", "")}
    </a>
  {:else}
    —
  {/if}
</div>

// frontend/src/components/Fields/Display/FileField.vue
<template>
  <div class="file_field">
    <a :href="`${media_url}${value}`" target="_blank">
      <i v-if="fileNotPublic" class="fas fa-eye-slash mr-1"></i>
      <i class="far fa-file-pdf"></i>
      {{ value.replace("uploads/", "") }}
    </a>
  </div>
</template>

<script lang="ts">
  import Vue from "vue";
  import type { PropType } from "vue";
  import type { FormField } from "$components/Fields/fields";

  export default Vue.extend({
    props: {
      formfield: { type: Object as PropType<FormField>, required: true },
      value: { type: String, required: true },
      model: { type: String, required: true },
      fileNotPublic: { type: Boolean, default: false },
    },
    data() {
      return { media_url: import.meta.env.VITE_MEDIA_URL };
    },
  });
</script>
