// newfront/src/components/Fields/Display/ForeignKeyField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields";
  import type { Country } from "$lib/types/wagtail";
  import { countries } from "$lib/stores";

  export let formfield: FormField;
  export let value: object;
  export let model: string;

  $: calc_name = () => {
    if (!value || !value.id) return "";
    if (formfield.related_model === "Country" && $countries) {
      return $countries.find((c: Country) => c.id === this.value.id).name;
    }
    return value.username ?? value.name ?? value.id;
  };
</script>

<div class="foreignkey_field">
  {#if formfield.related_model === "Investor"}
    <a class="investor" target="_blank">
      <!--      to="{ name: 'investor_detail', params: { investorId: value.id } }"-->

      {value.name} (#{value.id})
    </a>
  {:else}{calc_name()}
  {/if}
</div>

// frontend/src/components/Fields/Display/ForeignKeyField.vue
<template>
  <div class="foreignkey_field">
    <router-link
      v-if="formfield.related_model === 'Investor'"
      class="investor"
      target="_blank"
      :to="{ name: 'investor_detail', params: { investorId: value.id } }"
    >
      {{ value.name }} (#{{ value.id }})
    </router-link>
    <template v-else> {{ calc_name }} </template>
  </div>
</template>

<script lang="ts">
  import Vue, { PropType } from "vue";
  import type { FormField } from "$components/Fields/fields";
  import type { Country } from "$types/wagtail";

  export default Vue.extend({
    props: {
      formfield: { type: Object as PropType<FormField>, required: true },
      value: { type: Object, required: true },
      model: { type: String, required: true },
    },
    computed: {
      calc_name(): string {
        if (!this.value || !this.value.id) return "";
        if (this.formfield.related_model === "Country" && this.$store.state.countries) {
          return this.$store.state.countries.find(
            (c: Country) => c.id === this.value.id
          ).name;
        }
        return this.value.username ?? this.value.name ?? this.value.id;
      },
    },
  });
</script>
