// frontend/src/components/Fields/Display/JSONDateChoiceField.vue
<template>
  <div class="jsondatechoice_field whitespace-nowrap">
    <div v-for="val in vals" :class="{ 'font-weight-bold': val.current }">
      <span>{{ date_and_current(val) }}</span>
      <span v-if="val.choice">{{ mapChoices(val.choice) }}</span>
    </div>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";

  export default {
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ date: null, value: null }],
      };
    },
  };
</script>

// frontend/src/components/Fields/Display/JSONDateChoiceField.svelte
<script lang="ts">
  import { ImplementationStatus, NegotiationStatus } from "$lib/types/deal"

  import {
    dateCurrentFormat,
    mapChoices,
  } from "$components/Fields/Display/jsonHelpers.ts"
  import type { FormField } from "$components/Fields/fields"

  type JSONDateChoiceFieldType = {
    current?: boolean
    date: string
    choice: NegotiationStatus | ImplementationStatus
  }

  export let formfield: FormField
  export let value: JSONDateChoiceFieldType[] = []
</script>

<div class="jsondatechoice_field whitespace-nowrap" data-name={formfield?.name ?? ""}>
  {#each value ?? [] as val}
    <div class:font-bold={val.current}>
      <span>{dateCurrentFormat(val)}</span>
      {#if val.choice}
        {mapChoices(val.choice, formfield.choices)}
      {/if}
    </div>
  {/each}
</div>
