// frontend/src/components/Fields/Display/JSONDateAreaChoicesField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import type { IntentionOfInvestment } from "$lib/types/deal"

  import { dateCurrentFormat } from "$components/Fields/Display/jsonHelpers"
  import type { FormField } from "$components/Fields/fields"
  import CircleNotchIcon from "$components/icons/CircleNotchIcon.svelte"

  type JSONDateAreaChoicesFieldType = {
    current?: boolean
    name: string
    area?: string
    choices: Array<IntentionOfInvestment>
  }

  export let formfield: FormField
  export let value: JSONDateAreaChoicesFieldType[] = []
</script>

<div class="jsondateareachoices_field" data-name={formfield?.name ?? ""}>
  {#each value ?? [] as val}
    <div class:font-bold={val.current}>
      <span>{dateCurrentFormat(val)}</span>
      {#if val.choices}
        {val.choices.map(v => formfield.choices[v]).join(", ")}
      {/if}
      {#if val.area}
        (<CircleNotchIcon /> {val.area.toLocaleString("fr")} {$_("ha")})
      {/if}
    </div>
  {/each}
</div>

// frontend/src/components/Fields/Display/JSONDateAreaChoicesField.vue
<template>
  <div class="jsondateareachoices_field">
    <div v-for="val in vals" :class="{ 'font-weight-bold': val.current }">
      <span>{{ date_and_current(val) }} </span>
      <span v-if="val.choices">{{ mapChoices(val.choices) }}</span>
      <span v-if="val.area">
        (<i class="fas fa-circle-notch"></i> {{ val.area.toLocaleString("fr") }} ha)
      </span>
    </div>
  </div>
</template>

<script>
  import Vue from "vue";
  import JSONFieldMixin from "../JSONFieldMixin";

  export default Vue.extend({
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ date: null, value: null }],
      };
    },
  });
</script>
