// frontend/src/components/Fields/Display/JSONExportsField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import { dateCurrentFormat } from "$components/Fields/Display/jsonHelpers"
  import type { FormField } from "$components/Fields/fields"
  import CircleNotchIcon from "$components/icons/CircleNotchIcon.svelte"
  import PlaneIcon from "$components/icons/PlaneIcon.svelte"
  import WeightIcon from "$components/icons/WeightIcon.svelte"

  type JSONExportsFieldType = {
    current?: boolean
    area?: string
    yield?: string
    export?: string
    choices: Array<{ [key: string]: string }>
  }

  export let value: JSONExportsFieldType[] = []
  export let formfield: FormField
</script>

<div class="jsonexports_field whitespace-nowrap" data-name={formfield?.name ?? ""}>
  {#each value ?? [] as val}
    <div class:font-bold={val.current}>
      <span>{dateCurrentFormat(val)}</span>
      {#if val.choices}
        {val.choices.map(v => formfield.choices[v]).join(", ")}
      {/if}{#if val.area}
        <span>
          <CircleNotchIcon />
          {val.area.toLocaleString("fr")}
          {$_("ha")}
        </span>
      {/if}{#if val.yield}
        <span class="mx-2">
          <WeightIcon />
          {val.yield.toLocaleString("fr")}
          {$_("tons")}
        </span>
      {/if}{#if val.export}
        <span class="mx-2">
          <PlaneIcon />
          {val.export.toLocaleString("fr")} %
        </span>
      {/if}
    </div>
  {/each}
</div>

// frontend/src/components/Fields/Display/JSONExportsField.vue
<template>
  <div class="jsonexports_field whitespace-nowrap">
    <div v-for="val in vals" :class="{ 'font-weight-bold': val.current }">
      <span>{{ date_and_current(val) }} </span>
      <span v-if="val.choices">{{ mapChoices(val.choices) }}</span>
      <span v-if="val.area" class="mx-2">
        <i class="fas fa-circle-notch"></i> {{ val.area.toLocaleString("fr") }} ha
      </span>
      <span v-if="val.yield" class="mx-2">
        <i class="fas fa-weight-hanging"></i> {{ val.yield.toLocaleString("fr") }} tons
      </span>
      <span v-if="val.export" class="mx-2">
        <i class="fas fa-plane-departure"></i> {{ val.export.toLocaleString("fr") }} %
      </span>
    </div>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";

  export default {
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ date: null, value: null }],
      };
    },
  };
</script>
