// frontend/src/components/Fields/Display/JSONJobsField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import { dateCurrentFormat } from "$components/Fields/Display/jsonHelpers"
  import type { FormField } from "$components/Fields/fields"

  type JSONJobsFieldType = {
    current?: boolean
    date: string
    jobs?: string
    employees?: string
    workers?: string
    choices?: Array<{ [key: string]: string }>
  }

  export let formfield: FormField
  export let value: JSONJobsFieldType[] = []
</script>

<ul>
  {#each value ?? [] as val}
    <li class:font-bold={val.current}>
      {dateCurrentFormat(val)}
      {#if val.jobs}
        <span class="mx-2">
          {val.jobs.toLocaleString("fr")}
          {$_("jobs")}
        </span>
      {/if}{#if val.employees}
        <span class="mx-2">
          {val.employees.toLocaleString("fr")}
          {$_("employees")}
        </span>
      {/if}{#if val.workers}
        <span class="mx-2">
          {val.workers.toLocaleString("fr")}
          {$_("workers")}
        </span>
      {/if}
    </li>
  {/each}
</ul>

// frontend/src/components/Fields/Display/JSONJobsField.vue
<template>
  <div class="nowrap">
    <div v-for="val in vals" :class="{ 'font-weight-bold': val.current }">
      <span>{{ date_and_current(val) }}</span>
      <span v-if="val.jobs" class="mx-2"> {{ val.jobs.toLocaleString() }} jobs </span>
      <span v-if="val.employees" class="mx-2">
        {{ val.employees.toLocaleString() }} employees
      </span>
      <span v-if="val.workers" class="mx-2">
        {{ val.workers.toLocaleString() }} workers
      </span>
    </div>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";

  export default {
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ date: null, value: null }],
      };
    },
  };
</script>
