// frontend/src/components/Fields/Display/JSONDateAreaField.vue
<template>
  <div class="jsondatearea_field whitespace-nowrap">
    <div v-for="val in vals" :class="{ 'font-weight-bold': val.current }">
      <span>{{ date_and_current(val) }}</span>
      <span v-if="val.area">{{ val.area.toLocaleString("fr") }} ha</span>
    </div>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";

  export default {
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ date: null, value: null }],
      };
    },
  };
</script>

// frontend/src/components/Fields/Display/JSONDateAreaField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import { dateCurrentFormat } from "$components/Fields/Display/jsonHelpers"
  import type { FormField } from "$components/Fields/fields"

  type JSONDateAreaFieldType = {
    area: string
    date: string
    current?: boolean
  }

  export let formfield: FormField
  export let value: JSONDateAreaFieldType[] = []
</script>

<div class="jsondatearea_field whitespace-nowrap" data-name={formfield?.name ?? ""}>
  {#each value ?? [] as val}
    <div class:font-bold={val.current}>
      <span>{dateCurrentFormat(val)}</span>
      {#if val.area}
        {val.area.toLocaleString("fr")} {$_("ha")}
      {/if}
    </div>
  {/each}
</div>
