// frontend/src/components/Fields/Display/JSONActorsField.svelte
<script lang="ts">
  import { mapChoices } from "$components/Fields/Display/jsonHelpers"
  import type { FormField } from "$components/Fields/fields"

  enum ActorRole {
    TRADITIONAL_LAND_OWNERS_OR_COMMUNITIES = "TRADITIONAL_LAND_OWNERS_OR_COMMUNITIES",
    GOVERNMENT_OR_STATE_INSTITUTIONS = "GOVERNMENT_OR_STATE_INSTITUTIONS",
    TRADITIONAL_LOCAL_AUTHORITY = "TRADITIONAL_LOCAL_AUTHORITY",
    BROKER = "BROKER",
    INTERMEDIARY = "INTERMEDIARY",
    OTHER = "OTHER",
  }

  type JSONActorsFieldType = {
    name: string
    role: ActorRole
  }

  export let formfield: FormField
  export let value: JSONActorsFieldType[] = []
</script>

<ul class="jsonactors_field list-disc pl-5" data-name={formfield?.name ?? ""}>
  {#each value ?? [] as val}
    <li>
      <span>{val.name}</span>
      {#if val.role}
        <span class="text-sm font-light">
          ({mapChoices(val.role, formfield.choices)})
        </span>
      {/if}
    </li>
  {/each}
</ul>

// frontend/src/components/Fields/Display/JSONActorsField.vue
<template>
  <div class="jsonactors_field nowrap">
    <div v-for="val in vals">
      <span>{{ val.name }}</span>
      <span v-if="val.role" class="font-weight-light">
        ({{ mapChoices(val.role) }})
      </span>
    </div>
  </div>
</template>

<script lang="ts">
  import JSONFieldMixin from "../JSONFieldMixin";
  import Vue from "vue";

  export default Vue.extend({
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ name: null, role: null }],
      };
    },
  });
</script>
