// newfront/src/components/Fields/Display/JSONDateAreaChoicesField.svelte
<script lang="ts">
  import { date_and_current, mapChoices } from "$components/Fields/Display/jsonHelpers";
  import type { FormField } from "$components/Fields/fields";

  export let formfield: FormField;
  export let value: boolean;
  export let model: string;
  let vals = value ? value : [{ name: null, role: null }];
</script>

<div class="jsondateareachoices_field">
  {#each vals as val}
    <div class={() => (val.current ? "font-weight-bold" : "")}>
      <span>{date_and_current(val)} </span>
      {#if val.choices}
        {mapChoices(val.choices, formfield.choices)}
      {/if}
      {#if val.area}
        (<i class="fas fa-circle-notch" />
        {val.area.toLocaleString("fr")} ha)
      {/if}
    </div>
  {/each}
</div>

// frontend/src/components/Fields/Display/JSONDateAreaChoicesField.vue
<template>
  <div class="jsondateareachoices_field">
    <div v-for="val in vals" :class="{ 'font-weight-bold': val.current }">
      <span>{{ date_and_current(val) }} </span>
      <span v-if="val.choices">{{ mapChoices(val.choices) }}</span>
      <span v-if="val.area">
        (<i class="fas fa-circle-notch"></i> {{ val.area.toLocaleString("fr") }} ha)
      </span>
    </div>
  </div>
</template>

<script>
  import Vue from "vue";
  import JSONFieldMixin from "../JSONFieldMixin";

  export default Vue.extend({
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ date: null, value: null }],
      };
    },
  });
</script>
