// frontend/src/components/Fields/Display/LengthField.vue
<template>
  <div class="length_field">
    <a href="#" @click.prevent="displayDeals = !displayDeals">{{ value.length }}</a>
    <div v-if="displayDeals">
      <span v-for="val in value" :key="val.id">
        <br />
        <router-link :to="{ name: 'deal_detail', params: { dealId: val.id } }">
          #{{ val.id }}
        </router-link>
      </span>
    </div>
  </div>
</template>

<script lang="ts">
  import Vue from "vue";
  import type { PropType } from "vue";
  import type { FormField } from "$components/Fields/fields";

  export default Vue.extend({
    props: {
      formfield: { type: Object as PropType<FormField>, required: true },
      value: { type: [Array, Object], required: true },
      model: { type: String, required: true },
    },
    data() {
      return {
        displayDeals: false,
      };
    },
  });
</script>

// frontend/src/components/Fields/Display/LengthField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields"

  type ForeignKey = {
    id: number
  }

  export let value: ForeignKey[] = []
  export let formfield: FormField

  let displayDeals = false
</script>

<div class="length_field" data-name={formfield?.name ?? ""}>
  {#if value.length > 0}
    <button
      class="text-orange"
      type="button"
      on:click={() => (displayDeals = !displayDeals)}
    >
      {value.length}
    </button>
    {#if displayDeals}
      <ul>
        {#each value as val (val.id)}
          <li><a href="/deal/{val.id}">#{val.id}</a></li>
        {/each}
      </ul>
    {/if}
  {/if}
</div>
