// frontend/src/components/Fields/Display/ManyToManyField.vue
<template>
  <div>
    <template v-if="formfield.related_model === 'Investor'" v-for="val in value">
      <router-link
        class="investor"
        target="_blank"
        :to="{ name: 'investor_detail', params: { investorId: val.id } }"
      >
        {{ val.name }} (#{{ val.id }})
      </router-link>
      <br />
    </template>
    <template v-else>
      {{ value }}
    </template>
  </div>
</template>

<script>
  export default {
    name: "ManyToManyField",
    props: ["formfield", "value", "model"],
  };
</script>

// frontend/src/components/Fields/Display/ManyToManyField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields"

  type ForeignKey = {
    id: number
    name?: string
    username?: string
  }

  export let formfield: FormField
  export let value: ForeignKey
</script>

{#if formfield.related_model === "Investor"}
  <ul>
    {#each value as val}
      <li>
        <a
          class="investor"
          target="_blank"
          rel="noreferrer"
          href="/investor/{value.id}"
        >
          {val.name} (#{val.id})
        </a>
      </li>
    {/each}
  </ul>
{:else}
  {value}
{/if}
