// frontend/src/components/Fields/Display/OCIDField.vue
<template>
  <div>
    <div>{{ value }}</div>
    <div><a :href="ocidUrl" target="_blank">{{ $t("Access more information about this contract on OpenLandContracts.org") }}</a></div>
  </div>
</template>

<script>
  export default {
    props: {
      formfield: { type: Object, required: true },
      value: { type: String, required: true },
      model: { type: String, required: true },
    },
    computed: {
      ocidUrl() {
        return `https://www.openlandcontracts.org/contract/${this.value}/view#/pdf`;
      }
    }
  };
</script>

// frontend/src/components/Fields/Display/OCIDField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import type { FormField } from "$components/Fields/fields"

  export let formfield: FormField
  export let value: string
</script>

{#if value}
  {value}
  <a
    href="https://www.openlandcontracts.org/contract/{value}/view#/pdf"
    target="_blank"
    rel="noreferrer"
  >
    {$_("Access more information about this contract on OpenLandContracts.org")}
  </a>
{:else}
  —
{/if}
