// frontend/src/components/Fields/Display/PointField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields"

  export let value: { lat?: number; lng?: number } | null
  export let formfield: FormField

  // @fixme JSON_Field
  $: value = value ?? {}
</script>

{#if value.lat}
  <div>Lat: {parseFloat(value.lat.toFixed(8))}</div>
{/if}
{#if value.lng}
  <div>Lng: {parseFloat(value.lng.toFixed(8))}</div>
{/if}

// frontend/src/components/Fields/Display/PointField.vue
<template>
  <div>
    <div v-if="value.lat">Lat: {{ parseFloat(value.lat.toFixed(8)) }}</div>
    <div v-if="value.lng">Lng: {{ parseFloat(value.lng.toFixed(8)) }}</div>
  </div>
</template>

<script lang="ts">
  import type { PropType } from "vue";
  import type { FormField } from "$components/Fields/fields";
  import Vue from "vue";

  export default Vue.extend({
    props: {
      formfield: { type: Object as PropType<FormField>, required: true },
      value: { type: [Array, Object], required: true },
      model: { type: String, required: true },
    },
  });
</script>
