// newfront/src/components/Fields/Display/StatusField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields";
  import { _ } from "svelte-i18n";
  import { combined_status_fn } from "./choices";

  export let formfield: FormField;
  export let value: number[];
  export let model: string;

  $: display_status = $_(combined_status_fn(value[0], value[1], true));
</script>

<span class="status_field">{display_status}</span>

// frontend/src/components/Fields/Display/StatusField.vue
<template>
  <span class="status_field">{{ display_status }}</span>
</template>

<script lang="ts">
  import { combined_status_fn } from "$utils/choices";
  import Vue from "vue";
  import type { PropType } from "vue";

  export default Vue.extend({
    props: {
      formfield: { type: Object, required: true },
      value: { type: Array as PropType<number[]>, required: true },
      model: { type: String, required: true },
    },
    computed: {
      display_status() {
        return this.$t(combined_status_fn(this.value[0], this.value[1], true));
      },
    },
  });
</script>
