// frontend/src/components/Fields/Display/TextField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields"

  export let value: string
  export let formfield: FormField
</script>

{#if !value}
  —
{:else if formfield.class === "URLField"}
  <a href={value} target="_blank" rel="noreferrer">{new URL(value).hostname}</a>
{:else}
  {value}
{/if}

// frontend/src/components/Fields/Display/TextField.vue
<template>
  <div>
    <template v-if="formfield.class === 'URLField'">
      <a :href="value" target="_blank">{{ value }}</a>
    </template>
    <template v-else>
      {{ parseVal(value) }}
    </template>
  </div>
</template>

<script lang="ts">
  import { flatten_choices } from "$utils";
  import Vue, { PropType } from "vue";
  import type { FormField } from "$components/Fields/fields";

  export default Vue.extend({
    props: {
      formfield: { type: Object as PropType<FormField>, required: true },
      value: { type: String, required: true },
      model: { type: String, required: true },
    },
    methods: {
      parseVal(val: string): string {
        if (!val) return "n/a";
        if (this.formfield.choices) {
          let choices = flatten_choices(this.formfield.choices, true);
          return choices ? choices[val] : val;
        }
        return val;
      },
    },
  });
</script>
