// frontend/src/components/Fields/Display/ArrayField.vue
<template>
  <div>
    <span v-html="parseValues(value)"></span>
  </div>
</template>

<script>
  import { flatten_choices } from "/utils";
  import { intention_of_investment_map } from "/choices";

  export default {
    props: ["formfield", "value", "model"],
    methods: {
      parseValues: function (value) {
        if (this.formfield.name === "current_intention_of_investment") {
          return value
            .map((ioi) => {
              let [intention, icon] = intention_of_investment_map[ioi];
              return `<span class="ioi-label">
                    <i class="${icon}"></i> ${this.$t(intention)}
                    </span>`;
            })
            .join(" ");
        }

        let choices = flatten_choices(this.formfield.choices);
        let ret = "";
        if (value instanceof Array) {
          if (choices) {
            ret += value.map((v) => choices[v]).join(", ");
          } else ret += value.join(", ");
        } else {
          if (choices) ret += choices[value];
          else ret += value;
        }
        return ret;
      },
    },
  };
</script>

// newfront/src/components/Fields/Display/ArrayField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import type { FormField } from "$components/Fields/fields";
  import { intention_of_investment_map } from "./choices";

  export let formfield: FormField;
  export let value: string[];
  export let model: string;

  export function parseValues(value) {
    if (formfield.name === "current_intention_of_investment") {
      return value
        .map((ioi) => {
          let [intention, icon] = intention_of_investment_map[ioi];
          // TODO: Charlotte hier noch SVGS
          return `<span class="ioi-label">
                    <i class="${icon}"></i> ${$_(intention)}
                    </span>`;
        })
        .join(" ");
    }

    let ret = "";
    if (formfield.choices) {
      ret += value.map((v) => formfield.choices[v]).join(", ");
    } else ret += value.join(", ");
    return ret;
  }
</script>

<div class="array_field">
  {@html parseValues(value)}
</div>
