// frontend/src/components/Fields/Display/JSONActorsField.vue
<template>
  <div class="jsonactors_field whitespace-nowrap">
    <div v-for="val in vals">
      <span>{{ val.name }}</span>
      <span v-if="val.role" class="font-weight-light">
        ({{ mapChoices(val.role) }})
      </span>
    </div>
  </div>
</template>

<script lang="ts">
  import JSONFieldMixin from "../JSONFieldMixin";
  import Vue from "vue";

  export default Vue.extend({
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ name: null, role: null }],
      };
    },
  });
</script>

// newfront/src/components/Fields/Display/JSONActorsField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields";
  import { mapChoices } from "$components/Fields/Display/jsonHelpers";

  export let formfield: FormField;
  export let value: boolean;
  export let model: string;
  let vals = value ? value : [{ name: null, role: null }];
</script>

<div class="jsonactors_field whitespace-nowrap">
  {#each vals as val}
    <div>
      <span>{val.name}</span>
      {#if val.role}
        <span class="font-weight-light">
          ({mapChoices(val.role, formfield.choices)})
        </span>
      {/if}
    </div>
  {/each}
</div>
