// frontend/src/components/Fields/Display/JSONJobsField.vue
<template>
  <div class="jsonjobs_field whitespace-nowrap">
    <div v-for="val in vals" :class="{ 'font-weight-bold': val.current }">
      <span>{{ date_and_current(val) }}</span>
      <span v-if="val.jobs" class="mx-2">
        {{ val.jobs.toLocaleString("fr") }} jobs
      </span>
      <span v-if="val.employees" class="mx-2">
        {{ val.employees.toLocaleString("fr") }} employees
      </span>
      <span v-if="val.workers" class="mx-2">
        {{ val.workers.toLocaleString("fr") }} workers
      </span>
    </div>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";

  export default {
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ date: null, value: null }],
      };
    },
  };
</script>

// newfront/src/components/Fields/Display/JSONJobsField.svelte
<script lang="ts">
  import {
    date_and_current,
    JSONJobsFieldType,
  } from "$components/Fields/Display/jsonHelpers.ts";

  export let value: JSONJobsFieldType[] = [];
</script>

<div class="jsonjobs_field whitespace-nowrap">
  {#each value as val}
    <div class:font-bold={val.current}>
      {date_and_current(val)}
      {#if val.jobs}
        <span class="mx-2">
          {val.jobs.toLocaleString("fr")} jobs
        </span>
      {/if}{#if val.employees}
        <span class="mx-2">
          {val.employees.toLocaleString("fr")} employees
        </span>
      {/if}{#if val.workers}
        <span class="mx-2">
          {val.workers.toLocaleString("fr")} workers
        </span>
      {/if}
    </div>
  {/each}
</div>
