// newfront/src/components/Fields/Display/JSONExportsField.vue
<template>
  <div class="jsonexports_field whitespace-nowrap">
    <div v-for="val in vals" :class="{ 'font-weight-bold': val.current }">
      <span>{{ date_and_current(val) }}</span>
      <span v-if="val.choices">{{ mapChoices(val.choices) }}</span>
      <span v-if="val.area" class="mx-2">
        <i class="fas fa-circle-notch"></i> {{ val.area.toLocaleString("fr") }} ha
      </span>
      <span v-if="val.yield" class="mx-2">
        <i class="fas fa-weight-hanging"></i> {{ val.yield.toLocaleString("fr") }} tons
      </span>
      <span v-if="val.export" class="mx-2">
        <i class="fas fa-plane-departure"></i> {{ val.export.toLocaleString("fr") }} %
      </span>
    </div>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";

  export default {
    mixins: [JSONFieldMixin],
    data() {
      return {
        vals: this.value ? this.value : [{ date: null, value: null }],
      };
    },
  };
</script>

// newfront/src/components/Fields/Display/JSONExportsField.svelte
<script lang="ts">
  import {
    date_and_current,
    mapChoices,
  } from "$components/Fields/Display/jsonHelpers.ts";
  import CircleNotchIcon from "../../icons/CircleNotchIcon.svelte";
  import WeightIcon from "../../icons/WeightIcon.svelte";
  import type { FormField } from "$components/Fields/fields";
  import PlaneIcon from "../../icons/PlaneIcon.svelte";

  export let value: boolean;
  export let formfield: FormField;
  let vals = value ? value : [{ name: null, role: null }];
</script>

<div class="jsonexports_field whitespace-nowrap">
  {#each vals as val}
    <div class={() => (val.current ? "font-bold" : "")}>
      <span>{date_and_current(val)}</span>
      {#if val.choices}
        {mapChoices(val.choices, formfield.choices)}
      {/if}{#if val.area}
        <span> <CircleNotchIcon /> {val.area.toLocaleString("fr")} ha</span>
      {/if}{#if val.yield}
        <span class="mx-2">
          <WeightIcon />
          {val.yield.toLocaleString("fr")} tons
        </span>
      {/if}{#if val.export}
        <span class="mx-2">
          <PlaneIcon />
          {val.export.toLocaleString("fr")} %
        </span>
      {/if}
    </div>
  {/each}
</div>
