// frontend/src/components/Fields/PointField.vue
<template>
  <div>
    <div v-if="readonly">
      <span v-if="val.lat">Lat: {{ parseFloat(val.lat.toFixed(8)) }}</span>
      <span v-if="val.lng">Lng: {{ parseFloat(val.lng.toFixed(8)) }}</span>
    </div>
  </div>
</template>

<script>
  export default {
    props: ["formfield", "value", "readonly"],
    data() {
      return {
        val: this.value,
      };
    },
    methods: {
      emitVal() {
        this.$emit("input", this.val);
      },
    },
  };
</script>

<style scoped>
  span {
    display: block;
  }
</style>

// newfront/src/components/Fields/Display/PointField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields"

  export let value: { lat: number; lng: number }
  export let formfield: FormField
</script>

<div class="point_field" data-name={formfield?.name ?? ""}>
  {#if value.lat}
    <div>Lat: {parseFloat(value.lat.toFixed(8))}</div>
  {/if}
  {#if value.lng}
    <div>Lng: {parseFloat(value.lng.toFixed(8))}</div>{/if}
</div>
