// frontend/src/components/Fields/Display/PointField.vue
<template>
  <div class="point_field">
    <div v-if="value.lat">Lat: {{ parseFloat(value.lat.toFixed(8)) }}</div>
    <div v-if="value.lng">Lng: {{ parseFloat(value.lng.toFixed(8)) }}</div>
  </div>
</template>

<script lang="ts">
  import type { PropType } from "vue";
  import type { FormField } from "$components/Fields/fields";
  import Vue from "vue";

  export default Vue.extend({
    props: {
      formfield: { type: Object as PropType<FormField>, required: true },
      value: { type: [Array, Object], required: true },
      model: { type: String, required: true },
    },
  });
</script>

// newfront/src/components/Fields/Display/PointField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields";

  export let formfield: FormField;
  export let value: object[];
  export let model: string;
</script>

<div class="point_field">
  {#if value.lat}
    <div>Lat: {parseFloat(value.lat.toFixed(8))}</div>
  {/if}
  {#if value.lng}
    <div>Lng: {parseFloat(value.lng.toFixed(8))}</div>{/if}
</div>
