// frontend/src/views/Data/Charts/ChartsContainer.vue
<template>
  <div class="datacontainer">
    <ViewSwitcher />
    <FilterBar />
    <ContextBarContainer>
      <slot name="ContextBar"></slot>
    </ContextBarContainer>
    <div class="main-content">
      <!--      <LoadingPulse v-if="$apollo.loading" />-->
      <div class="h-100">
        <div
          class="sideBuffer float-left"
          :class="{ collapsed: !$store.state.map.showFilterBar }"
        ></div>
        <div
          class="sideBuffer float-right"
          :class="{ collapsed: !$store.state.map.showContextBar }"
        ></div>
        <div class="chart-container">
          <slot></slot>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import LoadingPulse from "components/Data/LoadingPulse";
  import ViewSwitcher from "components/Data/ViewSwitcher";
  import FilterBar from "components/Data/FilterBar";
  import ContextBarContainer from "components/Data/ContextBarContainer";

  export default {
    name: "ChartsContainer",
    components: {
      ContextBarContainer,
      FilterBar,
      ViewSwitcher,
      LoadingPulse,
    },
    computed: {},
  };
</script>
<style lang="scss">
  .chart-container {
    text-align: center;
    height: 100%;
    display: flex;
    justify-content: center;
    overflow-y: scroll;
  }
</style>

// newfront/src/components/Data/Charts/ChartsContainer.svelte
<script lang="ts">
  import ContextBarContainer from "../ContextBarContainer.svelte";
  import FilterBar from "../FilterBar.svelte";
  import { showContextBar, showFilterBar } from "../index";
  import ViewSwitcher from "../ViewSwitcher.svelte";
</script>

<div class="relative p-0 w-full h-full">
  <ViewSwitcher />
  <FilterBar />
  <ContextBarContainer>
    <slot name="ContextBar" />
  </ContextBarContainer>
  <div class="w-full h-full">
    <div
      class="{$showFilterBar ? 'w-[clamp(220px,20%,300px)]' : 'w-0'} h-full float-left"
    />
    <div
      class="{$showContextBar
        ? 'w-[clamp(220px,20%,300px)]'
        : 'w-0'} h-full float-right"
    />
    <div class="text-center h-full flex justify-center overflow-y-auto overflow-x-auto">
      <slot />
    </div>
  </div>
</div>
