// frontend/src/views/Register.vue
<template>
  <div>
    <PageTitle>{{ $t("Register") }}</PageTitle>

    <div
      v-if="registration_successful"
      class="flex justify-center items-center h-full w-full mb-4"
    >
      Registration successful. You can now close this window and check your emails.
    </div>
    <div v-else class="flex justify-center items-center h-full w-full mb-4">
      <div v-if="$store.getters.userAuthenticated">
        {{ $t("You are already logged in.") }}
      </div>
      <div
        v-else
        class="w-[clamp(300px,80%,900px)] p-6 rounded border-2 border-[#4b4b4b]"
      >
        {{
          $t(
            "Your contact information will help our researchers get in touch with you for additional information. We respect and protect your privacy and anonymity, and will never share or publish your personal information. You can also write us directly at data@landmatrix.org."
          )
        }}

        <form class="grid md:grid-cols-2 gap-4 my-6" @submit.prevent="register">
          <label>
            {{ $t("Username") }}
            <input
              v-model="username"
              autocomplete="username"
              class="form-control"
              placeholder="Username"
              type="text"
              required
            />
          </label>
          <label>
            {{ $t("Email") }}
            <input
              v-model="email"
              class="form-control"
              autocomplete="email"
              :placeholder="$t('Email')"
              type="email"
              required
            />
          </label>
          <label>
            {{ $t("First name") }}
            <input
              v-model="first_name"
              class="form-control"
              :placeholder="$t('First name')"
              type="text"
              required
            />
          </label>
          <label>
            {{ $t("Last name") }}
            <input
              v-model="last_name"
              class="form-control"
              :placeholder="$t('Last name')"
              type="text"
              required
            />
          </label>

          <label>
            {{ $t("Phone") }}
            <input
              v-model="phone"
              class="form-control"
              :placeholder="$t('Phone')"
              type="text"
            />
          </label>
          <label>
            {{ $t("User information") }}
            <textarea
              v-model="information"
              class="form-control"
              :placeholder="
                $t(
                  'Write something about yourself and your company. This won\'t be published.'
                )
              "
              type="text"
            />
          </label>

          <label>
            {{ $t("Password") }}
            <input
              v-model="password"
              class="form-control"
              autocomplete="new-password"
              :placeholder="$t('Password')"
              type="password"
            />
          </label>
          <label>
            {{ $t("Password confirmation") }}
            <input
              v-model="password_confirm"
              class="form-control"
              autocomplete="new-password"
              :placeholder="$t('Password confirmation')"
              type="password"
            />
          </label>
          <vue-hcaptcha
            ref="hcaptcha"
            :re-captcha-compat="false"
            :sitekey="VITE_HCAPTCHA_SITEKEY"
            @verify="captchaVerified"
          />

          <button class="btn btn-primary" type="submit" :disabled="submit_disabled">
            {{ $t("Register") }}
          </button>
          <p class="mt-3 text-danger small">{{ register_failed_message }}</p>
        </form>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import Vue from "vue";
  import PageTitle from "$components/PageTitle.vue";
  import { apolloClient } from "$utils/apolloclient";
  import gql from "graphql-tag";
  import VueHcaptcha from "@hcaptcha/vue-hcaptcha";

  export default Vue.extend({
    name: "Register",
    components: { PageTitle, VueHcaptcha },
    data() {
      return {
        username: null,
        first_name: null,
        last_name: null,
        email: null,
        phone: null,
        information: null,
        password: null,
        password_confirm: null,
        token: null,
        submit_disabled: true,
        register_failed_message: "",
        registration_successful: false,
        VITE_HCAPTCHA_SITEKEY:
          import.meta.env.VITE_HCAPTCHA_SITEKEY ||
          "10000000-ffff-ffff-ffff-000000000001",
      };
    },
    created() {
      if (this.$store.getters.userAuthenticated) {
        if (this.$route.query.next)
          this.$router.push(this.$route.query.next.toString());
      }
    },
    methods: {
      captchaVerified(token) {
        this.token = token;
        this.submit_disabled = false;
      },

      async register() {
        // let xx = await fetch("/api/accounts/register/", {
        //   method: "POST",
        //   body: JSON.stringify({
        //     username: this.username,
        //     first_name: this.first_name,
        //     last_name: this.last_name,
        //     email: this.email,
        //     phone: this.phone,
        //     information: this.information,
        //     password: this.password,
        //     password_confirm: this.password_confirm,
        //     token: this.token,
        //   }),
        //   headers: {
        //     "Content-Type": "application/json",
        //   },
        // });
        // console.log(await xx.json());
        apolloClient
          .mutate({
            mutation: gql`
              mutation Register(
                $username: String!
                $first_name: String!
                $last_name: String!
                $email: String!
                $phone: String
                $information: String!
                $password: String!
                $token: String!
              ) {
                register(
                  username: $username
                  first_name: $first_name
                  last_name: $last_name
                  email: $email
                  phone: $phone
                  information: $information
                  password: $password
                  token: $token
                ) {
                  ok
                  message
                }
              }
            `,
            variables: {
              username: this.username,
              first_name: this.first_name,
              last_name: this.last_name,
              email: this.email,
              phone: this.phone,
              information: this.information,
              password: this.password,
              token: this.token,
            },
          })
          .then(({ data }) => {
            if (data.register.ok) {
              this.registration_successful = true;
            } else {
              this.register_failed_message = data.register.message;
            }
          });
      },
    },
  });
</script>

<style scoped>
  label {
    display: block;
    margin-bottom: 1rem;
  }

  input {
    display: block;
  }
</style>

// frontend/src/routes/(main)/account/register/+page.svelte
<script lang="ts">
  import { toast } from "@zerodevx/svelte-toast"
  import { _ } from "svelte-i18n"

  import { getCsrfToken, slugify } from "$lib/utils"

  import HCaptcha from "$components/HCaptcha.svelte"
  import PageTitle from "$components/PageTitle.svelte"

  let user = {
    username: "",
    first_name: "",
    last_name: "",
    email: "",
    phone: "",
    information: "",
    password: "",
    password_confirm: "",
  }
  let token = ""
  let disabled = true
  let register_failed_message = ""
  let registration_successful = false

  function captchaVerified(e: CustomEvent<{ token: string }>) {
    token = e.detail.token
    disabled = false
  }

  function usernameChange() {
    user = { ...user, username: slugify(user.username) }
  }

  async function register() {
    const ret = await fetch("/api/user/register/", {
      method: "POST",
      credentials: "include",
      body: JSON.stringify({ ...user, token }),
      headers: {
        "X-CSRFToken": await getCsrfToken(),
        "Content-Type": "application/json",
      },
    })
    const retJson = await ret.json()
    console.log(retJson)
    if (!ret.ok) {
      return toast.push(`Unknown Problem: ${retJson}`, { classes: ["error"] })
    }
    if (!retJson.ok) {
      register_failed_message = retJson.error
      return
    }
    registration_successful = true
  }
</script>

<PageTitle>{$_("Register")}</PageTitle>

{#if registration_successful}
  <div
    class="mb-4 flex h-full w-full items-center justify-center text-gray-700 dark:text-white"
  >
    {$_(
      "Registration successful. You can now close this window and check your emails.",
    )}
  </div>
{:else}
  <div
    class="mb-4 flex h-full w-full items-center justify-center text-gray-700 dark:text-white"
  >
    {$_(
      "Your contact information will help our researchers get in touch with you for additional information. We respect and protect your privacy and anonymity, and will never share or publish your personal information. You can also write us directly at data@landmatrix.org.",
    )}
  </div>

  <form
    class="my-6 grid gap-4 text-gray-700 md:grid-cols-2 dark:text-white"
    on:submit|preventDefault={register}
  >
    <label>
      {$_("Username")}
      <input
        bind:value={user.username}
        autocomplete="username"
        class="inpt"
        placeholder={$_("Username")}
        type="text"
        required
        pattern="[@_+.a-zA-Z0-9 \-]+"
        on:input={usernameChange}
      />
      <span class="text-xs">{$_("Letters, digits and @/./+/-/_ only.")}</span>
    </label>
    <label>
      {$_("Email")}
      <input
        bind:value={user.email}
        class="inpt"
        autocomplete="email"
        placeholder={$_("Email")}
        type="email"
        required
      />
    </label>
    <label>
      {$_("First name")}
      <input
        bind:value={user.first_name}
        class="inpt"
        placeholder={$_("First name")}
        type="text"
        required
      />
    </label>
    <label>
      {$_("Last name")}
      <input
        bind:value={user.last_name}
        class="inpt"
        placeholder={$_("Last name")}
        type="text"
        required
      />
    </label>

    <label>
      {$_("Phone")}
      <input
        bind:value={user.phone}
        class="inpt"
        placeholder={$_("Phone")}
        type="text"
      />
    </label>
    <label>
      {$_("User information")}
      <textarea
        bind:value={user.information}
        class="inpt"
        placeholder={$_(
          "Write something about yourself and your company. This won't be published.",
        )}
        type="text"
      />
    </label>

    <label>
      {$_("Password")}
      <input
        bind:value={user.password}
        class="inpt"
        autocomplete="new-password"
        placeholder={$_("Password")}
        type="password"
      />
    </label>
    <label>
      {$_("Password confirmation")}
      <input
        bind:value={user.password_confirm}
        class="inpt"
        autocomplete="new-password"
        placeholder={$_("Password confirmation")}
        type="password"
      />
    </label>
    <HCaptcha class="flex w-full justify-center" on:success={captchaVerified} />
    <div class="flex items-center justify-center">
      <button class="btn btn-primary w-full" type="submit" {disabled}>
        {$_("Register")}
      </button>
    </div>
    <p class="text-danger small mt-3">{register_failed_message}</p>
  </form>
{/if}
