// frontend/src/components/Fields/Edit/BooleanField.vue
<template>
  <div>
    <div v-if="formfield.class === 'NullBooleanField'">
      <select v-model="val" :name="formfield.name" class="form-control">
        <option v-if="!formfield.required" :value="null">--------</option>
        <option :value="true">{{ $t("Yes") }}</option>
        <option :value="false">{{ $t("No") }}</option>
      </select>
    </div>
    <input v-else v-model="val" type="checkbox" :name="formfield.name" />
  </div>
</template>

<script>
  export default {
    props: {
      formfield: { type: Object, required: true },
      value: { type: Boolean, required: false },
      model: { type: String, required: true },
    },
    computed: {
      val: {
        get() {
          return this.value;
        },
        set(v) {
          this.$emit("input", v);
        },
      },
    },
  };
</script>

// newfront/src/components/Fields/Edit/BooleanField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import type { FormField } from "../fields";

  export let formfield: FormField;
  export let value: number;
</script>

<div class="boolean_field">
  {#if formfield.class === "NullBooleanField"}
    <select bind:value class="inpt">
      {#if !formfield.required}<option value={null}>--------</option>{/if}
      <option value={true}>{$_("Yes")}</option>
      <option value={false}>{$_("No")}</option>
    </select>
  {:else}
    <input bind:checked={value} type="checkbox" class="inpt" />
  {/if}
</div>
