// frontend/src/components/Fields/Edit/DateField.vue
<template>
  <div class="date_field">
    <LowLevelDateYearField v-model="val" />
  </div>
</template>

<script>
  import LowLevelDateYearField from "$components/Fields/Edit/LowLevelDateYearField";

  export default {
    name: "DateField",
    components: { LowLevelDateYearField },
    props: {
      formfield: { type: Object, required: true },
      value: { type: [Date, String], required: false, default: null },
      model: { type: String, required: true },
    },
    computed: {
      val: {
        get() {
          return this.value;
        },
        set(v) {
          this.$emit("input", v);
        },
      },
    },
  };
</script>

// newfront/src/components/Fields/Edit/DateField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import type { FormField } from "../fields";
  import LowLevelDateYearField from "./LowLevelDateYearField.svelte";

  export let formfield: FormField;
  export let value;
</script>

<div class="date_field">
  <LowLevelDateYearField bind:value name={formfield.name} />
</div>
