// frontend/src/components/Fields/Edit/LowLevelDateYearField.vue
<template>
  <div class="nowrap input-group">
    <input
      ref="inputfield"
      v-model="val"
      type="text"
      class="form-control"
      :class="valid_state"
      placeholder="YYYY-MM-DD"
      :required="required"
    />
  </div>
</template>

<script>
  import dayjs from "dayjs";
  import customParseFormat from "dayjs/plugin/customParseFormat";

  dayjs.extend(customParseFormat);

  export default {
    name: "LowLevelDateYearField",
    props: {
      label: { type: String, required: false, default: "" },
      unit: { type: String, required: false, default: "" },
      required: { type: Boolean, default: false },
      value: { type: [String, Date], required: false, default: null },
    },
    data() {
      return {
        val: this.value,
        valid_state: null,
      };
    },
    watch: {
      value(newValue) {
        this.val = newValue;
      },
      val(v) {
        if (!v) {
          this.$emit("input", null);
          this.valid_state = "";
          this.$refs.inputfield.setCustomValidity("");
          return;
        }
        v = v.replace("/", "-");

        let field_valid = dayjs(
          this.val,
          ["YYYY", "YYYY-M", "YYYY-M-D", "YYYY-MM", "YYYY-MM-D", "YYYY-MM-DD"],
          true
        ).isValid();

        if (field_valid) {
          this.valid_state = "is-valid";
          this.$refs.inputfield.setCustomValidity("");
        } else {
          this.valid_state = "is-invalid";
          this.$refs.inputfield.setCustomValidity(
            "Invalid format. Use YYYY, YYYY-MM or YYYY-MM-DD"
          );
        }

        this.$emit("input", v);
      },
    },
  };
</script>

// newfront/src/components/Fields/Edit/LowLevelDateYearField.svelte
<script lang="ts">
  import dayjs from "dayjs";
  import customParseFormat from "dayjs/plugin/customParseFormat";

  dayjs.extend(customParseFormat);

  export let required = false;
  export let value: string | Date;
  export let name: string;

  let valid_state = "";
  let inputfield;

  const onChange = async () => {
    if (!value) {
      // this.$emit("input", null);
      valid_state = "";
      inputfield.setCustomValidity("");
      return;
    }
    value = value.replace("/", "-").replace(".", "-").replace(",", "-");

    const field_valid = dayjs(
      value,
      ["YYYY", "YYYY-M", "YYYY-M-D", "YYYY-MM", "YYYY-MM-D", "YYYY-MM-DD"],
      true
    ).isValid();
    if (field_valid) {
      valid_state = "is-valid";
      inputfield.setCustomValidity("");
    } else {
      valid_state = "border-2 border-red-600 text-red-700";
      inputfield.setCustomValidity("Invalid format. Use YYYY, YYYY-MM or YYYY-MM-DD");
    }
  };
</script>

<div class="whitespace-nowrap">
  <input
    bind:this={inputfield}
    bind:value
    type="text"
    class="inpt {valid_state}"
    placeholder="YYYY-MM-DD"
    {required}
    {name}
    on:input={onChange}
  />
</div>
