// frontend/src/components/Fields/TextField.vue
<template>
  <div>
    <div v-if="readonly">
      {{ val }}
    </div>
    <div v-else class="input-group">
      <input
        v-if="!formfield.multiline"
        :id="`type-${formfield.name}`"
        :type="formfield.type || `text`"
        class="form-control"
        :placeholder="formfield.placeholder || formfield.label"
        :aria-label="formfield.placeholder || formfield.label"
        v-model="val"
        @input="emitVal"
      />
      <textarea
        v-else
        rows="5"
        :id="`type-${formfield.name}`"
        class="form-control"
        :placeholder="formfield.placeholder || formfield.label"
        :aria-label="formfield.placeholder || formfield.label"
        v-model="val"
        @input="emitVal"
      />
      <div v-if="formfield.unit" class="input-group-append">
        <span class="input-group-text">{{ formfield.unit }}</span>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    props: ["formfield", "value", "readonly"],
    data() {
      return {
        val: this.value,
      };
    },
    methods: {
      emitVal() {
        this.$emit("input", this.val);
      },
    },
  };
</script>

// newfront/src/components/Fields/Edit/TextField.svelte
<script lang="ts">
  import type { FormField } from "../fields";

  export let formfield: FormField;
  export let value: string;
</script>

<div class="text_field">
  {#if formfield.class === "TextField"}
    <textarea
      bind:value
      placeholder={formfield.label}
      name={formfield.name}
      rows="5"
      class="inpt"
    />
  {:else if formfield.class === "URLField"}
    <input
      bind:value
      type="url"
      placeholder={formfield.label}
      name={formfield.name}
      maxlength={formfield.max_length}
    />
  {:else}
    <input
      bind:value
      type="text"
      placeholder={formfield.label}
      name={formfield.name}
      maxlength={formfield.max_length}
    />
  {/if}
</div>
