// frontend/src/components/Investor/InvestorHistory.vue
<template>
  <div>
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Created</th>
          <th v-if="$store.getters.userAuthenticated">User</th>
          <th>Fully updated</th>
          <th>Status</th>
          <th>Comment</th>
          <th style="text-align: right;">
            <!--            Show / <a @click="compareVersions">Compare</a>-->
            Show
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(version, i) in investor.versions" :key="i">
          <td>{{ version.revision.date_created | dayjs("YYYY-MM-DD HH:mm") }}</td>
          <td v-if="$store.getters.userAuthenticated">
            {{ version.revision.user && version.revision.user.full_name }}
          </td>
          <td>
            <b-button
              v-b-tooltip.hover
              disabled
              :title="version.investor.fully_updated ? 'Fully updated' : 'Updated'"
              :class="[
                'fa',
                version.investor.fully_updated ? 'fa-check-circle' : 'fa-circle',
              ]"
            />
          </td>
          <td>
            {{ version.investor.status }}
          </td>
          <td>{{ version.revision.comment }}</td>
          <td style="white-space: nowrap; text-align: right;">
            <span v-if="i === deduced_position">Current</span>
            <span v-else>
              <router-link
                v-slot="{ href }"
                :to="{
                  name: 'investor_detail',
                  params: { investorId, investorVersion: version.revision.id },
                }"
              >
                <!-- this hack helps to understand that a new version is actually loading, atm -->
                <a :href="href">Show</a>
              </router-link>
            </span>
            <!--            <span class="ml-4" style="white-space: nowrap; text-align: right;">-->
            <!--              <input-->
            <!--                type="radio"-->
            <!--                v-model="compare_from"-->
            <!--                :value="version.revision.id"-->
            <!--                :disabled="version.revision.id >= compare_to"-->
            <!--              />-->

            <!--              <input-->
            <!--                type="radio"-->
            <!--                v-model="compare_to"-->
            <!--                :value="version.revision.id"-->
            <!--                :disabled="version.revision.id <= compare_from"-->
            <!--              />-->
            <!--            </span>-->
          </td>
        </tr>
      </tbody>
      <!--      <tfoot>-->
      <!--        <tr>-->
      <!--          <td></td>-->
      <!--          <td></td>-->
      <!--          <td></td>-->
      <!--          <td></td>-->
      <!--          <td></td>-->
      <!--          <td>-->
      <!--            <button style="white-space: nowrap;" @click="compareVersions">-->
      <!--              Compare versions-->
      <!--            </button>-->
      <!--          </td>-->
      <!--        </tr>-->
      <!--      </tfoot>-->
    </table>
  </div>
</template>

<script>
  export default {
    name: "InvestorHistory",
    props: ["investor", "investorId", "investorVersion"],
    data() {
      return {
        compare_from: null,
        compare_to: null,
      };
    },
    computed: {
      deduced_position() {
        if (this.investor.versions.length === 0) return 0;
        if (this.investorVersion) {
          return this.investor.versions.findIndex(
            (v) => +v.revision.id === +this.investorVersion
          );
        }
        for (const [i, v] of this.investor.versions.entries()) {
          if (v.investor.draft_status === null) return i;
        }
        return this.investor.versions.length - 1;
      },
    },
    mounted() {
      if (this.investor.versions.length >= 2) {
        this.compare_to = this.investor.versions[0].revision.id;
        this.compare_from = this.investor.versions[1].revision.id;
      }
    },
    methods: {
      derive_status(status, draft_status) {
        const status_map = {
          1: "Draft",
          2: "Live",
          3: "Updated",
          4: "Deleted",
        };
        const draft_status_map = {
          1: "Draft",
          2: "Review",
          3: "Activation",
          4: "Rejected",
          5: "To Delete",
        };

        if (draft_status) {
          return draft_status_map[draft_status];
        }

        let st = status_map[status];
        if (draft_status) {
          return `${st} + ${draft_status_map[draft_status]}`;
        }
        return st;
      },
      compareVersions() {
        this.$router.push({
          name: "investor_compare",
          params: {
            investorId: this.investorId,
            fromVersion: this.compare_from,
            toVersion: this.compare_to,
          },
        });
      },
    },
  };
</script>

// newfront/src/components/Investor/InvestorHistory.svelte
<script lang="ts">
  import dayjs from "dayjs"
  import { onMount } from "svelte"
  import { _ } from "svelte-i18n"

  import { page } from "$app/stores"

  import type { Investor, InvestorVersion } from "$lib/types/investor"

  export let investor: Investor
  export let investorID: number
  export let investorVersion: number

  let compareFrom
  let compareTo

  onMount(() => {
    if (investor.versions?.length >= 2) {
      compareTo = investor.versions[0].id
      compareFrom = investor.versions[1].id
    }
  })

  function calcVersionList(versions: InvestorVersion[]) {
    versions = JSON.parse(JSON.stringify(versions))
    if (!$page.data.user.is_authenticated) {
      versions = versions.filter(
        v => !(v.investor.confidential || v.investor.draft_status),
      )
    }
    let currentActive = false
    return versions.map(v => {
      if (!v.investor.draft_status && !currentActive) {
        v.link = `/investor/${investorID}`
        currentActive = true
      } else v.link = `/investor/${investorID}/${v.id}`
      return v
    })
  }
  $: enriched_versions = calcVersionList(investor.versions ?? [])

  function calcDeducedPosition(versions) {
    if (versions.length === 0) return 0
    if (investorVersion) {
      return versions.findIndex(v => +v.id === +investorVersion)
    }
    for (const [i, v] of versions.entries()) {
      if (v.investor.draft_status === null) return i
    }
    return versions.length - 1
  }

  $: deduced_position = calcDeducedPosition(investor?.versions)

  const status_map = {
    1: "Draft",
    2: "Active", //"Live",
    3: "Active", // "Updated",
    4: "Deleted",
    5: "Rejected", // legacy
    6: "To Delete", // legacy
  }
  const draft_status_map = {
    1: "Draft",
    2: "Review",
    3: "Activation",
    4: "Rejected", // legacy
    5: "Deleted",
  }
  function derive_status(status, draft_status) {
    return draft_status ? draft_status_map[draft_status] : status_map[status]
  }
</script>

<section>
  <h3>{$_("Version history")}</h3>
  <table class="relative w-full table-auto border-b-2">
    <thead>
      <tr>
        <th>{$_("Created")}</th>
        {#if $page.data.user.is_authenticated} <th>{$_("User")}</th> {/if}
        {#if $page.data.user.is_authenticated} <th>{$_("Status")}</th> {/if}
        <th class="text-right">
          {$_("Show")} /
          <a
            href={`/investor/${investorID}/compare/${compareFrom}/${compareTo}/`}
            class="text-nowrap"
          >
            {$_("Compare")}
          </a>
        </th>
      </tr>
    </thead>
    <tbody>
      {#each enriched_versions as version, i}
        <tr class="odd:bg-gray-100">
          <td>{dayjs(version.created_at).format("YYYY-MM-DD HH:mm")}</td>
          {#if $page.data.user.is_authenticated}
            <td>
              {version.created_by && version.created_by.full_name}
            </td>
          {/if}

          {#if $page.data.user.is_authenticated}
            <td>
              {$_(
                derive_status(
                  version?.investor?.status,
                  version?.investor?.draft_status,
                ),
              )}
            </td>
          {/if}
          <td class="whitespace-nowrap text-right">
            {#if i === deduced_position}
              {$_("Current")}
            {:else}
              <a href={version?.link}>{$_("Show")}</a>
            {/if}
            <span class="ml-4 whitespace-nowrap text-right">
              <input
                bind:group={compareFrom}
                type="radio"
                value={version?.id}
                disabled={version?.id >= compareTo}
              />

              <input
                bind:group={compareTo}
                type="radio"
                value={version?.id}
                disabled={version?.id <= compareFrom}
              />
            </span>
          </td>
        </tr>
      {/each}
    </tbody>
    <tfoot>
      <tr>
        <td />
        {#if $page.data.user.is_authenticated} <td /> {/if}
        <td />
        {#if $page.data.user.is_authenticated} <td /> {/if}
        {#if compareFrom && compareTo}
          <td>
            <a
              href={`/investor/${investorID}/compare/${compareFrom}/${compareTo}/`}
              class="btn btn-primary text-nowrap"
            >
              {$_("Compare versions")}
            </a>
          </td>
        {/if}
      </tr>
    </tfoot>
  </table>
</section>
