// frontend/src/components/BigMap.vue
<template>
  <div class="map-container" :style="mapContainerStyle">
    <l-map
      id="bigMap"
      ref="bigMap"
      :options="mapOptions"
      :center="center"
      :bounds="bounds"
      @ready="(map) => $emit('ready', map)"
    >
      <l-tile-layer
        v-for="tileProvider in tileLayers"
        :key="tileProvider.name"
        :name="tileProvider.name"
        :visible="tileProvider.name === visibleLayer"
        :url="tileProvider.url"
        :attribution="tileProvider.attribution"
        :max-zoom="tileProvider.maxZoom || 19"
        layer-type="base"
      />

      <slot />
    </l-map>
    <BigMapStandaloneLayerSwitcher v-if="!hideLayerSwitcher" />
  </div>
</template>

<script>
  import iconRetinaUrl from "$static/images/marker-icon-2x.png";
  import iconUrl from "$static/images/marker-icon.png";
  import shadowUrl from "$static/images/marker-shadow.png";

  import { Icon, Map } from "leaflet";
  import { GestureHandling } from "leaflet-gesture-handling";
  import "leaflet-gesture-handling/dist/leaflet-gesture-handling.css";
  import "leaflet/dist/leaflet.css";
  import { LMap, LTileLayer } from "vue2-leaflet";
  import { mapState } from "vuex";
  import BigMapStandaloneLayerSwitcher from "./Map/BigMapStandaloneLayerSwitcher";

  Map.addInitHook("addHandler", "gestureHandling", GestureHandling);

  delete Icon.Default.prototype._getIconUrl;
  let shadowSize = [0, 0];
  Icon.Default.mergeOptions({ iconRetinaUrl, iconUrl, shadowUrl, shadowSize });

  export default {
    name: "BigMap",
    components: {
      BigMapStandaloneLayerSwitcher,
      LMap,
      LTileLayer,
    },
    props: {
      center: { type: Array, default: null },
      options: { type: Object, default: null },
      bounds: { type: Object, default: null },
      containerStyle: { type: Object, default: null },
      hideLayerSwitcher: { type: Boolean, default: false },
    },
    computed: {
      ...mapState({
        tileLayers: (state) => state.map.layers,
        visibleLayer: (state) => state.map.visibleLayer,
      }),
      mapOptions() {
        return {
          zoomSnap: 0.5,
          minZoom: 1,
          zoom: 3,
          zoomControl: true,
          gestureHandling: true,
          ...this.options,
        };
      },
      mapContainerStyle() {
        return {
          "margin-left": "auto",
          "margin-right": "auto",
          position: "relative",
          // height: "75vh",
          ...this.containerStyle,
        };
      },
    },
  };
</script>

<style lang="scss" scoped>
  .map-container {
    position: relative;

    #bigMap {
      height: 100%;
      z-index: 1;
    }
  }

  //.leaflet-container {
  //  background-color: rgba(255, 0, 0, 0);
  //}
</style>

// frontend/src/components/Map/BigMap.svelte
<script lang="ts">
  import type { MapOptions } from "leaflet"
  import "leaflet-gesture-handling/dist/leaflet-gesture-handling.css"
  import { GestureHandling } from "leaflet-gesture-handling?client"
  import "leaflet/dist/leaflet.css"
  import { Icon, Map } from "leaflet?client"
  import { nanoid } from "nanoid"
  import { createEventDispatcher, onMount, onDestroy } from "svelte"
  import { _ } from "svelte-i18n"

  import LoadingPulse from "$components/LoadingPulse.svelte"
  import {
    getBaseLayers,
    getContextLayers,
    visibleContextLayers,
    visibleLayer,
  } from "$components/Map/layers"

  import BigMapStandaloneLayerSwitcher from "./BigMapStandaloneLayerSwitcher.svelte"

  export let options: MapOptions = {}
  export let containerClass = ""
  export let showLayerSwitcher = true

  const dispatch = createEventDispatcher<{ ready: Map }>()

  let mapId = "bigMap-" + nanoid()
  let map: Map

  if (!import.meta.env.SSR) {
    // noinspection TypeScriptUnresolvedVariable
    delete Icon.Default.prototype._getIconUrl
    Icon.Default.mergeOptions({
      iconRetinaUrl: "/images/marker-icon-2x.png",
      iconUrl: "/images/marker-icon.png",
      shadowUrl: "/images/marker-shadow.png",
      shadowSize: [0, 0],
    })
  }

  $: contextLayers = getContextLayers($_)
  $: baseLayers = getBaseLayers($_)

  onMount(async () => {
    // onDestroy sometimes triggers after onMount on loading a new map
    // clean up by removing layers from old map
    baseLayers.forEach(l => l.layer.remove())
    contextLayers.forEach(l => l.layer.remove())

    Map.addInitHook("addHandler", "gestureHandling", GestureHandling)

    // create new Map in div with mapId
    map = new Map(mapId, {
      zoomSnap: 0.5,
      minZoom: 1,
      zoom: 3,
      zoomControl: true,
      gestureHandling: true,
      ...options,
    })

    map.whenReady(() => dispatch("ready", map))
  })

  // See bug ticket #668: Sometimes not called when switching views quickly.
  onDestroy(() => {
    if (map) {
      map.remove()
      map = undefined
    }
  })

  $: if (map && $visibleLayer) {
    baseLayers.forEach(l => {
      if (l.id === $visibleLayer) l.layer.addTo(map)
      else l.layer.remove()
    })
  }

  $: if (map && $visibleContextLayers) {
    contextLayers.forEach(l => {
      if ($visibleContextLayers.includes(l.id)) l.layer.addTo(map)
      else l.layer.remove()
    })
  }
</script>

<div class="relative mx-auto {containerClass}">
  <!-- ! isolate is important to capture and contextualize leaflet's "400" z-index -->
  <div id={mapId} class="isolate h-full w-full">
    {#if !map}
      <LoadingPulse class="h-[300px]" />
    {/if}
  </div>
  {#if showLayerSwitcher}
    <BigMapStandaloneLayerSwitcher />
  {/if}
  <slot />
</div>

<style>
  :global(.leaflet-container a) {
    @apply text-orange;
  }
</style>
