// newfront/src/components/Data/FilterBar.svelte
<script lang="ts">
  import { gql, request } from "graphql-request";
  import { onMount } from "svelte";
  import { _ } from "svelte-i18n";
  import { GQLEndpoint } from "$lib";
  import { filters } from "$lib/filters";
  import { publicOnly } from "$lib/filters";
  import { countries, regions, user } from "$lib/stores";
  import { formfields } from "$lib/stores";
  import type { Investor } from "$lib/types/investor";
  import { isDefaultFilter, showFilterBar } from "$components/Data";
  import {
    implementation_status_choices,
    intention_of_investment_choices,
    nature_of_deal_choices,
  } from "$components/Fields/Display/choices";
  import FilterCollapse from "./FilterCollapse.svelte";
  import Wimpel from "./Wimpel.svelte";

  $: produce_choices = $formfields
    ? [
        {
          type: $_("Crop"),
          options: Object.entries($formfields.deal.crops.choices).map(([k, v]) => ({
            name: v,
            id: `crop_${k}`,
            value: k,
          })),
        },
        {
          type: $_("Livestock"),
          options: Object.entries($formfields.deal.animals.choices).map(([k, v]) => ({
            name: v,
            id: `animal_${k}`,
            value: k,
          })),
        },
        {
          type: $_("Minerals"),
          options: Object.entries($formfields.deal.mineral_resources.choices).map(
            ([k, v]) => ({ name: v, id: `mineral_${k}`, value: k })
          ),
        },
      ]
    : [];

  //   watch: {
  //     showFilterBar(state) {
  //       this.$emit("visibility-changed", state);
  //     },
  //   },
  $: console.log(produce_choices);

  $: countriesWithDeals = $countries.filter((c) => c.deals.length > 0);

  const choices = {
    implementation_status: {
      UNKNOWN: $_("No information"),
      ...implementation_status_choices,
    },
    nature_of_deal: nature_of_deal_choices,
    intention_of_investment: intention_of_investment_choices,
  };

  $: regionsWithGlobal = [
    {
      id: null,
      name: "Global",
    },
    ...$regions,
  ];

  let investors: Investor[] = [];
  async function getInvestors() {
    const query = gql`
      query Investors($limit: Int!, $subset: Subset) {
        investors(limit: $limit, subset: $subset) {
          id
          name
        }
      }
    `;
    const variables = {
      limit: 0,
      subset: $user?.is_authenticated ? "ACTIVE" : "PUBLIC",
    };
    const res = await request(GQLEndpoint, query, variables);
    investors = res.investors;
  }

  onMount(() => {
    getInvestors();
  });
</script>

<div
  class="absolute bg-white/90 top-0 left-0 bottom-0 z-10 flex text-sm drop-shadow-[3px_-3px_3px_rgba(0,0,0,0.3)] {$showFilterBar
    ? 'w-[clamp(220px,20%,300px)]'
    : 'w-0'}"
>
  <Wimpel
    showing={$showFilterBar}
    on:click={() => showFilterBar.set(!$showFilterBar)}
  />
  <div
    class="w-full h-full overflow-y-auto overflow-x-hidden p-2 flex flex-col"
    class:hidden={!$showFilterBar}
  >
    <div class="w-full self-start">
      <h3 class="mt-2 mb-1 text-black">{$_("Filter")}</h3>
      <span style="font-size: 0.8em">
        <label>
          <input type="checkbox" checked={$isDefaultFilter} />
          {$_("Default filter")}
        </label>
      </span>
      {#if $user?.bigrole}
        <!--v-if="$store.getters.userInGroup(['Administrators', 'Editors'])"-->
        <span style="font-size: 0.8em">
          <label>
            <input type="checkbox" checked={$publicOnly} />
            {$_("Public deals only")}
          </label>
        </span>
      {/if}

      <FilterCollapse
        title={$_("Land Matrix region")}
        clearable={!!$filters.region_id}
        on:click={() => ($filters.region_id = undefined)}
      >
        {#each regionsWithGlobal as reg}
          <label class="block">
            <input
              type="radio"
              bind:group={$filters.region_id}
              value={reg.id}
              on:change={() => ($filters.country_id = undefined)}
            />
            {$_(reg.name)}
          </label>
        {/each}
      </FilterCollapse>

      <FilterCollapse
        title={$_("Country")}
        clearable={!!$filters.country_id}
        on:click={() => ($filters.country_id = null)}
      >
        <select
          bind:value={$filters.country_id}
          class="inpt"
          on:change={() => ($filters.region_id = undefined)}
        >
          <option value={undefined} />
          {#each countriesWithDeals as c}
            <option value={c.id}>{c.name}</option>
          {/each}
        </select>
      </FilterCollapse>

      <FilterCollapse
        title={$_("Deal size")}
        clearable={!!($filters.deal_size_min || $filters.deal_size_max)}
        on:click={() => ($filters.deal_size_min = $filters.deal_size_max = undefined)}
      >
        <div class="field-has-appendix">
          <input
            bind:value={$filters.deal_size_min}
            type="number"
            class="inpt"
            placeholder={$_("from")}
            aria-label="from"
            max={$filters.deal_size_max}
          />
          <span>ha</span>
        </div>
        <div class="field-has-appendix">
          <input
            bind:value={$filters.deal_size_max}
            type="number"
            class="inpt"
            placeholder={$_("to")}
            aria-label="to"
            min={$filters.deal_size_min}
          />
          <span>ha</span>
        </div>
      </FilterCollapse>

      <!--        <FilterBarNegotiationStatusToggle />-->

      <FilterCollapse
        title={$_("Nature of the deal")}
        clearable={$filters.nature_of_deal.length > 0}
        on:click={() => ($filters.nature_of_deal = [])}
      >
        {#each Object.entries(choices.nature_of_deal) as [isval, isname]}
          <label class="block">
            <input type="checkbox" bind:group={$filters.nature_of_deal} value={isval} />
            {$_(isname)}
          </label>
        {/each}
      </FilterCollapse>

      <!--        <FilterCollapse-->
      <!--          :title="$_('Investor')"-->
      <!--          :clearable="!!(investor || investor_country)"-->
      <!--          @click="investor = investor_country = null"-->
      <!--        >-->
      <!--          <div>-->
      <!--            {{ $_("Investor name") }}-->
      <!--            <multi-select-->
      <!--              v-model="investor"-->
      <!--              :options="investors"-->
      <!--              :multiple="false"-->
      <!--              :close-on-select="true"-->
      <!--              placeholder="Investor"-->
      <!--              track-by="id"-->
      <!--              label="name"-->
      <!--              select-label=""-->
      <!--            />-->
      <!--            {{ $_("Country of registration") }}-->
      <!--            <multi-select-->
      <!--              v-model="investor_country"-->
      <!--              :options="countries"-->
      <!--              label="name"-->
      <!--              select-label=""-->
      <!--              placeholder="Country of registration"-->
      <!--            />-->
      <!--          </div>-->
      <!--        </FilterCollapse>-->

      <FilterCollapse
        title={$_("Year of initiation")}
        clearable={!!($filters.initiation_year_min || $filters.initiation_year_max)}
        on:click={() =>
          ($filters.initiation_year_min = $filters.initiation_year_max = undefined)}
      >
        <div class="flex">
          <input
            bind:value={$filters.initiation_year_min}
            type="number"
            class="inpt"
            placeholder="from"
            aria-label="from"
            min="1970"
            max={new Date().getFullYear()}
          />
          <input
            bind:value={$filters.initiation_year_max}
            type="number"
            class="inpt"
            placeholder="to"
            aria-label="to"
            min="1970"
            max={new Date().getFullYear()}
          />
        </div>

        <label class="block">
          <input
            id="initiation_year_unknown"
            bind:checked={$filters.initiation_year_unknown}
            type="checkbox"
            disabled={!$filters.initiation_year_min && !$filters.initiation_year_max}
          />

          {$_("Include unknown years")}
        </label>
      </FilterCollapse>

      <FilterCollapse
        title={$_("Implementation status")}
        clearable={$filters.implementation_status.length > 0}
        on:click={() => ($filters.implementation_status = [])}
      >
        {#each Object.entries(choices.implementation_status) as [isval, isname]}
          <label class="block">
            <input
              bind:group={$filters.implementation_status}
              class="form-check-input custom-control-input"
              type="checkbox"
              value={isval}
            />
            {$_(isname)}
          </label>
        {/each}
      </FilterCollapse>

      <FilterCollapse
        title={$_("Intention of investment")}
        clearable={$filters.intention_of_investment.length > 0}
        on:click={() => ($filters.intention_of_investment = [])}
      >
        <div class="hint p-1 mb-2 rounded bg-white text-xs italic">
          {$_(
            "Please note that excluding one intention of investment will exclude all deals that report the respective intention of investment, including deals that have other intentions of investments aside from the excluded one."
          )}
        </div>
        {#each Object.entries(choices.intention_of_investment) as [name, options]}
          <div>
            <strong>{$_(name)}</strong>
            {#each Object.entries(options) as [isval, isname]}
              <label class="block">
                <input
                  type="checkbox"
                  bind:group={$filters.intention_of_investment}
                  value={isval}
                />
                {$_(isname)}
              </label>
            {/each}
          </div>
        {/each}
      </FilterCollapse>

      <!--        <FilterCollapse-->
      <!--          :title="$_('Produce')"-->
      <!--          :clearable="produce.length > 0"-->
      <!--          @click="produce = []"-->
      <!--        >-->
      <!--          <multi-select-->
      <!--            v-model="produce"-->
      <!--            :options="produce_choices"-->
      <!--            :multiple="true"-->
      <!--            :close-on-select="false"-->
      <!--            placeholder="Produce"-->
      <!--            :group-select="true"-->
      <!--            group-label="type"-->
      <!--            group-values="options"-->
      <!--            track-by="id"-->
      <!--            label="name"-->
      <!--            select-label=""-->
      <!--          />-->
      <!--        </FilterCollapse>-->

      <FilterCollapse
        title={$_("Scope")}
        clearable={$filters.transnational !== null}
        on:click={() => ($filters.transnational = null)}
      >
        <label class="block">
          <input type="radio" bind:group={$filters.transnational} value={true} />
          {$_("Transnational")}
        </label>
        <label class="block">
          <input type="radio" bind:group={$filters.transnational} value={false} />
          {$_("Domestic")}
        </label>
      </FilterCollapse>

      <FilterCollapse
        title={$_("Forest concession")}
        clearable={$filters.forest_concession !== null}
        on:click={() => ($filters.forest_concession = null)}
      >
        <label class="block">
          <input type="radio" bind:group={$filters.forest_concession} value={null} />
          {$_("Included")}
        </label>
        <label class="block">
          <input type="radio" bind:group={$filters.forest_concession} value={false} />
          {$_("Excluded")}
        </label>
        <label class="block">
          <input type="radio" bind:group={$filters.forest_concession} value={true} />
          {$_("Only")}
        </label>
      </FilterCollapse>
    </div>
    <div class="self-end mt-auto pt-10 w-full">
      <slot />
    </div>
  </div>
</div>

<!--<style lang="scss">-->

<!--    .default-filter-switch {-->
<!--      &.active {-->
<!--        color: var(&#45;&#45;color-lm-orange);-->
<!--      }-->

<!--      label.custom-control-label {-->
<!--        font-size: 0.9rem;-->

<!--        &:hover {-->
<!--          cursor: pointer;-->
<!--        }-->

<!--        &:before {-->
<!--          font-size: 0.8rem;-->
<!--          background-color: rgba(black, 0.1);-->
<!--          border-width: 0;-->
<!--          width: 1.9em;-->
<!--          height: 0.65em;-->
<!--          margin-top: 0.2em;-->
<!--          margin-left: 0.15em;-->

<!--          &:focus {-->
<!--            outline: none;-->
<!--          }-->
<!--        }-->

<!--        &:after {-->
<!--          margin-top: -0.1em;-->
<!--          background-color: white;-->
<!--          box-shadow: 0 1px 2px rgba(black, 0.3);-->
<!--        }-->
<!--      }-->
<!--    }-->

<!--    .custom-switch .custom-control-input:checked ~ .custom-control-label {-->
<!--      &:before {-->
<!--        background-color: var(&#45;&#45;color-lm-orange-light-10);-->
<!--      }-->

<!--      &:after {-->
<!--        background-color: var(&#45;&#45;color-lm-orange);-->
<!--        box-shadow: 0 0 0 1px var(&#45;&#45;color-lm-orange-light);-->
<!--      }-->
<!--    }-->

<!--    .custom-control-input:focus ~ .custom-control-label {-->
<!--      &:before {-->
<!--        box-shadow: none;-->
<!--      }-->
<!--    }-->

<!--    .form-check {-->
<!--      padding: 0;-->

<!--      .custom-control.custom-checkbox {-->
<!--        min-height: 0;-->
<!--        padding-left: 1.3rem;-->

<!--        label.custom-control-label {-->
<!--          &:hover {-->
<!--            cursor: pointer;-->
<!--          }-->

<!--          line-height: 1.2;-->

<!--          &:before,-->
<!--          &:after {-->
<!--            top: 1px;-->
<!--            left: -1.3rem;-->
<!--          }-->
<!--        }-->
<!--      }-->

<!--      .custom-control-input:focus ~ .custom-control-label {-->
<!--        &:before {-->
<!--          border-color: #adb5bd;-->
<!--        }-->
<!--      }-->

<!--      .custom-control-input:checked ~ .custom-control-label {-->
<!--        &:before {-->
<!--          background-color: var(&#45;&#45;color-lm-orange-light);-->
<!--          border-color: transparent;-->
<!--        }-->
<!--      }-->

<!--      &:not(:first-child) {-->
<!--        .custom-control.custom-checkbox {-->
<!--          margin-top: 2px;-->
<!--        }-->
<!--      }-->
<!--    }-->
<!--  }-->
<!--</style>-->

// frontend/src/components/Map/FilterBar.vue
<template>
  <div class="filter-overlay" :class="{ collapsed: !showFilterOverlay }">
    <span class="wimpel" @click.prevent="showFilterOverlay = !showFilterOverlay">
      <svg viewBox="0 0 2 20" width="20px">
        <path d="M0,0 L2,2 L2,18 L0,20z"></path>
        <text x="0.3" y="11">
          {{ showFilterOverlay ? "&lsaquo;" : "&rsaquo;" }}
        </text>
      </svg>
    </span>
    <div class="overlay-content">
      <div class="main-pane">
        <strong>{{ $t("Filter") }}</strong
        ><br />
        <span style="font-size: 0.8em;">
          <a href="#" @click="$store.dispatch('resetFilters')">Set default filters</a> |
          <a href="#" @click="$store.dispatch('clearFilters')">Clear filters</a>
        </span>

        <FilterCollapse
          :title="$t('Region')"
          :clearable="region_id"
          @click="region_id = null"
        >
          <b-form-group>
            <b-form-radio
              v-model="region_id"
              name="regionRadio"
              :value="reg.id"
              v-for="reg in regions"
              @input="country = null"
            >
              {{ $t(reg.name) }}
            </b-form-radio>
          </b-form-group>
        </FilterCollapse>

        <FilterCollapse
          :title="$t('Country')"
          :clearable="country"
          @click="country = null"
        >
          <multiselect
            v-model="country"
            :options="countries"
            label="name"
            placeholder="Country"
            @input="region_id = null"
          />
        </FilterCollapse>
        <FilterCollapse
          :title="$t('Deal size')"
          :clearable="deal_size_min || deal_size_max"
          @click="deal_size_min = deal_size_max = null"
        >
          <div class="input-group">
            <input
              v-model="deal_size_min"
              type="number"
              class="form-control"
              :placeholder="$t('from')"
              aria-label="from"
              :max="deal_size_max"
            />
            <div class="input-group-append">
              <span class="input-group-text">ha</span>
            </div>
          </div>
          <div class="input-group">
            <input
              type="number"
              v-model="deal_size_max"
              class="form-control"
              :placeholder="$t('to')"
              aria-label="to"
              :min="deal_size_min"
            />
            <div class="input-group-append">
              <span class="input-group-text">ha</span>
            </div>
          </div>
        </FilterCollapse>

        <FilterCollapse
          :title="$t('Negotiation status')"
          :clearable="negotiation_status.length > 0"
          @click="negotiation_status = []"
        >
          <div v-for="(nsname, nsval) in choices.negotiation_status" class="form-check">
            <input
              class="form-check-input"
              type="checkbox"
              :value="nsval"
              :id="nsval"
              v-model="negotiation_status"
            />
            <label class="form-check-label" :for="nsval">
              {{ $t(nsname) }}
            </label>
          </div>
        </FilterCollapse>

        <FilterCollapse
          :title="$t('Nature of Deal')"
          :clearable="nature_of_deal.length > 0"
          @click="nature_of_deal = []"
        >
          <div v-for="(isname, isval) in choices.nature_of_deal" class="form-check">
            <input
              class="form-check-input"
              type="checkbox"
              :value="isval"
              :id="isval"
              v-model="nature_of_deal"
            />
            <label class="form-check-label" :for="isval">
              {{ $t(isname) }}
            </label>
          </div>
        </FilterCollapse>

        <FilterCollapse
          :title="$t('Investor')"
          :clearable="investor"
          @click="investor = null"
        >
          <div>
            <multiselect
              v-model="investor"
              :options="investors"
              :multiple="false"
              :close-on-select="true"
              placeholder="Investor"
              track-by="id"
              label="name"
            />
          </div>
        </FilterCollapse>

        <FilterCollapse
          :title="$t('Year of initiation')"
          :clearable="initiation_year_min || initiation_year_max"
          @click="initiation_year_min = initiation_year_max = null"
        >
          <form class="form-inline">
            <div class="input-group">
              <input
                type="number"
                v-model="initiation_year_min"
                class="form-control"
                placeholder="from"
                aria-label="from"
                min="1970"
                :max="year"
              />
            </div>
            <div class="input-group">
              <input
                type="number"
                v-model="initiation_year_max"
                class="form-control"
                placeholder="to"
                aria-label="to"
                min="1970"
                :max="year"
              />
            </div>
            <label>
              <input
                type="checkbox"
                :disabled="!initiation_year_min && !initiation_year_max"
                v-model="initiation_year_unknown"
              />
              Include unknown years
            </label>
          </form>
        </FilterCollapse>

        <FilterCollapse
          :title="$t('Implementation status')"
          :clearable="implementation_status.length > 0"
          @click="implementation_status = []"
        >
          <div
            v-for="(isname, isval) in choices.implementation_status"
            class="form-check"
          >
            <input
              class="form-check-input"
              type="checkbox"
              :value="isval"
              :id="isval"
              v-model="implementation_status"
            />
            <label class="form-check-label" :for="isval">
              {{ $t(isname) }}
            </label>
          </div>
        </FilterCollapse>

        <FilterCollapse
          :title="$t('Intention of Investment')"
          :clearable="intention_of_investment.length > 0"
          @click="intention_of_investment = []"
        >
          <div v-for="(options, name) in choices.intention_of_investment">
            <strong>{{ $t(name) }}</strong>
            <div v-for="(isname, isval) in options" class="form-check">
              <input
                class="form-check-input"
                type="checkbox"
                :value="isval"
                :id="isval"
                v-model="intention_of_investment"
              />
              <label class="form-check-label" :for="isval">
                {{ $t(isname) }}
              </label>
            </div>
          </div>
        </FilterCollapse>

        <FilterCollapse
          :title="$t('Produce')"
          :clearable="produce.length > 0"
          @click="produce = []"
        >
          <multiselect
            v-model="produce"
            :options="produce_choices"
            :multiple="true"
            :close-on-select="false"
            placeholder="Produce"
            :group-select="true"
            group-label="type"
            group-values="options"
            track-by="id"
            label="name"
          />
        </FilterCollapse>
        <FilterCollapse
          :title="$t('Transnational')"
          :clearable="transnational !== null"
          @click="transnational = null"
        >
          <b-form-group>
            <b-form-radio
              v-model="transnational"
              name="transnationalRadio"
              :value="true"
            >
              Transnational
            </b-form-radio>
            <b-form-radio
              v-model="transnational"
              name="transnationalRadio"
              :value="false"
            >
              Domestic
            </b-form-radio>
            <b-form-radio
              v-model="transnational"
              name="transnationalRadio"
              :value="null"
            >
              Both
            </b-form-radio>
          </b-form-group>
        </FilterCollapse>
        <FilterCollapse
          :title="$t('Forest Concession')"
          :clearable="forest_concession !== null"
          @click="forest_concession = null"
        >
          <b-form-group>
            <b-form-radio
              v-model="forest_concession"
              name="forest_concessionRadio"
              :value="true"
            >
              {{ $t("Included") }}
            </b-form-radio>
            <b-form-radio
              v-model="forest_concession"
              name="forest_concessionRadio"
              :value="false"
            >
              {{ $t("Excluded") }}
            </b-form-radio>
            <b-form-radio
              v-model="forest_concession"
              name="forest_concessionRadio"
              :value="null"
            >
              {{ $t("Both") }}
            </b-form-radio>
          </b-form-group>
        </FilterCollapse>
      </div>
      <div class="bottom-pane">
        <slot></slot>
      </div>
    </div>
  </div>
</template>

<script>
  import { mapState } from "vuex";
  import FilterCollapse from "./FilterCollapse";
  import gql from "graphql-tag";

  export default {
    name: "FilterBar",
    components: { FilterCollapse },
    apollo: {
      investors: {
        query: gql`
          query {
            investors(limit: 0) {
              id
              name
            }
          }
        `,
      },
    },
    data() {
      return {
        year: new Date().getFullYear(),
        showFilterOverlay: true,
        investors: [],
        defaultFilters: true,
        choices: {
          negotiation_status: {
            CONCLUDED: "Concluded",
            INTENDED: "Intended",
            FAILED: "Failed",
          },
          implementation_status: {
            PROJECT_NOT_STARTED: "Project not started",
            STARTUP_PHASE: "Start-up phase",
            IN_OPERATION: "In Operation",
            PROJECT_ABANDONED: "Project abandoned",
          },
          nature_of_deal: {
            OUTRIGHT_PURCHASE: "Outright Purchase",
            LEASE: "Lease",
            CONCESSION: "Concession",
            EXPLOITATION_PERMIT:
              "Exploitation permit / license / concession (for mineral resources)",
            PURE_CONTRACT_FARMING: "Pure contract farming",
          },
          intention_of_investment: {
            Agriculture: {
              BIOFUELS: "Biofuels",
              FOOD_CROPS: "Food crops",
              FODDER: "Fodder",
              LIVESTOCK: "Livestock",
              NON_FOOD_AGRICULTURE: "Non-food agricultural commodities",
              AGRICULTURE_UNSPECIFIED: "Agriculture unspecified",
            },
            Forestry: {
              TIMBER_PLANTATION: "Timber plantation",
              FOREST_LOGGING: "Forest logging / management",
              CARBON: "For carbon sequestration/REDD",
              FORESTRY_UNSPECIFIED: "Forestry unspecified",
            },

            Other: {
              MINING: "Mining",
              OIL_GAS_EXTRACTION: "Oil / Gas extraction",
              TOURISM: "Tourism",
              INDUSTRY: "Industry",
              CONVERSATION: "Conservation",
              LAND_SPECULATION: "Land speculation",
              RENEWABLE_ENERGY: "Renewable Energy",
              OTHER: "Other",
            },
          },
        },
      };
    },
    computed: {
      region_id: {
        get() {
          return this.filters.region_id;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "region_id", value });
        },
      },
      country: {
        get() {
          return this.countries.find((c) => c.id === this.filters.country_id);
        },
        set(value) {
          this.$store.dispatch("setFilter", {
            filter: "country_id",
            value: value ? value.id : value,
          });
        },
      },
      deal_size_min: {
        get() {
          return this.filters.deal_size_min;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "deal_size_min", value });
        },
      },
      deal_size_max: {
        get() {
          return this.filters.deal_size_max;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "deal_size_max", value });
        },
      },
      negotiation_status: {
        get() {
          return this.filters.negotiation_status;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "negotiation_status", value });
        },
      },
      nature_of_deal: {
        get() {
          return this.filters.nature_of_deal;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "nature_of_deal", value });
        },
      },
      investor: {
        get() {
          return this.filters.investor;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "investor", value });
        },
      },
      initiation_year_min: {
        get() {
          return this.filters.initiation_year_min;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "initiation_year_min", value });
        },
      },
      initiation_year_max: {
        get() {
          return this.filters.initiation_year_max;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "initiation_year_max", value });
        },
      },
      initiation_year_unknown: {
        get() {
          return this.filters.initiation_year_unknown;
        },
        set(value) {
          this.$store.dispatch("setFilter", {
            filter: "initiation_year_unknown",
            value,
          });
        },
      },
      implementation_status: {
        get() {
          return this.filters.implementation_status;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "implementation_status", value });
        },
      },
      intention_of_investment: {
        get() {
          return this.filters.intention_of_investment;
        },
        set(value) {
          this.$store.dispatch("setFilter", {
            filter: "intention_of_investment",
            value,
          });
        },
      },
      produce: {
        get() {
          return this.filters.produce;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "produce", value });
        },
      },
      transnational: {
        get() {
          return this.filters.transnational;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "transnational", value });
        },
      },
      forest_concession: {
        get() {
          return this.filters.forest_concession;
        },
        set(value) {
          this.$store.dispatch("setFilter", { filter: "forest_concession", value });
        },
      },
      ...mapState({
        filters: (state) => state.filters.filters,
        countries: (state) => state.page.countries,
        regions: (state) => {
          let global = {
            id: null,
            name: "Global",
          };
          return [global, ...state.page.regions];
        },
        dealFormfields: (state) => state.formfields.deal,
      }),
      intention_of_investment_choices() {
        if (!this.dealFormfields) return [];
        return Object.entries(this.dealFormfields.intention_of_investment.choices).map(
          ([k, v]) => {
            return {
              type: k,
              options: Object.entries(v).map(([ke, ve]) => ({
                name: ve,
                id: ke,
              })),
            };
          }
        );
      },
      produce_choices() {
        if (!this.dealFormfields) return [];
        return [
          {
            type: this.$t("Crop"),
            options: Object.entries(
              this.dealFormfields.crops.choices
            ).map(([k, v]) => ({ name: v, id: `crop_${k}`, value: k })),
          },
          {
            type: this.$t("Livestock"),
            options: Object.entries(
              this.dealFormfields.animals.choices
            ).map(([k, v]) => ({ name: v, id: `animal_${k}`, value: k })),
          },
          {
            type: this.$t("Minerals"),
            options: Object.entries(
              this.dealFormfields.resources.choices
            ).map(([k, v]) => ({ name: v, id: `mineral_${k}`, value: k })),
          },
        ];
      },
    },
  };
</script>

<style lang="scss">
  @import "../../scss/colors";

  .filter-overlay {
    position: absolute;
    background-color: rgba(255, 255, 255, 0.95);
    filter: drop-shadow(1px -1px 1px rgba(0, 0, 0, 0.3));
    border-right: 1px solid $primary;
    top: 0;
    left: 0;
    bottom: 0;
    z-index: 10;
    display: flex;

    .toggle-button {
      position: absolute;
      right: 10px;
    }

    .overlay-content {
      width: 20vw;
      max-width: 230px;
      height: 100%;
      overflow-y: auto;
      padding: 0.5em;
      display: flex;
      flex-direction: column;

      .main-pane {
        align-self: flex-start;
      }

      .bottom-pane {
        align-self: flex-end;
        margin-top: auto;
        padding-top: 40px;
        width: 100%;
      }
    }

    &.collapsed {
      width: 0;

      .toggle-button {
        position: static;
      }

      .overlay-content {
        display: none;
      }
    }
  }

  ul.layer-list {
    padding-left: 5px;
    list-style: none;

    div {
      color: $primary;
    }

    a {
      cursor: pointer;
    }
  }
  .wimpel {
    position: absolute;
    top: 25vh;
    cursor: pointer;
    right: -20px;
    svg {
      filter: drop-shadow(1px -1px 1px rgba(0, 0, 0, 0.3));
      color: black;
      path {
        fill: $primary;
      }
      text {
        font-size: 4px;
        fill: white;
      }
    }
  }
</style>
