// newfront/src/components/Map/MapMarkerPopup.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import type { Deal, Location } from "$lib/types/deal";
  import DisplayField from "$components/Fields/DisplayField.svelte";

  export let deal: Deal;
  export let location: Location;
</script>

<h3>{$_("Deal")} #{deal.id}</h3>
<div class="deal-summary">
  <DisplayField
    wrapperClasses="mb-4"
    labelClasses="font-bold"
    valueClasses=""
    fieldname="level_of_accuracy"
    model="location"
    value={location.level_of_accuracy}
  />
  <DisplayField
    wrapperClasses="mb-4"
    labelClasses="font-bold"
    valueClasses=""
    fieldname="current_intention_of_investment"
    value={deal.current_intention_of_investment}
  />
  <DisplayField
    wrapperClasses="mb-4"
    labelClasses="font-bold"
    valueClasses=""
    fieldname="deal_size"
    value={deal.deal_size}
  />
  <DisplayField
    wrapperClasses="mb-4"
    labelClasses="font-bold"
    valueClasses=""
    fieldname="operating_company"
    value={deal.operating_company}
  />
</div>
<a href="/deal/{deal.id}/" class="btn btn-primary !text-white">
  {$_("More details")}
</a>

// frontend/src/components/Map/MapMarkerPopup.vue
<template>
  <div class="deal-popup">
    <h3>Deal #{{ deal.id }}</h3>
    <div class="deal-summary">
      <DisplayField
        :wrapper-classes="['map-marker-popup-wrapper']"
        :label-classes="['map-marker-popup-label']"
        :value-classes="['map-marker-popup-value']"
        fieldname="level_of_accuracy"
        model="location"
        :value="location.level_of_accuracy"
      />
      <DisplayField
        :wrapper-classes="['map-marker-popup-wrapper']"
        :label-classes="['map-marker-popup-label']"
        :value-classes="['map-marker-popup-value']"
        fieldname="current_intention_of_investment"
        :value="deal.current_intention_of_investment"
      />
      <DisplayField
        :wrapper-classes="['map-marker-popup-wrapper']"
        :label-classes="['map-marker-popup-label']"
        :value-classes="['map-marker-popup-value']"
        fieldname="deal_size"
        :value="deal.deal_size"
      />
      <DisplayField
        :wrapper-classes="['map-marker-popup-wrapper']"
        :label-classes="['map-marker-popup-label']"
        :value-classes="['map-marker-popup-value']"
        fieldname="operating_company"
        :value="deal.operating_company"
      />
    </div>
    <router-link
      class="btn btn-primary"
      :to="{ name: 'deal_detail', params: { deal_id: deal.id } }"
    >
      {{ $t("More details") }}
    </router-link>
  </div>
</template>

<script>
  import DisplayField from "../Fields/DisplayField";
  export default {
    name: "MapPopup",
    components: { DisplayField },
    props: ["deal", "location"],
  };
</script>

<style lang="scss">
  .map-marker-popup-wrapper {
    margin-bottom: 1em;
  }
  .map-marker-popup-label {
    font-weight: bold;
  }
</style>
