// frontend/src/components/Map/MapMarkerPopup.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import type { DealHull, Location2 } from "$lib/types/newtypes"

  import DisplayField from "$components/Fields/DisplayField.svelte"

  export let deal: DealHull
  export let location: Location2

  const labelClass = "font-semibold"
  const valueClass = ""
  const wrapperClass = "mb-4"
</script>

<div class="heading4">{$_("Deal")} #{deal.id}</div>
<div class="deal-summary">
  <DisplayField
    fieldname="location.level_of_accuracy"
    {labelClass}
    showLabel
    value={location.level_of_accuracy}
    {valueClass}
    {wrapperClass}
  />
  <DisplayField
    fieldname="current_intention_of_investment"
    {labelClass}
    showLabel
    value={deal.selected_version.current_intention_of_investment}
    {valueClass}
    {wrapperClass}
  />
  <DisplayField
    fieldname="deal_size"
    {labelClass}
    showLabel
    value={deal.selected_version.deal_size}
    {valueClass}
    {wrapperClass}
  />
  <DisplayField
    fieldname="operating_company"
    {labelClass}
    showLabel
    value={deal.selected_version.operating_company}
    {valueClass}
    {wrapperClass}
  />
</div>
<a class="btn btn-primary !text-white" href="/deal/{deal.id}/">
  {$_("More details")}
</a>

// frontend/src/components/Map/MapMarkerPopup.vue
<template>
  <div class="deal-popup">
    <h3>Deal #{{ deal.id }}</h3>
    <div class="deal-summary">
      <DisplayField
        :wrapper-classes="['map-marker-popup-wrapper']"
        :label-classes="['map-marker-popup-label']"
        :value-classes="['map-marker-popup-value']"
        fieldname="level_of_accuracy"
        model="location"
        :value="location.level_of_accuracy"
      />
      <DisplayField
        :wrapper-classes="['map-marker-popup-wrapper']"
        :label-classes="['map-marker-popup-label']"
        :value-classes="['map-marker-popup-value']"
        fieldname="current_intention_of_investment"
        :value="deal.current_intention_of_investment"
      />
      <DisplayField
        :wrapper-classes="['map-marker-popup-wrapper']"
        :label-classes="['map-marker-popup-label']"
        :value-classes="['map-marker-popup-value']"
        fieldname="deal_size"
        :value="deal.deal_size"
      />
      <DisplayField
        :wrapper-classes="['map-marker-popup-wrapper']"
        :label-classes="['map-marker-popup-label']"
        :value-classes="['map-marker-popup-value']"
        fieldname="operating_company"
        :value="deal.operating_company"
      />
    </div>
    <router-link
      class="btn btn-primary"
      :to="{ name: 'deal_detail', params: { deal_id: deal.id } }"
    >
      {{ $t("More details") }}
    </router-link>
  </div>
</template>

<script>
  import DisplayField from "../Fields/DisplayField";
  export default {
    name: "MapPopup",
    components: { DisplayField },
    props: ["deal", "location"],
  };
</script>

<style lang="scss">
  .map-marker-popup-wrapper {
    margin-bottom: 1em;
  }
  .map-marker-popup-label {
    font-weight: bold;
  }
</style>
