// frontend/src/components/Wagtail/FAQsBlock.svelte
<script lang="ts">
  import { slide } from "svelte/transition"

  import { browser } from "$app/environment"

  export let value

  let locationHash = browser ? location.hash : undefined

  function updateHash(slug) {
    if (!browser) return
    let newslug
    if (location.hash === slug) newslug = ""
    else newslug = slug
    locationHash = newslug
    location.hash = newslug
  }
</script>

<div data-block="faqs_block" class="border border-gray-400">
  {#each value.faqs as faq}
    <div
      class="cursor-pointer border-b border-gray-400 bg-gray-50 dark:bg-gray-600"
      on:click={() => updateHash(`#${faq.slug}`)}
    >
      <div class="py-4 px-6">
        <button
          class="text-orange"
          on:click|stopPropagation={() => updateHash(`#${faq.slug}`)}
        >
          {faq.question}
        </button>
      </div>
      {#if locationHash === `#${faq.slug}`}
        <div
          transition:slide
          id="collapse-{faq.slug}"
          class="border-t border-gray-400 bg-white p-4 dark:bg-gray-600"
        >
          <div class="card-body">{@html faq.answer}</div>
        </div>
      {/if}
    </div>
  {/each}
</div>

// frontend/src/components/Wagtail/FaqsBlock.vue
<template>
  <div id="accordion" class="accordion">
    <div v-for="faq in value.faqs" :key="faq.slug" class="card">
      <div id="headingOne" class="card-header">
        <h5 class="mb-0">
          <button
            :aria-controls="`collapse-${faq.slug}`"
            :data-target="`#collapse-${faq.slug}`"
            aria-expanded="true"
            class="btn btn-link"
            data-toggle="collapse"
            @click="updateHash(`#${faq.slug}`)"
          >
            {{ faq.question }}
          </button>
        </h5>
      </div>
      <div
        :id="`collapse-${faq.slug}`"
        :class="{ show: location_hash === `#${faq.slug}` }"
        aria-labelledby="headingOne"
        class="collapse"
        data-parent="#accordion"
      >
        <div class="card-body" v-html="faq.answer" />
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    props: {
      value: { type: Object, required: true },
    },
    data() {
      return { location_hash: location.hash };
    },
    methods: {
      updateHash(slug) {
        if (location.hash === slug) this.$router.push(this.$route.path);
        else this.$router.push(this.$route.path + slug);
      },
    },
  };
</script>
