// frontend/src/components/Charts/WebOfTransnationalDeals.vue
<template>
  <div style="height: 100%;">
    <LoadingPulse v-if="$apollo.queries.transnational_deals.loading" />
    <div id="svg-container">
      <svg id="svgweb" width="800"></svg>
    </div>
  </div>
</template>

<style lang="scss">
  #svg-container {
    text-align: center;
    height: 100%;
    display: flex;
    justify-content: center;
    .link {
      fill: none;
      stroke: #555;
      stroke-opacity: 0.4;
      stroke-width: 4.5px;
    }
    #svgweb {
      text {
        font-size: 14px;
      }
    }
  }
</style>
<script>
  import store from "/store";
  import { LandMatrixRadialSpider } from "./d3_hierarchical_edge_bundling";
  import gql from "graphql-tag";
  import LoadingPulse from "/components/Data/LoadingPulse";

  export default {
    name: "WebOfTransnationalDeals",
    components: { LoadingPulse },
    apollo: {
      transnational_deals: gql`
        query {
          transnational_deals
        }
      `,
    },
    data() {
      return {
        transnational_deals: [],
      };
    },
    beforeRouteEnter(to, from, next) {
      let title = "Web of transnational deals";
      store.dispatch("setPageContext", {
        title: title,
        breadcrumbs: [
          { link: { name: "wagtail" }, name: "Home" },
          { link: { name: "charts" }, name: "Charts" },
          { name: title },
        ],
      });
      next();
    },
    watch: {
      transnational_deals() {
        LandMatrixRadialSpider(this.transnational_deals, "#svgweb");
      },
    },
    // mounted() {
    //   // if (this.transnational_deals.length) {
    //   //   LandMatrixRadialSpider(this.transnational_deals, "svg");
    //   // }
    // }
  };
</script>

<style scoped></style>

// newfront/src/routes/charts/web-of-transnational-deals.svelte
<script lang="ts" context="module">
  import type { Load } from "@sveltejs/kit";
  import { showContextBar } from "$components/Data";

  export const load: Load = async () => {
    showContextBar.set(true);
    return {};
  };
</script>

<script lang="ts">
  import { gql } from "graphql-tag";
  import { _ } from "svelte-i18n";
  import { browser } from "$app/env";
  import { client } from "$lib/apolloClient";
  import { filters } from "$lib/filters";
  import ChartsContainer from "$components/Data/Charts/ChartsContainer.svelte";
  import ContextBarWebOfTransnationalDeals from "$components/Data/Charts/ContextBarWebOfTransnationalDeals.svelte";
  import LoadingPulse from "$components/LoadingPulse.svelte";
  import { LandMatrixRadialSpider } from "./d3_hierarchical_edge_bundling";

  let transnational_deals = [];

  function redrawSpider(deals, country_id): void {
    LandMatrixRadialSpider(
      deals,
      "#svg-container > svg",
      country_id,
      (country) => ($filters.country_id = +country)
    );
  }

  const grabTransnationalDeals = async () => {
    const { data } = await $client.query<{ transnational_deals: unknown[] }>({
      query: gql`
        query WebOfTransnationalDeals($filters: [Filter]) {
          transnational_deals(filters: $filters)
        }
      `,
      variables: {
        filters: $filters
          .toGQLFilterArray()
          .filter(
            (f) => f.field !== "country_id" && f.field !== "country.fk_region_id"
          ),
      },
    });
    transnational_deals = data.transnational_deals;
  };

  $: $filters && grabTransnationalDeals();
  $: browser && redrawSpider(transnational_deals, $filters.country_id);
</script>

<svelte:head>
  <title>{$_("Web of transnational deals | Land Matrix")}</title>
</svelte:head>

<ChartsContainer>
  {#if transnational_deals.length === 0}
    <div class="absolute inset-0">
      <LoadingPulse data-v-if="$apollo.queries.transnational_deals.loading" />
    </div>
  {/if}

  <div id="svg-container" class="max-h-full w-full p-8 pt-16">
    <svg />
  </div>

  <div slot="ContextBar">
    <ContextBarWebOfTransnationalDeals />
  </div>
</ChartsContainer>

<style>
  :global(#incoming-marker) {
    fill: var(--color-lm-orange);
  }
  :global(#outgoing-marker) {
    fill: var(--color-lm-investor);
  }

  :global(path.incoming-highlighted) {
    stroke: var(--color-lm-orange);
    stroke-width: 2;
    marker-start: url(#incoming-marker);
  }
  :global(path.outgoing-highlighted) {
    stroke: var(--color-lm-investor);
    stroke-width: 2;
    marker-start: url(#outgoing-marker);
  }

  :global(path.incoming-permahighlight) {
    stroke: var(--color-lm-orange);
    stroke-width: 2.5;
    marker-start: url(#incoming-marker);
  }
  :global(path.outgoing-permahighlight) {
    stroke: var(--color-lm-investor);
    stroke-width: 2.5;
    marker-start: url(#outgoing-marker);
  }

  :global(text.incoming-highlighted) {
    font-size: 14px;
    cursor: pointer;
    font-weight: bold;
    fill: var(--color-lm-orange);
  }
  :global(text.outgoing-highlighted) {
    font-size: 14px;
    cursor: pointer;
    font-weight: bold;
    fill: var(--color-lm-investor);
  }
</style>
