// newfront/src/components/Data/Charts/ContextBarWebOfTransnationalDeals.svelte
<script lang="ts">
  import { gql } from "@urql/svelte";
  import { _ } from "svelte-i18n";
  import { page } from "$app/stores";
  import { filters, FilterValues } from "$lib/filters";
  import { chartDescriptions, countries } from "$lib/stores";

  $: country =
    $filters.country_id && $countries.find((c) => c.id === $filters.country_id);

  let global_rankings;
  let country_investments_and_rankings: {
    investing: [];
    invested: [];
    ranking_deal: null;
    ranking_investor: null;
  };
  let investing_countries = [];
  let invested_countries = [];

  async function _grabInvestmentsAndRankings(countryID: number, fltrs: FilterValues) {
    if (!countryID) return;
    const { data } = await $page.data.urqlClient
      .query(
        gql`
          query InvestmentsAndRankings($id: Int!, $filters: [Filter]) {
            country_investments_and_rankings(id: $id, filters: $filters)
          }
        `,
        {
          id: countryID,
          filters: fltrs
            .toGQLFilterArray()
            .filter((f) => f.field !== "country_id" && f.field !== "country.region_id"),
        }
      )
      .toPromise();

    let countryInvestmentsAndRankings = data.country_investments_and_rankings;
    investing_countries = countryInvestmentsAndRankings.investing.map((x) => ({
      country_name: $countries.find((c) => c.id === x.country_id).name,
      ...x,
    }));
    invested_countries = countryInvestmentsAndRankings.invested.map((x) => ({
      country_name: $countries.find((c) => c.id === x.country_id).name,
      ...x,
    }));
  }

  $: _grabInvestmentsAndRankings($filters.country_id, $filters);

  //     apollo: {
  //     global_rankings: {
  //       query: gql`
  //         query GlobalRankings($filters: [Filter]) {
  //           global_rankings(filters: $filters)
  //         }
  //       `,
  //       variables() {
  //         return {
  //           filters: this.$store.getters.defaultFiltersForGQL,
  //         };
  //       },
  //     },
  // global_ranking_deals() {
  //   if (!this.global_rankings) return;
  //   if (this.$store.state.countries.length === 0) return;
  //   return this.global_rankings.ranking_deal.map((x) => {
  //     let country_name = this.getCountryOrRegion({
  //       id: +x.country_id,
  //     }).name;
  //     return { country_name, ...x };
  //   });
  // },
  // global_ranking_investors() {
  //   if (!this.global_rankings) return;
  //   if (this.$store.state.countries.length === 0) return;
  //   return this.global_rankings.ranking_investor.map((x) => {
  //     let country_name = this.getCountryOrRegion({
  //       id: +x.country_id,
  //     }).name;
  //     return { country_name, ...x };
  //   });
  // },
</script>

<div>
  <h2>{$_("Web of transnational deals")}</h2>
  <div>{@html $chartDescriptions?.web_of_transnational_deals}</div>
  {#if country}
    <div class="mb-5 border border-gray-300 bg-gray-100 p-4 text-sm shadow-inner">
      <h4 class="mt-0">{country.name}</h4>
      <!--      <div class="mx-3">-->
      <!--        <b-->
      <!--          class="deal-ranking"-->
      <!--          v-if="this.country_investments_and_rankings.ranking_deal"-->
      <!--        >-->
      <!--          <i class="fas fa-compress-arrows-alt"></i> #{{-->
      <!--            this.country_investments_and_rankings.ranking_deal-->
      <!--          }}-->
      <!--        </b>-->
      <!--        &nbsp;-->
      <!--        <b-->
      <!--          class="investor-ranking"-->
      <!--          v-if="this.country_investments_and_rankings.ranking_investor"-->
      <!--        >-->
      <!--          <i class="fas fa-expand-arrows-alt"></i> #{{-->
      <!--            this.country_investments_and_rankings.ranking_investor-->
      <!--          }}-->
      <!--        </b>-->
      <!--      </div>-->
      {#if investing_countries.length > 0}
        <div>
          <b class="text-lg">
            {$_("Countries investing in {country}", {
              values: { country: country.name },
            })}
          </b>
          <table class="table-striped w-full">
            <tbody>
              {#each investing_countries as icountry}
                <tr>
                  <th class="text-left">{icountry.country_name}</th>
                  <td class="whitespace-nowrap text-right">
                    {icountry.count} deals<br />
                    {icountry.size} ha
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
      {#if invested_countries.length > 0}
        <div class="mt-6">
          <b class="text-lg">
            {$_("Countries {country} invests in", {
              values: { country: country.name },
            })}
          </b>
          <table class="table-striped w-full">
            <tbody>
              {#each invested_countries as icountry}
                <tr>
                  <th class="text-left">{icountry.country_name}</th>
                  <td class="whitespace-nowrap text-right">
                    {icountry.count} deals<br />
                    {icountry.size} ha
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      {/if}
    </div>
  {/if}
  <!--    <div v-else class="hint-box">-->
  <!--      <h4>{{ $t("Global ranking") }}</h4>-->
  <!--      <div v-if="global_rankings">-->
  <!--        <b><i class="fas fa-compress-arrows-alt"></i> Top invested-in Countries</b>-->
  <!--        <table class="table-striped">-->
  <!--          <tbody>-->
  <!--            <tr v-for="rank in global_ranking_deals">-->
  <!--              <th class="text-left">{{ rank.country_name }}</th>-->
  <!--              <td class="text-right whitespace-nowrap">{{ rank.deal_size__sum.toLocaleString() }} ha</td>-->
  <!--            </tr>-->
  <!--          </tbody>-->
  <!--        </table>-->

  <!--        <b><i class="fas fa-expand-arrows-alt"></i> Top investing Countries</b>-->
  <!--        <table class="table-striped">-->
  <!--          <tbody>-->
  <!--            <tr v-for="rank in global_ranking_investors">-->
  <!--              <th class="text-left">{{ rank.country_name }}</th>-->
  <!--              <td class="text-right whitespace-nowrap">{{ rank.deal_size__sum.toLocaleString() }} ha</td>-->
  <!--            </tr>-->
  <!--          </tbody>-->
  <!--        </table>-->
  <!--      </div>-->
  <!--    </div>-->
</div>

// frontend/src/components/Charts/ContextBarWebOfTransnationalDeals.vue
<template>
  <div>
    <h2 class="bar-title">Web of transnational deals</h2>
    <div v-html="chart_desc" />
    <div v-if="country" class="hint-box">
      <h4>{{ country.name }}</h4>
      <!--      <div class="mx-3">-->
      <!--        <b-->
      <!--          class="deal-ranking"-->
      <!--          v-if="this.country_investments_and_rankings.ranking_deal"-->
      <!--        >-->
      <!--          <i class="fas fa-compress-arrows-alt"></i> #{{-->
      <!--            this.country_investments_and_rankings.ranking_deal-->
      <!--          }}-->
      <!--        </b>-->
      <!--        &nbsp;-->
      <!--        <b-->
      <!--          class="investor-ranking"-->
      <!--          v-if="this.country_investments_and_rankings.ranking_investor"-->
      <!--        >-->
      <!--          <i class="fas fa-expand-arrows-alt"></i> #{{-->
      <!--            this.country_investments_and_rankings.ranking_investor-->
      <!--          }}-->
      <!--        </b>-->
      <!--      </div>-->
      <div v-if="investing_countries.length > 0">
        <b>Countries investing in {{ country.name }}</b>
        <table class="table-striped">
          <tbody>
            <tr v-for="icountry in investing_countries">
              <th>{{ icountry.country_name }}</th>
              <td>
                {{ icountry.count }} deals<br />
                {{ icountry.size }} ha
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div v-if="invested_countries.length > 0">
        <b>Countries {{ country.name }} invests in</b>
        <table class="table-striped">
          <tbody>
            <tr v-for="icountry in invested_countries">
              <th>{{ icountry.country_name }}</th>
              <td>
                {{ icountry.count }} deals<br />
                {{ icountry.size }} ha
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div v-else class="hint-box">
      <h4>{{ $t("Global ranking") }}</h4>
      <div v-if="global_rankings">
        <b><i class="fas fa-compress-arrows-alt"></i> Top invested-in Countries</b>
        <table class="table-striped">
          <tbody>
            <tr v-for="rank in global_ranking_deals">
              <th>{{ rank.country_name }}</th>
              <td>{{ rank.deal_size__sum.toLocaleString() }} ha</td>
            </tr>
          </tbody>
        </table>

        <b><i class="fas fa-expand-arrows-alt"></i> Top investing Countries</b>
        <table class="table-striped">
          <tbody>
            <tr v-for="rank in global_ranking_investors">
              <th>{{ rank.country_name }}</th>
              <td>{{ rank.deal_size__sum.toLocaleString() }} ha</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
  import { mapGetters } from "vuex";
  import {
    country_investments_and_rankings_query,
    global_rankings_query,
  } from "/store/queries";

  export default {
    name: "ContextBarWebOfTransnationalDeals",
    props: ["filters"],
    apollo: {
      global_rankings: global_rankings_query,
      country_investments_and_rankings: country_investments_and_rankings_query,
    },
    data() {
      return {
        global_rankings: null,
        country_investments_and_rankings: {
          investing: [],
          invested: [],
          ranking_deal: null,
          ranking_investor: null,
        },
      };
    },
    computed: {
      ...mapGetters(["getCountryOrRegion"]),
      country_id() {
        return this.$store.state.filters.filters.country_id;
      },
      chart_desc() {
        if (!this.$store.state.page.chartDescriptions) return null;
        return this.$store.state.page.chartDescriptions.web_of_transnational_deals;
      },
      country() {
        if (!this.country_id || this.country_id === 0) return null;
        return this.getCountryOrRegion({
          id: this.country_id,
        });
      },
      investing_countries() {
        return this.country_investments_and_rankings.investing.map((x) => {
          let country_name = this.getCountryOrRegion({
            id: +x.country_id,
          }).name;
          return { country_name, ...x };
        });
      },
      invested_countries() {
        return this.country_investments_and_rankings.invested.map((x) => {
          let country_name = this.getCountryOrRegion({
            id: +x.country_id,
          }).name;
          return { country_name, ...x };
        });
      },
      global_ranking_deals() {
        if (!this.global_rankings) return;
        if (this.$store.state.page.countries.length === 0) return;
        return this.global_rankings.ranking_deal.map((x) => {
          let country_name = this.getCountryOrRegion({
            id: +x.country_id,
          }).name;
          return { country_name, ...x };
        });
      },
      global_ranking_investors() {
        if (!this.global_rankings) return;
        if (this.$store.state.page.countries.length === 0) return;
        return this.global_rankings.ranking_investor.map((x) => {
          let country_name = this.getCountryOrRegion({
            id: +x.country_id,
          }).name;
          return { country_name, ...x };
        });
      },
    },
  };
</script>

<style lang="scss">
  @import "src/scss/colors";

  .investor-ranking {
    color: $primary;
  }
  .deal-ranking {
    color: $lm_investor;
  }

  .hint-box {
    padding: 1em;
    font-size: 0.9em;
    margin-bottom: 20px;
    background-color: #f5f5f5;
    border: 1px solid #e3e3e3;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
  }
</style>
<style lang="scss" scoped>
  b {
    padding: 3px;
    display: inline-block;
  }
  table {
    width: 100%;
  }

  th {
    text-align: left;
  }

  td {
    text-align: right;
    white-space: nowrap;
  }
</style>
