// newfront/src/components/StatusPieChart.svelte
<script lang="ts">
  import type { ChartData, ChartOptions } from "chart.js";
  import {
    ArcElement,
    CategoryScale,
    Chart as ChartJS,
    Legend,
    Title,
    Tooltip,
  } from "chart.js?client";
  import { Pie } from "svelte-chartjs?client";
  import { _ } from "svelte-i18n";

  ChartJS.register(Title, Tooltip, Legend, ArcElement, CategoryScale);

  export let data: ChartData<"pie", number[], string>;
  export let unit = "";

  $: totals = data.datasets.map((dSet) =>
    dSet.data.reduce((sum, value) => sum + value)
  );
  let i18nData: ChartData<"pie", number[], string>;
  $: i18nData = { ...data, labels: data.labels?.map((label) => $_(label)) };

  const options: ChartOptions<"pie"> = {
    responsive: true,
    aspectRatio: 1,
    plugins: {
      tooltip: {
        callbacks: {
          label: (context) => {
            const value = context.dataset.data[context.dataIndex];
            const percentage = (value / totals[context.datasetIndex]) * 100;

            let ret = `${context.label}: `;
            ret += Math.round(value).toLocaleString("fr");
            if (unit) ret += ` ${unit}`;
            ret += " (" + percentage.toFixed(0) + "%)";
            return ret;
          },
        },
      },
      legend: {
        position: "bottom",
      },
    },
  };
</script>

<!--svelte plugin for IntelliJ cannot index props for SvelteComponentTyped-->
<!--https://github.com/tomblachut/svelte-intellij/issues/206-->
<Pie data={i18nData} {options} />

// frontend/src/components/Charts/StatusPieChart.vue
<template>
  <div>
    <div class="chart-container" :style="containerStyle">
      <canvas ref="chart-canvas"></canvas>
    </div>
    <!--    <Legend v-if="legendItems && (displayLegend || legends)" :items="legendItems" />-->
  </div>
</template>

<script lang="ts">
  import {
    Chart,
    ArcElement,
    PieController,
    Title,
    Tooltip,
    Legend,
    SubTitle,
  } from "chart.js";
  import numeral from "numeral";

  import Vue from "vue";

  Chart.register(ArcElement, PieController, Legend, Tooltip, SubTitle, Title);

  export default Vue.extend({
    name: "StatusPieChart",
    // components: { Legend },
    props: {
      dealData: { type: Array, required: true },
      aspectRatio: { type: Number, default: 2 },
      containerStyle: { type: Object, default: () => ({ maxWidth: "auto" }) },
      unit: { type: String, required: false, default: null },
      valueField: { type: String, default: "value" },
      // legends: { type: Object, default: null },
    },
    data: function () {
      return {
        canvasCtx: null,
        chart: null,
      };
    },
    computed: {
      chartoptions() {
        return {
          cutoutPercentage: 0,
          plugins: {
            legend: {
              position: "bottom",
              labels: {
                boxWidth: 10,
                textAlign: "left",
              },
            },
            // title: { display: true, text: "Custom Chart Title" },
            tooltip: {
              callbacks: {
                label: (context) => {
                  let value = context.dataset.data[context.dataIndex];
                  value = numeral(value).format("0,0");
                  if (this.unit) value += ` ${this.unit}`;
                  return `${context.label}: ${value}`;
                },
              },
            },
          },
          aspectRatio: this.aspectRatio,
          responsive: true,
        };
      },
      chartdata() {
        return {
          labels: this.dealData.map((n) => n.label),
          datasets: [
            {
              data: this.dealData.map((n) => n[this.valueField]),
              backgroundColor: this.dealData.map((n) => n.color),
            },
          ],
        };
      },
      legendItems() {
        if (this.legends) return this.legends;
        else return this.dealData;
      },
    },
    watch: {
      dealData: {
        deep: true,
        handler() {
          this.updateChart();
        },
      },
      valueField: {
        handler() {
          this.updateChart();
        },
      },
    },
    mounted() {
      this.createChart();
    },
    methods: {
      createChart() {
        if (this.dealData) {
          let chart_container = this.$refs["chart-canvas"];
          this.chart = new Chart(chart_container, {
            type: "pie",
            data: this.chartdata,
            options: this.chartoptions,
          });
        }
      },
      updateChart() {
        if (this.chart && this.dealData) {
          this.chart.data = this.chartdata;
          this.chart.update();
        } else {
          this.createChart();
        }
      },
    },
  });
</script>

<style lang="scss" scoped>
  .chart-container {
    width: 90%;
    margin: auto;
  }
</style>
