// frontend/src/components/Charts/CountryProfile/CountryProfileChartWrapper.vue
<template>
  <div class="country-profile-chart-wrapper">
    <slot name="heading">
      <h2>{{ title }}</h2>
    </slot>
    <div class="svg-wrapper">
      <slot name="default"></slot>
    </div>
    <div class="download-buttons">
      <button class="btn" @click="downloadImage('svg')">
        <i class="fas fa-file-image" /> SVG
      </button>
      <span id="download-png">
        <button
          class="btn"
          :class="{ 'use-chrome': !isChrome }"
          @click="downloadImage('png')"
        >
          <i class="fas fa-file-image" />
          PNG
        </button>
      </span>
      <b-tooltip v-if="!isChrome" target="download-png" triggers="hover">
        At the moment, downloading PNG does not work in Firefox.
      </b-tooltip>
      <span id="download-webp">
        <button
          class="btn"
          :class="{ 'use-chrome': !isChrome }"
          @click="downloadImage('webp')"
        >
          <i class="fas fa-file-image" /> WebP
        </button>
      </span>
      <b-tooltip v-if="!isChrome" target="download-webp" triggers="hover">
        At the moment, downloading WebP does not work in Firefox.
      </b-tooltip>
      <span style="margin: 2rem 0">|</span>
      <button class="btn" @click="$emit('downloadJSON')">
        <i class="fas fa-file-code" /> JSON
      </button>
      <button class="btn" @click="$emit('downloadCSV')">
        <i class="fas fa-file-code" /> CSV
      </button>
    </div>
    <div class="legend">
      <slot name="legend" />
    </div>
  </div>
</template>

<script lang="ts">
  import Vue from "vue";
  import { data_deal_query } from "$views/Data/query";
  import { chart_download, fileName } from "$utils/charts";
  import type { Deal } from "$types/deal";

  export default Vue.extend({
    name: "CountryProfileChartWrapper",
    components: {},
    props: {
      svgId: { type: String, required: true },
      title: { type: String, required: true },
    },
    data() {
      return { deals: [] as Deal[] };
    },
    apollo: { deals: data_deal_query },
    computed: {
      isChrome(): boolean {
        return /Google Inc/.test(navigator.vendor);
      },
    },
    methods: {
      downloadImage(filetype: string) {
        chart_download(
          document.getElementById(this.svgId),
          `image/${filetype}`,
          fileName(this.title, `.${filetype}`)
        );
      },
    },
  });
</script>

<style lang="scss" scoped>
  .country-profile-chart-wrapper {
    min-height: 75vh;
    margin: 1rem 3rem 1rem;
    background: var(--color-lm-orange-light-10);
    border-radius: 1rem;
    padding: 1rem;
    display: flex;
    flex-flow: column nowrap;
  }
  h2 {
    font-size: 1.2rem;
  }
  .svg-wrapper {
    flex: 1 1 auto;
    max-width: 100%;
    border-radius: 5px 5px 0 0;
    background: white;
    display: flex;
    justify-content: center;
    align-items: center;
    * > {
      flex: 1 1 auto;
    }
  }
  .download-buttons {
    background: #2d2d2dff;
    color: var(--color-lm-light);
    border-radius: 0 0 5px 5px;

    button {
      color: var(--color-lm-light);
      font-size: 0.85rem;
      padding: 0 0.75rem 0.15rem;
    }
  }
  .legend {
    flex-shrink: 0;
    padding: 0.4rem;
  }
  .use-chrome {
    opacity: 0.7;
    pointer-events: none;
  }
</style>

// newfront/src/components/Data/Charts/CountryProfile/CountryProfileChartWrapper.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { browser } from "$app/env";
  import FileCodeIcon from "$components/icons/FileCodeIcon.svelte";
  import FileImageIcon from "$components/icons/FileImageIcon.svelte";
  import { chart_download, fileName } from "../utils";

  export let title: string;
  export let svgID: string;

  const dispatch = createEventDispatcher();
  $: isChrome = browser && /Google Inc/.test(navigator.vendor);

  function downloadImage(filetype: string) {
    chart_download(
      document.getElementById(svgID),
      `image/${filetype}`,
      fileName(title, `.${filetype}`)
    );
  }
</script>

<div class="min-h-[75vh] mx-4 my-12 p-1 flex flex-col flex-nowrap bg-orange-50">
  <slot name="heading">
    <h2 class="text-lg">{title}</h2>
  </slot>
  <div
    class="max-w-full bg-white flex justify-center items-center flex-auto	svg-wrapper"
  >
    <slot class="flex-auto" />
  </div>
  <div class="bg-[#2d2d2d] text-lm-light text-sm">
    <button on:click={() => downloadImage("svg")} class="pb-1 px-3">
      <FileImageIcon /> SVG
    </button>
    <span
      id="download-png"
      title={isChrome ? "" : "At the moment, downloading PNG does not work in Firefox."}
    >
      <button
        class="pb-1 px-3"
        class:use-chrome={!isChrome}
        on:click={() => downloadImage("png")}
      >
        <FileImageIcon />
        PNG
      </button>
    </span>

    <span
      id="download-webp"
      title={isChrome
        ? ""
        : "At the moment, downloading WebP does not work in Firefox."}
    >
      <button
        class="pb-1 px-3"
        class:use-chrome={!isChrome}
        on:click={() => downloadImage("webp")}
      >
        <FileImageIcon /> WebP
      </button>
    </span>

    <span style="margin: 2rem 0">|</span>
    <button class="pb-1 px-3" on:click={() => dispatch("downloadJSON")}>
      <FileCodeIcon /> JSON
    </button>
    <button class="pb-1 px-3" on:click={() => dispatch("downloadCSV")}>
      <FileCodeIcon /> CSV
    </button>
  </div>
  <div class="flex-shrink-0 p-2">
    <slot name="legend" />
  </div>
</div>

<style>
  .use-chrome {
    opacity: 0.7;
    pointer-events: none;
  }
</style>
