// frontend/src/components/Charts/CountryProfile/DynamicsOfDeal.vue
<template>
  <CountryProfileChartWrapper
    svg-id="dynamicsofdeal"
    :title="title"
    @downloadJSON="downloadJSON"
    @downloadCSV="downloadCSV"
  >
    <template slot="default">
      <svg id="dynamicsofdeal" />
    </template>

    <template slot="legend">
      {{
        $t(
          "Please note: {number} deals have multiple investor types. The full size of the deal is assigned to each investor type.",
          { number: multideals }
        )
      }}
    </template>
  </CountryProfileChartWrapper>
</template>

<script lang="ts">
  import Vue, { PropType } from "vue";
  import CountryProfileChartWrapper from "$components/Charts/CountryProfile/CountryProfileChartWrapper.vue";
  import {
    dynamics_csv,
    DynamicsDataPoint,
    DynamicsOfDeal,
  } from "$components/Charts/CountryProfile/dynamics_of_deal";
  import { classification_choices } from "$utils/choices";
  import type { Deal } from "$types/deal";
  import { a_download, fileName } from "$utils/charts";

  export default Vue.extend({
    name: "DynamicsOfDeal",
    components: { CountryProfileChartWrapper },
    props: {
      deals: { type: [] as PropType<Deal[]>, required: true },
    },
    data() {
      return {
        title: this.$t("Dynamics of deal by investor type").toString(),
        svg: new DynamicsOfDeal(),
        multideals: 0,
        payload: [] as DynamicsDataPoint[],
      };
    },
    watch: {
      deals() {
        if (!this.svg || !this.deals) return;
        let pots: { [key: string]: number } = {};
        this.deals.forEach((d: Deal) => {
          if (d.top_investors.length > 1) this.multideals += 1;
          d.top_investors.forEach((i) => {
            const cl = i.classification;
            pots[cl] = pots[cl]
              ? pots[cl] + d.current_contract_size
              : d.current_contract_size;
          });
        });

        this.payload = Object.entries(pots).map(([k, v]) => ({
          name: this.$t(classification_choices[k] || "Unknown").toString(),
          value: v,
        }));

        this.svg.do_the_graph("#dynamicsofdeal", this.payload);
      },
    },
    methods: {
      downloadJSON() {
        let data =
          "data:application/json;charset=utf-8," +
          encodeURIComponent(JSON.stringify(this.payload, null, 2));
        a_download(data, fileName(this.title, ".json"));
      },
      downloadCSV() {
        const csv = dynamics_csv(this.payload);
        let data = "data:text/csv;charset=utf-8," + encodeURIComponent(csv);
        a_download(data, fileName(this.title, ".csv"));
      },
    },
  });
</script>

// newfront/src/components/Data/Charts/CountryProfile/DynamicsOfDeal.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import { browser } from "$app/env";
  import { deals } from "$lib/data";
  import { classification_choices } from "$components/Fields/Display/choices";
  import { a_download, fileName } from "../utils";
  import CountryProfileChartWrapper from "./CountryProfileChartWrapper.svelte";
  import { dynamics_csv, DynamicsOfDeal } from "./dynamics_of_deal";
  import type { DynamicsDataPoint } from "./dynamics_of_deal";

  const title = $_("Dynamics of deal by investor type");
  const svg = new DynamicsOfDeal();
  let multideals = 0;
  let payload: DynamicsDataPoint[] = [];

  $: if (browser && $deals && $deals.length > 0) {
    let pots: { [key: string]: number } = {};
    $deals.forEach((d) => {
      if (d.top_investors.length > 1) multideals += 1;
      d.top_investors.forEach((i) => {
        const cl = i.classification;
        pots[cl] = pots[cl]
          ? pots[cl] + d.current_contract_size
          : d.current_contract_size;
      });
    });

    payload = Object.entries(pots).map(([k, v]) => ({
      name: $_(classification_choices[k] || "Unknown").toString(),
      value: v,
    }));

    svg.do_the_graph("#dynamicsofdeal", payload);
  }

  function downloadJSON() {
    let data =
      "data:application/json;charset=utf-8," +
      encodeURIComponent(JSON.stringify(payload, null, 2));
    a_download(data, fileName(title, ".json"));
  }
  function downloadCSV() {
    const csv = dynamics_csv(payload);
    let data = "data:text/csv;charset=utf-8," + encodeURIComponent(csv);
    a_download(data, fileName(title, ".csv"));
  }
</script>

<CountryProfileChartWrapper
  svgID="dynamicsofdeal"
  {title}
  on:downloadJSON={downloadJSON}
  on:downloadCSV={downloadCSV}
>
  <template slot="default">
    <svg id="dynamicsofdeal" />
  </template>

  <template slot="legend">
    {$_(
      "Please note: {number} deals have multiple investor types. The full size of the deal is assigned to each investor type.",
      { value: { number: multideals } }
    )}
  </template>
</CountryProfileChartWrapper>
