// frontend/src/components/Navbar.vue
<template>
  <nav class="navbar navbar-expand-xl navbar-light">
    <div class="container-fluid">
      <router-link class="navbar-brand" to="/">
        <img :src="lm_logo" alt="Land Matrix" />
      </router-link>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#main-navbar-collapse"
        aria-controls="main-navbar-collapse"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="main-navbar-collapse" ref="mainbar" class="collapse navbar-collapse">
        <ul class="navbar-nav align-items-center">
          <li class="nav-item dropdown">
            <a
              id="map-dropdown"
              href="#"
              role="button"
              class="nav-link dropdown-toggle"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              {{ $t("Data") }}
            </a>
            <div class="dropdown-menu">
              <router-link
                v-for="data_link in data_links"
                :key="data_link.name"
                :to="data_link.link"
                class="dropdown-item"
                @click.native="closeMenu"
              >
                {{ $t(data_link.name) }}
              </router-link>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a
              id="obs-dropdown"
              href="#"
              role="button"
              class="nav-link dropdown-toggle"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              {{ $t("Observatories") }}
            </a>
            <div class="dropdown-menu">
              <div
                v-for="(obs, obsgroup) in observatories_group"
                :key="obsgroup"
                class="dropdown-menu-group"
              >
                <router-link
                  v-for="observatory in obs"
                  :key="observatory.id"
                  class="dropdown-item"
                  :to="`/observatory/${observatory.meta.slug}/`"
                  @click.native="closeMenu"
                >
                  {{ observatory.title }}
                </router-link>
              </div>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a
              id="res-dropdown"
              href="#"
              role="button"
              class="nav-link dropdown-toggle"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              {{ $t("Resources") }}
            </a>
            <div class="dropdown-menu">
              <router-link
                v-for="cat in blogcategories"
                :key="cat.slug"
                class="dropdown-item"
                :to="`/resources/?category=${cat.slug}`"
                @click.native="closeMenu"
              >
                {{ $t(cat.name) }}
              </router-link>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a
              id="about-dropdown"
              href="#"
              role="button"
              class="nav-link dropdown-toggle"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              {{ $t("About") }}
            </a>
            <div class="dropdown-menu">
              <router-link
                v-for="about_link in aboutLinks"
                :key="about_link.link"
                :to="about_link.link"
                class="dropdown-item"
                @click.native="closeMenu"
              >
                {{ $t(about_link.name) }}
              </router-link>
            </div>
          </li>
          <li class="nav-item">
            <router-link class="nav-link" :to="`/faq/`" @click.native="closeMenu">
              {{ $t("FAQ") }}
            </router-link>
          </li>
          <li class="nav-item">
            <router-link
              class="nav-link"
              :to="`/contribute/`"
              @click.native="closeMenu"
            >
              {{ $t("Contribute") }}
            </router-link>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto align-items-center">
          <NavbarSearch />
          <li class="nav-item dropdown">
            <a
              id="languageDropdown"
              role="button"
              class="nav-link dropdown-toggle"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="fa fa-language" aria-hidden="true"></i>
              {{ languages[language] }}
            </a>
            <div class="dropdown-menu">
              <div
                v-for="(lingo, lcode) in languages"
                :key="lingo"
                :class="{ active: lcode === language }"
                class="dropdown-item"
                @click="switchLanguage(lcode)"
              >
                {{ lingo }} ({{ lcode }})
              </div>
            </div>
          </li>
          <li v-if="user" class="nav-item dropdown">
            <a
              id="navbarDropdown"
              href="#"
              role="button"
              class="nav-link dropdown-toggle"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              {{ user.initials }}
              <i v-if="user.role === 'ADMINISTRATOR'" class="fas fa-user-astronaut"></i>
              <i v-else-if="user.role === 'EDITOR'" class="fas fa-user-nurse"></i>
              <i v-else-if="user.is_impersonate" class="fa fa-user-secret"></i>
              <i v-else class="fa fa-user"></i>
            </a>
            <div
              ref="userMenu"
              class="dropdown-menu dropdown-menu-right"
              aria-labelledby="#navbarDropdown"
            >
              <p class="name-emblem">
                {{ user.full_name }}
                <br />
                <small>{{ $t(user.bigrole) }}</small>
              </p>
              <div class="dropdown-divider"></div>
              <!--suppress HtmlUnknownTarget -->
              <a
                v-if="user.is_impersonate"
                class="dropdown-item"
                href="/impersonate/stop/?next=/dashboard/"
              >
                {{ $t("Stop impersonation") }}
              </a>
              <div v-if="user.is_impersonate" class="dropdown-divider"></div>

              <router-link class="dropdown-item" :to="{ name: 'manager' }">
                {{ $t("Manage") }}
              </router-link>
              <router-link class="dropdown-item" :to="{ name: 'case_statistics' }">
                {{ $t("Case statistics") }}
              </router-link>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/deal/add/">
                {{ $t("Add a deal") }}
              </a>

              <a class="dropdown-item" @click.prevent="dispatchLogout">
                {{ $t("Logout") }}
              </a>
            </div>
          </li>
          <li v-if="!user" class="nav-item dropdown">
            <a
              id="navbarDropdownAnonymous"
              href="#"
              role="button"
              title="Login/Register"
              class="nav-link dropdown-toggle"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <i class="far fa-user"></i>
            </a>
            <div
              class="dropdown-menu dropdown-menu-right"
              aria-labelledby="#navbarDropdownAnonymous"
            >
              <form class="px-4 pt-3" @submit.prevent="dispatchLogin">
                <div class="form-group">
                  <input
                    id="username"
                    v-model="username"
                    type="text"
                    class="form-control"
                    autocomplete="username"
                    placeholder="Username"
                  />
                </div>
                <div class="form-group">
                  <input
                    id="password"
                    v-model="password"
                    type="password"
                    class="form-control"
                    autocomplete="current-password"
                    placeholder="Password"
                  />
                </div>
                <button type="submit" class="btn btn-secondary">
                  {{ $t("Login") }}
                </button>
                <p class="mt-3 text-danger small">{{ login_failed_message }}</p>
              </form>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/accounts/register/">{{
                $t("New around here? Sign up")
              }}</a>
              <a class="dropdown-item" href="/accounts/password_reset/">{{
                $t("Forgot password?")
              }}</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script lang="ts">
  import NavbarSearch from "$components/NavbarSearch.vue";
  import { blogcategories_query } from "$store/queries";
  import Cookies from "js-cookie";
  import lm_logo from "$static/images/lm-logo.png";
  import Vue from "vue";

  export default Vue.extend({
    components: { NavbarSearch },
    data() {
      return {
        lm_logo,
        username: null,
        password: null,
        login_failed_message: "",
        language: Cookies.get("django_language") ?? "en",
        languages: { en: "English", es: "Español", fr: "Français", ru: "Русский" },
        blogcategories: [],
        data_links: [
          { name: "Map", link: { name: "map" } },
          { name: "Deals", link: { name: "list_deals" } },
          { name: "Investors", link: { name: "list_investors" } },
          { name: "Charts", link: { name: "charts" } },
        ],
      };
    },
    apollo: { blogcategories: blogcategories_query },
    computed: {
      user() {
        return this.$store.state.user;
      },
      aboutPages() {
        return this.$store.state.aboutPages;
      },
      aboutLinks() {
        return this.$store.state.aboutPages.map((page) => {
          return {
            name: page.title,
            link: `/about/${page.meta.slug}/`,
          };
        });
      },
      observatories_group() {
        let ret = { global: [], regions: [], countries: [] };
        this.$store.state.observatories.forEach((ob) => {
          if (ob.country) ret.countries.push(ob);
          else if (ob.region) ret.regions.push(ob);
          else ret.global.push(ob);
        });
        return ret;
      },
    },
    methods: {
      switchLanguage(locale) {
        this.$store.dispatch("setLocale", locale);
        this.$i18n.locale = locale;
        this.language = locale;
      },
      dispatchLogout() {
        this.$store.dispatch("logout").then(() => location.reload());
      },
      dispatchLogin() {
        this.$store
          .dispatch("login", { username: this.username, password: this.password })
          .then(() => {
            location.reload();
            // this.login_failed_message = "";
            // if (this.$refs.userMenu) {
            //   this.$refs.userMenu.classList.remove("show");
            // }
          })
          .catch((response) => {
            this.login_failed_message = response.error;
          });
      },
      closeMenu() {
        if (this.$refs.mainbar.classList.contains("show")) {
          this.$refs.mainbar.classList.remove("show");
        }
      },
    },
  });
</script>

<style lang="scss" scoped>
  nav {
    position: sticky;
    top: 0;
    z-index: 1030;
    background-color: white !important;
  }

  .navbar-light .navbar-nav .nav-item .nav-link {
    font-size: 16px;
    line-height: 18px;
    font-weight: 500;
    color: black;
    padding: 0.5rem 1.1rem;

    &:hover {
      color: var(--color-lm-orange);
    }

    &.active {
      background: var(--color-lm-orange);
    }
  }

  .navbar {
    border-bottom: 10px solid var(--color-lm-orange);
    padding: 0;

    .dropdown-menu {
      border: 1px solid var(--color-lm-orange);
      border-radius: 0;
      padding: 0;

      .dropdown-menu-group + .dropdown-menu-group {
        margin: 0;
        border-top: 1px solid #e9ecef;
      }

      .dropdown-item {
        padding: 0.5rem 1rem;
      }
    }
  }

  .navbar-brand {
    margin-top: 2px;
    margin-right: 1.5rem;
    margin-left: 0.7rem;

    > img {
      height: 38px;
      width: 144px;
      min-width: 144px;
      max-width: 144px;
    }
  }
  .name-emblem {
    padding: 0.5rem 0 0 1rem;
    line-height: 1.2em;
    color: gray;
  }

  .router-link-exact-active {
    pointer-events: none;
    &:hover {
      background: inherit;
      cursor: default;
    }
  }
</style>

// newfront/src/components/Navbar.svelte
<script lang="ts">
  import Cookies from "js-cookie";
  import { _, locale } from "svelte-i18n";
  import { page } from "$app/stores";
  import {
    aboutPages,
    blogCategories,
    fetchBasis,
    observatoryPages,
  } from "$lib/stores";
  import type { ObservatoryPage } from "$lib/types/wagtail";
  import { dispatchLogin, dispatchLogout } from "$lib/user";
  import TranslateIcon from "$components/icons/TranslateIcon.svelte";
  import UserAstronautSolid from "$components/icons/UserAstronautSolid.svelte";
  import UserNurseSolid from "$components/icons/UserNurseSolid.svelte";
  import UserRegular from "$components/icons/UserRegular.svelte";
  import UserSecretSolid from "$components/icons/UserSecretSolid.svelte";
  import NavDropDown from "./LowLevel/NavDropDown.svelte";
  import NavbarSearch from "./NavbarSearch.svelte";

  let language = Cookies.get("django_language") ?? "en";
  const languages = { en: "English", es: "Español", fr: "Français", ru: "Русский" };
  const dataLinks = [
    { name: "Map", href: "/map" },
    { name: "Deals", href: "/list/deals" },
    { name: "Investors", href: "/list/investors" },
    { name: "Charts", href: "/charts" },
  ];

  let observatoriesGroups = { global: [], regions: [], countries: [] };
  $observatoryPages.forEach((op: ObservatoryPage) => {
    if (op.country) observatoriesGroups.countries.push(op);
    else if (op.region) observatoriesGroups.regions.push(op);
    else observatoriesGroups.global.push(op);
  });

  async function switchLanguage(lang: string) {
    language = lang;
    Cookies.set("django_language", lang);
    await locale.set(lang);
    await fetchBasis(lang);
  }

  let username = "";
  let password = "";
  let login_failed_message = "";

  $: user = $page.stuff.user;

  async function login() {
    const res = await dispatchLogin(username, password);
    if (res.status === true) await location.reload();
  }
  async function logout() {
    if (await dispatchLogout()) location.reload();
  }
</script>

<nav class="sticky top-0 z-[1030] bg-white border-b-8 border-orange flex px-2">
  <div class="mx-6 w-full lg:container lg:mx-auto flex justify-between p-1">
    <a class="mt-1 mr-6" href="/">
      <img
        alt="Land Matrix"
        class="h-[38px] w-[144px] min-w-[144px] max-w-[144px]"
        src="/images/lm-logo.png"
      />
    </a>
    <button
      class="inline-block py-1 px-3 leading-none bg-transparent border border-transparent rounded text-gray-500 border-gray-600 lg:hidden"
      data-target="#navbarCollapse"
      data-toggle="collapse"
      type="button"
    >
      <svg
        class="inline-block w-6 h-6 align-middle bg-center bg-no-repeat"
        viewBox="0 0 30 30"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M4 7h22M4 15h22M4 23h22"
          stroke="rgba(0,0,0,0.5)"
          stroke-linecap="round"
          stroke-miterlimit="10"
          stroke-width="2"
        />
      </svg>
    </button>
    <div class="hidden w-full flex-grow items-center lg:flex lg:w-auto">
      <ul class="flex w-full items-center">
        <NavDropDown title={$_("Data")}>
          <ul class="border border-orange bg-white">
            {#each dataLinks as { name, href }}
              <li class="whitespace-nowrap">
                <a {href} class="nav-link">
                  {$_(name)}
                </a>
              </li>
            {/each}
          </ul>
        </NavDropDown>

        <NavDropDown title={$_("Observatories")}>
          <div class="divide-y divide-solid border border-orange bg-white">
            {#each Object.values(observatoriesGroups) as obs}
              <ul>
                {#each obs as observatory}
                  <li class="whitespace-nowrap">
                    <a class="nav-link" href="/observatory/{observatory.meta.slug}">
                      {observatory.title}
                    </a>
                  </li>
                {/each}
              </ul>
            {/each}
          </div>
        </NavDropDown>

        <NavDropDown title={$_("Resources")}>
          <ul class="border border-orange bg-white">
            {#each $blogCategories as cat}
              <li class="whitespace-nowrap">
                <a class="nav-link" href="/resources/?category={cat.slug}">
                  {$_(cat.name)}
                </a>
              </li>
            {/each}
          </ul>
        </NavDropDown>

        <NavDropDown title={$_("About")}>
          <ul class="border border-orange bg-white">
            {#each $aboutPages as { title, meta }}
              <li class="whitespace-nowrap">
                <a class="nav-link" href="/about/{meta.slug}/">
                  {$_(title)}
                </a>
              </li>
            {/each}
          </ul>
        </NavDropDown>

        <li class="nav-item">
          <a class="nav-link" href="/faq/">
            {$_("FAQ")}
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contribute/">
            {$_("Contribute")}
          </a>
        </li>
      </ul>
      <ul class="flex items-center ml-auto">
        <NavbarSearch />

        <NavDropDown placement="bottom-end">
          <div slot="title" class="whitespace-nowrap flex items-center gap-1">
            <TranslateIcon class="h-4 w-4 inline" />
            {languages[language]}
          </div>

          <ul class="border border-orange bg-white">
            {#each Object.entries(languages) as [lcode, lingo]}
              <li class="whitespace-nowrap">
                <a
                  class="nav-link"
                  class:active={lcode === language}
                  on:click={() => switchLanguage(lcode)}
                >
                  {lingo} ({lcode})
                </a>
              </li>
            {/each}
          </ul>
        </NavDropDown>

        {#if user}
          <NavDropDown placement="bottom-end">
            <div slot="title" class="whitespace-nowrap flex items-center gap-1">
              {user.initials}
              {#if user.role === "ADMINISTRATOR"}
                <UserAstronautSolid class="h-4 w-4 inline" />
                <i class="fas fa-user-astronaut" />
              {:else if user.role === "EDITOR"}
                <UserNurseSolid class="h-4 w-4 inline" />
                <i class="fas fa-user-nurse" />
              {:else if user.is_impersonate}
                <UserSecretSolid class="h-4 w-4 inline" />
                <i class="fa fa-user-secret" />
              {:else}
                <i class="fa fa-user" />
              {/if}
            </div>

            <div class="divide-y divide-solid border border-orange bg-white">
              <p class="pt-2 pl-4 text-gray-400 leading-5 mb-2">
                {user.full_name}
                <br />
                <small>{user?.role ? $_(user?.role) : ""}</small>
              </p>

              {#if user.is_impersonate}
                <ul>
                  <li>
                    <a class="nav-link" href="/impersonate/stop/?next=/dashboard/">
                      {$_("Stop impersonation")}
                    </a>
                  </li>
                </ul>
              {/if}

              <ul>
                <li>
                  <a class="nav-link" href="/manager/">
                    {$_("Manage")}
                  </a>
                </li>
                <li class="whitespace-nowrap">
                  <a class="nav-link" href="/case_statistics/">
                    {$_("Case statistics")}
                  </a>
                </li>
              </ul>
              <ul>
                <li>
                  <a class="nav-link" href="/deal/add">{$_("Add a deal")}</a>
                </li>
                <li>
                  <a class="nav-link" on:click|preventDefault={logout}>
                    {$_("Logout")}
                  </a>
                </li>
              </ul>
            </div>
          </NavDropDown>
        {:else}
          <NavDropDown placement="bottom-end">
            <div slot="title" class="whitespace-nowrap" title="Login/Register">
              <UserRegular class="h-4 w-4 inline mx-1" />
            </div>
            <div class="divide-y divide-solid border border-orange bg-white">
              <form on:submit|preventDefault={login} class="px-4 pt-3 space-y-2">
                <input
                  autocomplete="username"
                  class="inpt"
                  id="username"
                  placeholder="Username"
                  type="text"
                  bind:value={username}
                />
                <input
                  autocomplete="current-password"
                  class="inpt"
                  id="password"
                  placeholder="Password"
                  type="password"
                  bind:value={password}
                />
                <button class="btn btn-secondary" type="submit">
                  {$_("Login")}
                </button>
                <p class="mt-3 text-danger small">{login_failed_message}</p>
              </form>
              <ul>
                <li class="whitespace-nowrap">
                  <a class="nav-link" href="/account/register/">
                    {$_("New around here? Sign up")}
                  </a>
                </li>
                <li class="whitespace-nowrap">
                  <a class="nav-link" href="/account/password_reset/">
                    {$_("Forgot password?")}
                  </a>
                </li>
              </ul>
            </div>
          </NavDropDown>
        {/if}
      </ul>
    </div>
  </div>
</nav>

<style>
  :global(.nav-link) {
    @apply px-4 py-2 block text-black;
    @apply hover:bg-gray-200;
    @apply active:bg-orange active:text-white;
  }
  :global(.nav-link.active) {
    @apply bg-orange text-white;
  }
</style>
