// frontend/src/components/PageTitle.vue
<template>
  <div v-if="$slots.default" class="container">
    <h1>
      <span><slot /></span>
    </h1>
  </div>
</template>

<script>
  export default {
    props: {
      title: { type: String, default: "" },
    },
  };
</script>

<style lang="scss" scoped>
  h1 {
    margin-top: 1.25rem;
    font-size: 1.75rem;
    text-align: center;
    color: var(--color-lm-orange);

    &:before {
      background: #c1c1c1;
      content: "";
      display: block;
      height: 1px;
      position: absolute;
      top: 50%;
      width: 100%;
    }
    span {
      font-family: "Unit", sans-serif;
      font-weight: bold;
      text-transform: uppercase;
      background: #ffffff;
      padding: 0 1em;
      position: relative;
      z-index: 1;
    }
  }
</style>

// newfront/src/components/PageTitle.svelte
{#if $$slots?.default}
  <div class="container mx-auto mt-9 mb-5">
    <h1
      class="text-center relative text-3xl before:content-[''] before:bg-gray-300 before:block before:h-[1px] before:absolute before:top-1/2 before:w-full"
    >
      <span
        class="uppercase font-bold text-orange uppercase px-4 relative bg-white z-10"
      >
        <slot />
      </span>
    </h1>
  </div>
{/if}
