// frontend/src/components/Fields/Edit/DecimalField.svelte
<script lang="ts">
  import type { FormField } from "../fields"
  import LowLevelDecimalField from "./LowLevelDecimalField.svelte"

  export let formfield: FormField
  export let value: number
</script>

<div class="decimal_field">
  <LowLevelDecimalField
    bind:value
    required={formfield.required}
    unit={formfield.unit}
    max={formfield.max_value}
    min={formfield.min_value}
    decimals={formfield.class === "IntegerField" ? 0 : 2}
    name={formfield.name}
  />
</div>

// frontend/src/components/Fields/Edit/DecimalField.vue
<template>
  <div class="decimal_field">
    <LowLevelDecimalField
      v-model="val"
      :name="formfield.name"
      :required="formfield.required"
      :unit="formfield.unit"
      :max-value="formfield.max_value"
      :min-value="formfield.min_value"
      :decimals="formfield.class === 'IntegerField' ? 0 : 2"
    />
  </div>
</template>

<script>
  import LowLevelDecimalField from "./LowLevelDecimalField";

  export default {
    components: { LowLevelDecimalField },
    props: {
      formfield: { type: Object, required: true },
      value: { type: Number, required: false, default: null },
      model: { type: String, required: true },
    },
    computed: {
      val: {
        get() {
          return this.value;
        },
        set(v) {
          this.$emit("input", v);
        },
      },
    },
  };
</script>
