// newfront/src/components/Fields/Edit/FileField.svelte
<script lang="ts">
  import { gql } from "@apollo/client/core";
  import { _ } from "svelte-i18n";
  import { client } from "$lib/apolloClient";
  import FilePdfIcon from "$components/icons/FilePdfIcon.svelte";

  export let value;

  function removeFile() {
    if (confirm($_("Do you really want to remove this file?")) === true) value = "";
  }

  function uploadFile({ target: { files = [] } }) {
    if (!files.length) return;
    let fr = new FileReader();
    fr.onload = async () => {
      const { data } = await $client.mutate<{ upload_datasource_file: string }>({
        mutation: gql`
          mutation ($filename: String!, $payload: String!) {
            upload_datasource_file(filename: $filename, payload: $payload)
          }
        `,
        variables: { filename: files[0].name, payload: fr.result },
      });
      value = data.upload_datasource_file;
    };
    fr.readAsDataURL(files[0]);
  }
</script>

<div class="file_field">
  {#if value}
    <div class="flex w-full justify-between">
      <div>
        <a href="{import.meta.env.VITE_MEDIA_URL}{value}`" target="_blank">
          <FilePdfIcon />
          {value.replace("uploads/", "")}
        </a>
        <br />
        {$_("Change")}:
        <input type="file" on:change={uploadFile} />
      </div>

      <button class="btn btn-danger" on:click|preventDefault={removeFile}>
        {$_("Remove this file")}
      </button>
    </div>
  {:else}
    <input type="file" on:change={uploadFile} />
  {/if}
  <span class="text-gray-400 text-sm block pt-2">{$_("Maximum file size: 10MB")}</span>
</div>

// frontend/src/components/Fields/Edit/FileField.vue
<template>
  <div>
    <div v-if="value">
      <a :href="`${media_url}${value}`" target="_blank">
        <i class="far fa-file-pdf"></i>
        {{ value.replace("uploads/", "") }}
      </a>
      <br />
      Change:
      <input
        style="display: inline"
        type="file"
        :name="formfield.name"
        @change="uploadFile"
      /><br />
      <a href="#" @click.prevent="removeFile">Remove this file</a>
    </div>
    <div v-else>
      <input type="file" :name="formfield.name" @change="uploadFile" />
    </div>
  </div>
</template>

<script>
  import gql from "graphql-tag";

  export default {
    props: {
      formfield: { type: Object, required: true },
      value: { type: String, required: false, default: "" },
      model: { type: String, required: true },
    },
    data() {
      return {
        media_url: import.meta.env.VITE_MEDIA_URL,
        user: this.$store.state.page.user,
      };
    },
    methods: {
      removeFile() {
        if (confirm(this.$t("Do you really want to remove this file?")) === true) {
          this.$emit("input", "");
        }
      },
      uploadFile({ target: { files = [] } }) {
        if (!files.length) return;
        let fr = new FileReader();
        fr.onload = () => {
          this.$apollo
            .mutate({
              mutation: gql`
                mutation ($filename: String!, $payload: String!) {
                  upload_datasource_file(filename: $filename, payload: $payload)
                }
              `,
              variables: {
                filename: files[0].name,
                payload: fr.result,
              },
            })
            .then(({ data: { upload_datasource_file } }) => {
              this.$emit("input", upload_datasource_file);
            });
        };
        fr.readAsDataURL(files[0]);
      },
    },
  };
</script>
