// frontend/src/components/Fields/Edit/FileField.vue
<template>
  <div>
    <div v-if="value">
      <a :href="`${media_url}${value}`" target="_blank">
        <i class="far fa-file-pdf"></i>
        {{ value.replace("uploads/", "") }}
      </a>
      <br />
      Change:
      <input
        style="display: inline"
        type="file"
        :name="formfield.name"
        @change="uploadFile"
      /><br />
      <a href="#" @click.prevent="removeFile">Remove this file</a>
    </div>
    <div v-else>
      <input type="file" :name="formfield.name" @change="uploadFile" />
    </div>
  </div>
</template>

<script>
  import gql from "graphql-tag";

  export default {
    props: {
      formfield: { type: Object, required: true },
      value: { type: String, required: false, default: "" },
      model: { type: String, required: true },
    },
    data() {
      return {
        media_url: import.meta.env.VITE_MEDIA_URL,
        user: this.$store.state.page.user,
      };
    },
    methods: {
      removeFile() {
        if (confirm(this.$t("Do you really want to remove this file?")) === true) {
          this.$emit("input", "");
        }
      },
      uploadFile({ target: { files = [] } }) {
        if (!files.length) return;
        let fr = new FileReader();
        fr.onload = () => {
          this.$apollo
            .mutate({
              mutation: gql`
                mutation ($filename: String!, $payload: String!) {
                  upload_datasource_file(filename: $filename, payload: $payload)
                }
              `,
              variables: {
                filename: files[0].name,
                payload: fr.result,
              },
            })
            .then(({ data: { upload_datasource_file } }) => {
              this.$emit("input", upload_datasource_file);
            });
        };
        fr.readAsDataURL(files[0]);
      },
    },
  };
</script>

// frontend/src/components/Fields/Edit/FileField.svelte
<script lang="ts">
  import { Client, gql } from "@urql/svelte"
  import { _ } from "svelte-i18n"

  import { page } from "$app/stores"

  import type { FormField } from "$components/Fields/fields"
  import FilePdfIcon from "$components/icons/FilePdfIcon.svelte"

  export let value: string
  export let accept: string
  export let formfield: FormField
  // "application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint," +
  // " text/plain, application/pdf, image/*";

  function removeFile() {
    if (confirm($_("Do you really want to remove this file?")) === true) value = ""
  }

  function uploadFile({ target: { files = [] } }) {
    if (!files.length) return
    let fr = new FileReader()
    fr.onload = async () => {
      const { error, data } = await ($page.data.urqlClient as Client)
        .mutation<{ upload_datasource_file: string }>(
          gql`
            mutation ($filename: String!, $payload: String!) {
              upload_datasource_file(filename: $filename, payload: $payload)
            }
          `,
          { filename: files[0].name, payload: fr.result },
        )
        .toPromise()

      if (error || !data) {
        alert(`Error uploading file: ${files[0].name}`)
      } else {
        value = data.upload_datasource_file
      }
    }
    fr.readAsDataURL(files[0])
  }
</script>

{#if value}
  <div class="flex w-full justify-between">
    <div>
      <a
        href="{import.meta.env.VITE_MEDIA_URL}{value}"
        target="_blank"
        rel="noreferrer"
      >
        <FilePdfIcon />
        {value.replace("uploads/", "")}
      </a>
      <br />
      {$_("Change")}:
      <input type="file" on:change={uploadFile} {accept} />
    </div>

    <button class="btn btn-danger" on:click|preventDefault={removeFile}>
      {$_("Remove this file")}
    </button>
  </div>
{:else}
  <input type="file" on:change={uploadFile} {accept} />
{/if}
<small class="block pt-2 text-gray-500">{$_("Maximum file size: 10MB")}</small>
