// frontend/src/components/Fields/Edit/JSONDateAreaChoicesField.vue
<template>
  <div class="nowrap">
    <table class="w-100">
      <thead>
        <tr>
          <th>Current</th>
          <th>Date</th>
          <th>Area (ha)</th>
          <th>Choices</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(val, i) in vals" :key="i" :class="{ 'is-current': val.current }">
          <td class="text-center" @click="updateCurrent(i)">
            <div class="form-check form-check-inline">
              <input
                :id="`${formfield.name}_current_${i}`"
                v-model="current"
                :name="`${formfield.name}_current`"
                :required="
                  vals.length > 0 && (vals[0].date || vals[0].area || vals[0].choices)
                "
                class="form-check-input"
                type="radio"
                :value="i"
              />
            </div>
          </td>
          <td>
            <LowLevelDateYearField
              v-model="val.date"
              :required="formfield.required"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.area"
              :required="formfield.required"
              unit="ha"
              @input="updateEntries"
            />
          </td>

          <td>
            <multiselect
              v-model="val.choices"
              :options="options"
              :placeholder="formfield.placeholder"
              :group-select="true"
              :multiple="true"
              :group-values="formfield.with_categories ? 'options' : null"
              :group-label="formfield.with_categories ? 'category' : null"
              :custom-label="(x) => labels[x]"
              :close-on-select="false"
              @input="updateEntries"
            />
          </td>

          <td class="buttons">
            <a class="btn" @click.stop="addEntry"><i class="fa fa-plus"></i></a>
            <a
              :class="{ disabled: vals.length <= 1 }"
              class="btn"
              @click.stop="removeEntry(i)"
            >
              <i class="fa fa-minus"></i
            ></a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";
  import LowLevelDateYearField from "./LowLevelDateYearField";
  import LowLevelDecimalField from "./LowLevelDecimalField";

  export default {
    components: { LowLevelDateYearField, LowLevelDecimalField },
    mixins: [JSONFieldMixin],
    data() {
      return {
        options: [],
        labels: {},
      };
    },
    computed: {
      filteredVals() {
        return this.vals.filter((x) => x.date || x.area || x.choices);
      },
    },
    created() {
      if (this.formfield.with_categories) {
        this.options = Object.entries(this.formfield.choices).map(([k, v]) => {
          let newopts = Object.entries(v).map(([h, j]) => {
            this.labels[h] = this.$t(j);
            return h;
          });
          return { category: k, options: newopts };
        });
      } else {
        this.options = Object.entries(this.formfield.choices).map(([k, v]) => {
          this.labels[k] = this.$t(v);
          return k;
        });
      }
    },
  };
</script>

<style lang="scss" scoped>
  th {
    text-align: center;
  }
  td {
    padding: 0.4em;
  }
</style>

// frontend/src/components/Fields/Edit/JSONDateAreaChoicesField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import { createValueCopy, syncValue } from "$components/Fields/JSONField"
  import MinusIcon from "$components/icons/MinusIcon.svelte"
  import PlusIcon from "$components/icons/PlusIcon.svelte"

  import type { FormField } from "../fields"
  import LowLevelDateYearField from "./LowLevelDateYearField.svelte"
  import LowLevelDecimalField from "./LowLevelDecimalField.svelte"
  import TypedChoicesField from "./TypedChoicesField.svelte"

  interface JSONDateAreaChoicesField {
    date?: string
    area?: number
    choices?: string[]
    current?: boolean
  }

  export let formfield: FormField
  export let value: Array<JSONDateAreaChoicesField> | null

  let valueCopy = createValueCopy(value)
  $: value = syncValue(val => !!val.choices, valueCopy)

  function addEntry() {
    valueCopy = [...valueCopy, {}]
  }

  function removeEntry(index) {
    valueCopy = valueCopy.filter((val, i) => i !== index)
  }

  const anySelectedAsCurrent = values => values.some(val => val.current)
  const isCurrentRequired = values => values.length > 0 && !anySelectedAsCurrent(values)
</script>

<div class="json_date_area_field whitespace-nowrap">
  <table class="w-full">
    <thead>
      <tr>
        <th class="pr-2 text-center font-normal">{$_("Current")}</th>
        <th class="font-normal">{$_("Date")}</th>
        <th class="font-normal">{$_("Area (ha)")}</th>
        <th class="font-normal">{$_("Choices")}</th>
        <th />
      </tr>
    </thead>
    <tbody>
      {#each valueCopy as val, i}
        <tr class:is-current={val.current}>
          <td class="p-1 text-center">
            <input
              type="checkbox"
              bind:checked={val.current}
              name="{formfield.name}_{i}_current"
              required={isCurrentRequired(valueCopy)}
              disabled={!val.choices}
            />
          </td>

          <td class="w-1/4 p-1">
            <LowLevelDateYearField
              bind:value={val.date}
              name="{formfield.name}_{i}_date"
            />
          </td>

          <td class="w-1/4 p-1">
            <LowLevelDecimalField
              bind:value={val.area}
              unit="ha"
              name="{formfield.name}_{i}_area"
            />
          </td>
          <td class="w-2/4">
            <TypedChoicesField
              bind:value={val.choices}
              formfield={{ ...formfield, name: `${formfield.name}_${i}_choices` }}
              required={val.date || val.area}
            />
          </td>
          <td class="p-1">
            <button type="button" on:click={addEntry}>
              <PlusIcon class="h-5 w-5 text-black" />
            </button>
            <button
              type="button"
              disabled={valueCopy.length <= 1}
              on:click={() => removeEntry(i)}
            >
              <MinusIcon class="h-5 w-5 text-red-600" />
            </button>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>
