// frontend/src/components/Fields/Edit/JSONLeaseField.vue
<template>
  <div class="whitespace-nowrap">
    <table class="w-100">
      <thead>
        <tr>
          <th>Current</th>
          <th>Date</th>
          <th>Area (ha)</th>
          <th>Farmers</th>
          <th>Households</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(val, i) in vals" :key="i" :class="{ 'is-current': val.current }">
          <td class="text-center" @click="updateCurrent(i)">
            <div class="form-check form-check-inline">
              <input
                :id="`${formfield.name}_current_${i}`"
                v-model="current"
                :name="`${formfield.name}_current`"
                :required="
                  vals.length > 0 &&
                  (vals[0].date ||
                    vals[0].area ||
                    vals[0].farmers ||
                    vals[0].households)
                "
                class="form-check-input"
                type="radio"
                :value="i"
              />
            </div>
          </td>
          <td>
            <LowLevelDateYearField
              v-model="val.date"
              :required="formfield.required"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.area"
              :required="formfield.required"
              unit="ha"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.farmers"
              :required="formfield.required"
              :decimals="0"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.households"
              :required="formfield.required"
              :decimals="0"
              @input="updateEntries"
            />
          </td>

          <td class="buttons">
            <a class="btn" @click.stop="addEntry"><i class="fa fa-plus"></i></a>
            <a
              :class="{ disabled: vals.length <= 1 }"
              class="btn"
              @click.stop="removeEntry(i)"
            >
              <i class="fa fa-minus"></i
            ></a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";
  import LowLevelDateYearField from "./LowLevelDateYearField";
  import LowLevelDecimalField from "./LowLevelDecimalField";

  export default {
    components: { LowLevelDateYearField, LowLevelDecimalField },
    mixins: [JSONFieldMixin],
    computed: {
      filteredVals() {
        return this.vals.filter((x) => x.date || x.area || x.farmers || x.households);
      },
    },
  };
</script>

<style lang="scss" scoped>
  th {
    text-align: center;
  }
  td {
    padding: 0.4em;
  }
</style>

// frontend/src/components/Fields/Edit/JSONLeaseField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import { createValueCopy, syncValue } from "$components/Fields/JSONField"
  import MinusIcon from "$components/icons/MinusIcon.svelte"
  import PlusIcon from "$components/icons/PlusIcon.svelte"

  import type { FormField } from "../fields"
  import LowLevelDateYearField from "./LowLevelDateYearField.svelte"
  import LowLevelDecimalField from "./LowLevelDecimalField.svelte"

  interface JSONLeaseField {
    date?: string
    area?: number
    farmers?: number
    households?: number
    current?: boolean
  }

  export let formfield: FormField
  export let value: Array<JSONLeaseField> | null

  let valueCopy = createValueCopy(value)
  let current = valueCopy.map(val => val.current).indexOf(true) ?? -1
  $: value = syncValue(val => !!(val.area || val.farmers || val.households), valueCopy)

  function updateCurrent(index) {
    valueCopy = valueCopy.map(val => ({ ...val, current: undefined }))
    valueCopy[index].current = true
    valueCopy = valueCopy
  }

  function addEntry() {
    valueCopy = [...valueCopy, {}]
  }

  function removeEntry(index) {
    if (current === index) {
      current = -1
    } else if (current > index) {
      current--
    }
    valueCopy = valueCopy.filter((val, i) => i !== index)
  }
</script>

<div class="json_date_area_field whitespace-nowrap">
  <table class="w-full">
    <thead>
      <tr>
        <th class="pr-2 text-center font-normal">{$_("Current")}</th>
        <th class="font-normal">{$_("Date")}</th>
        <th class="font-normal">{$_("Area (ha)")}</th>
        <th class="font-normal">{$_("Farmers")}</th>
        <th class="font-normal">{$_("Households")}</th>
      </tr>
    </thead>
    <tbody>
      {#each valueCopy as val, i}
        <tr class:is-current={val.current}>
          <td class="text-center" on:click={() => updateCurrent(i)}>
            <input
              type="radio"
              bind:group={current}
              name="{formfield.name}_current"
              required={valueCopy.length > 0}
              disabled={!val.area && !val.farmers && !val.households}
              value={i}
            />
          </td>

          <td class="w-1/3 p-1">
            <LowLevelDateYearField
              bind:value={val.date}
              name="{formfield.name}_{i}_date"
            />
          </td>

          <td class="w-1/3 p-1">
            <LowLevelDecimalField
              bind:value={val.area}
              required={val.date && !(val.farmers || val.households)}
              unit="ha"
              name="{formfield.name}_{i}_area"
            />
          </td>
          <td class="w-1/3 p-1">
            <LowLevelDecimalField
              bind:value={val.farmers}
              required={val.date && !(val.households || val.area)}
              decimals={0}
              min={0}
              name="{formfield.name}_{i}_farmers"
            />
          </td>
          <td class="w-1/3 p-1">
            <LowLevelDecimalField
              bind:value={val.households}
              required={val.date && !(val.area || val.farmers)}
              decimals={0}
              min={0}
              name="{formfield.name}_{i}_households"
            />
          </td>

          <td class="p-1">
            <button type="button" on:click={addEntry}>
              <PlusIcon class="h-5 w-5 text-black" />
            </button>
            <button
              type="button"
              disabled={valueCopy.length <= 1}
              on:click={() => removeEntry(i)}
            >
              <MinusIcon class="h-5 w-5 text-red-600" />
            </button>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>
