// newfront/src/components/Fields/Edit/JSONDateAreaChoicesField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import MinusIcon from "$components/icons/MinusIcon.svelte";
  import PlusIcon from "$components/icons/PlusIcon.svelte";
  import type { FormField } from "../fields";
  import LowLevelDateYearField from "./LowLevelDateYearField.svelte";
  import LowLevelDecimalField from "./LowLevelDecimalField.svelte";
  import TypedChoicesField from "./TypedChoicesField.svelte";

  interface JSONDateAreaChoicesField {
    date?: string;
    area?: number;
    choices?: string;
  }

  export let formfield: FormField;
  export let value: Array<JSONDateAreaChoicesField>;
  // let current = value?.map((val) => val.current)?.indexOf(true) ?? -1;

  // create valueCopy to avoid overwriting null in db by [] or so
  let valueCopy: Array<JSONDateAreaChoicesField> = JSON.parse(
    JSON.stringify(value ?? [{}])
  );
  $: filteredValueCopy = valueCopy.filter((val) => val.date || val.area || val.choices);
  $: value = filteredValueCopy.length > 0 ? filteredValueCopy : null;

  function addEntry() {
    valueCopy = [...valueCopy, {}];
  }

  function removeEntry(index) {
    valueCopy = valueCopy.filter((val, i) => i == index);
  }
</script>

<div class="json_date_area_field whitespace-nowrap">
  <table class="w-full">
    <thead>
      <tr>
        <th>{$_("Current")}</th>
        <th>{$_("Date")}</th>
        <th>{$_("Area (ha)")}</th>
        <th>{$_("Choices")}</th>
        <th />
      </tr>
    </thead>
    <tbody>
      {#each valueCopy as val, i}
        <tr class:is-current={val.current}>
          <td class="text-center p-1">
            <input
              type="checkbox"
              bind:checked={val.current}
              name="{formfield.name}_current"
              required={valueCopy.length > 0}
              disabled={!val.date && !val.area && !val.choices}
            />
          </td>

          <td class="w-1/4 p-1">
            <LowLevelDateYearField
              bind:value={val.date}
              required={formfield.required}
            />
          </td>

          <td class="w-1/4 p-1">
            <LowLevelDecimalField
              bind:value={val.area}
              required={formfield.required}
              unit="ha"
            />
          </td>
          <td class="w-2/4">
            <TypedChoicesField bind:value={val.choices} {formfield} />
          </td>
          <td class="p-1">
            <button type="button" on:click={addEntry}>
              <PlusIcon class="w-5 h-5 text-black" />
            </button>
            <button
              type="button"
              disabled={valueCopy.length <= 1}
              on:click={() => removeEntry(i)}
            >
              <MinusIcon class="w-5 h-5 text-red-600" />
            </button>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// frontend/src/components/Fields/Edit/JSONDateAreaChoicesField.vue
<template>
  <div class="nowrap">
    <table class="w-100">
      <thead>
        <tr>
          <th>Current</th>
          <th>Date</th>
          <th>Area (ha)</th>
          <th>Choices</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(val, i) in vals" :key="i" :class="{ 'is-current': val.current }">
          <td class="text-center" @click="updateCurrent(i)">
            <div class="form-check form-check-inline">
              <input
                :id="`${formfield.name}_current_${i}`"
                v-model="current"
                class="form-check-input"
                type="radio"
                :name="`${formfield.name}_current`"
                :value="i"
              />
            </div>
          </td>
          <td>
            <LowLevelDateYearField
              v-model="val.date"
              :name="formfield.name"
              :required="formfield.required"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.area"
              :name="formfield.name"
              :required="formfield.required"
              unit="ha"
              @input="updateEntries"
            />
          </td>

          <td>
            <multiselect
              v-model="val.choices"
              :options="options"
              :placeholder="formfield.placeholder"
              :group-select="true"
              :multiple="true"
              :group-values="formfield.with_categories ? 'options' : null"
              :group-label="formfield.with_categories ? 'category' : null"
              :custom-label="(x) => labels[x]"
              :close-on-select="false"
              @input="updateEntries"
            />
          </td>

          <td>
            <a class="btn" @click.stop="addEntry"><i class="fa fa-plus"></i></a>
            <a
              :class="{ disabled: vals.length <= 1 }"
              class="btn"
              @click.stop="removeEntry(i)"
            >
              <i class="fa fa-minus"></i
            ></a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";
  import LowLevelDateYearField from "./LowLevelDateYearField";
  import LowLevelDecimalField from "./LowLevelDecimalField";

  export default {
    components: { LowLevelDateYearField, LowLevelDecimalField },
    mixins: [JSONFieldMixin],
    data() {
      return {
        current: -1,
        vals: this.value
          ? JSON.parse(JSON.stringify(this.value))
          : [{ date: null, area: null, choices: [], current: true }],
        options: [],
        labels: {},
      };
    },
    created() {
      if (this.value) {
        this.current = this.value.map((e) => e.current).indexOf(true);
      }
      if (this.formfield.with_categories) {
        this.options = Object.entries(this.formfield.choices).map(([k, v]) => {
          let newopts = Object.entries(v).map(([h, j]) => {
            this.labels[h] = this.$t(j);
            return h;
          });
          return { category: k, options: newopts };
        });
      } else {
        this.options = Object.entries(this.formfield.choices).map(([k, v]) => {
          this.labels[k] = this.$t(v);
          return k;
        });
      }
    },
    methods: {
      updateCurrent(i) {
        this.current = i;
        this.updateEntries();
      },
      updateEntries() {
        this.vals = this.vals.map((v, i) => {
          let current = i === this.current ? { current: true } : {};
          delete v.current;
          return { ...v, ...current };
        });
        this.$emit(
          "input",
          this.vals.filter((x) => x.current || x.date || x.area || x.choices)
        );
      },
      addEntry() {
        this.vals.push({ date: null, area: null, choices: [] });
        this.updateEntries();
      },
      removeEntry(index) {
        this.current = Math.min(this.current, this.vals.length - 2);
        this.vals.splice(index, 1);
        this.updateEntries();
      },
    },
  };
</script>

<style lang="scss" scoped>
  @import "../../../scss/colors";

  th {
    text-align: center;
  }
  td {
    padding: 0.4em;
  }

  .is-current {
    font-weight: bold;
    background: rgba($primary, 0.5);
    border-radius: 3px;
  }
</style>
