// newfront/src/components/Fields/Edit/JSONExportsField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import MinusIcon from "$components/icons/MinusIcon.svelte";
  import PlusIcon from "$components/icons/PlusIcon.svelte";
  import type { FormField } from "../fields";
  import LowLevelDateYearField from "./LowLevelDateYearField.svelte";
  import LowLevelDecimalField from "./LowLevelDecimalField.svelte";
  import TypedChoiceField from "./TypedChoiceField.svelte";

  interface JSONExportsField {
    date?: string;
    area?: number;
    choices?: string;
    yield?: number;
    export?: number;
    current?: boolean;
  }

  export let formfield: FormField;
  export let value: Array<JSONExportsField>;
  // let current = value?.map((val) => val.current)?.indexOf(true) ?? -1;

  // create valueCopy to avoid overwriting null in db by [] or so
  let valueCopy: Array<JSONExportsField> = JSON.parse(JSON.stringify(value ?? [{}]));
  $: filteredValueCopy = valueCopy.filter(
    (val) => val.date || val.area || val.choices || val.yield || val.export
  );
  $: value = filteredValueCopy.length > 0 ? filteredValueCopy : null;

  function addEntry() {
    valueCopy = [...valueCopy, {}];
  }
  function removeEntry(index) {
    valueCopy = valueCopy.filter((val, i) => i == index);
  }
</script>

<div class="json_date_area_field whitespace-nowrap">
  {JSON.stringify(value)}
  <table class="w-full">
    <thead>
      <tr>
        <th>{$_("Current")}</th>
        <th>{$_("Date")}</th>
        <th>{$_("Area (ha)")}</th>
        <th>{$_("Choices")}</th>
        <th>{$_("Yield(tons)")}</th>
        <th>{$_("Export(%)")}</th>
        <th />
      </tr>
    </thead>
    <tbody>
      {#each valueCopy as val, i}
        <tr class:is-current={val.current}>
          <td class="text-center p-1">
            <input
              type="checkbox"
              bind:checked={val.current}
              name="{formfield.name}_current"
              required={valueCopy.length > 0}
              disabled={!val.date &&
                !val.area &&
                !val.choices &&
                !val.yield &&
                !val.export}
            />
          </td>

          <td class="w-1/5 p-1">
            <LowLevelDateYearField
              bind:value={val.date}
              required={formfield.required}
            />
          </td>
          <td class="w-1/5 p-1">
            <LowLevelDecimalField
              bind:value={val.area}
              required={formfield.required}
              unit="ha"
            />
          </td>
          <td class="w-1/5 p-1">
            <TypedChoiceField bind:value={val.choices} {formfield} />
          </td>
          <td class="w-1/5 p-1">
            <LowLevelDecimalField
              bind:value={val.yield}
              required={formfield.required}
              unit="tons"
            />
          </td>
          <td class="w-1/5 p-1">
            <LowLevelDecimalField
              bind:value={val.export}
              required={formfield.required}
              unit="%"
              max="100"
            />
          </td>

          <td class="p-1">
            <button type="button" on:click={addEntry}>
              <PlusIcon class="w-5 h-5 text-black" />
            </button>
            <button
              type="button"
              disabled={valueCopy.length <= 1}
              on:click={() => removeEntry(i)}
            >
              <MinusIcon class="w-5 h-5 text-red-600" />
            </button>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// frontend/src/components/Fields/Edit/JSONExportsField.vue
<template>
  <div class="whitespace-nowrap">
    <table class="w-100">
      <thead>
        <tr>
          <th>Current</th>
          <th>Date</th>
          <th>Choices</th>
          <th>Area (ha)</th>
          <th>Yield (tons)</th>
          <th>Export (%)</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(val, i) in vals" :key="i" :class="{ 'is-current': val.current }">
          <td class="text-center" @click="updateCurrent(i)">
            <div class="form-check form-check-inline">
              <input
                :id="`${formfield.name}_current_${i}`"
                v-model="current"
                class="form-check-input"
                type="radio"
                :name="`${formfield.name}_current`"
                :required="
                  vals.length > 0 &&
                  (vals[0].date ||
                    vals[0].area ||
                    vals[0].yield ||
                    vals[0].export ||
                    vals[0].choices)
                "
                :value="i"
              />
            </div>
          </td>
          <td>
            <LowLevelDateYearField
              v-model="val.date"
              :required="formfield.required"
              @input="updateEntries"
            />
          </td>
          <td>
            <multiselect
              v-model="val.choices"
              :options="options"
              :placeholder="formfield.placeholder"
              :group-select="true"
              :multiple="true"
              :custom-label="(x) => labels[x]"
              :close-on-select="false"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.area"
              :required="formfield.required"
              unit="ha"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.yield"
              :required="formfield.required"
              unit="tons"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.export"
              :required="formfield.required"
              :max-value="100"
              unit="%"
              @input="updateEntries"
            />
          </td>

          <td class="buttons">
            <a class="btn" @click.stop="addEntry"><i class="fa fa-plus"></i></a>
            <a
              :class="{ disabled: vals.length <= 1 }"
              class="btn"
              @click.stop="removeEntry(i)"
            >
              <i class="fa fa-minus"></i
            ></a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";
  import LowLevelDateYearField from "./LowLevelDateYearField";
  import LowLevelDecimalField from "./LowLevelDecimalField";

  export default {
    components: { LowLevelDateYearField, LowLevelDecimalField },
    mixins: [JSONFieldMixin],
    data() {
      return {
        options: [],
        labels: {},
      };
    },

    computed: {
      filteredVals() {
        return this.vals.filter(
          (x) => x.date || x.area || x.yield || x.export || x.choices
        );
      },
    },
    created() {
      this.options = Object.entries(this.formfield.choices).map(([k, v]) => {
        this.labels[k] = this.$t(v);
        return k;
      });
    },
  };
</script>
