// newfront/src/components/Fields/Edit/JSONJobsField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import { createValueCopy, syncValue } from "$components/Fields/JSONField";
  import MinusIcon from "$components/icons/MinusIcon.svelte";
  import PlusIcon from "$components/icons/PlusIcon.svelte";
  import type { FormField } from "../fields";
  import LowLevelDateYearField from "./LowLevelDateYearField.svelte";
  import LowLevelDecimalField from "./LowLevelDecimalField.svelte";

  interface JSONJobsField {
    date?: string;
    jobs?: string;
    employees?: string;
    workers?: string;
    current?: boolean;
  }

  export let formfield: FormField;
  export let value: Array<JSONJobsField> | null;

  let valueCopy = createValueCopy(value);
  let current = valueCopy.map((val) => val.current).indexOf(true) ?? -1;
  $: value = syncValue(
    (val) => !!(val.date || val.jobs || val.employees || val.workers),
    valueCopy
  );

  function updateCurrent(index) {
    valueCopy = valueCopy.map((val) => ({ ...val, current: undefined }));
    valueCopy[index].current = true;
    valueCopy = valueCopy;
  }
  function addEntry() {
    valueCopy = [...valueCopy, {}];
  }
  function removeEntry(index) {
    if (current === index) {
      current = -1;
    } else if (current > index) {
      current--;
    }
    valueCopy = valueCopy.filter((val, i) => i !== index);
  }
</script>

<div class="json_date_area_field whitespace-nowrap">
  <table class="w-full">
    <thead>
      <tr>
        <th class="font-normal">{$_("Current")}</th>
        <th class="font-normal">{$_("Date")}</th>
        <th class="font-normal">{$_("Jobs")}</th>
        <th class="font-normal">{$_("Employees")}</th>
        <th class="font-normal">{$_("Workers")}</th>
        <th />
      </tr>
    </thead>
    <tbody>
      {#each valueCopy as val, i}
        <tr class:is-current={val.current}>
          <td class="text-center p-1" on:click={() => updateCurrent(i)}>
            <input
              type="radio"
              bind:group={current}
              name="{formfield.name}_current"
              required={valueCopy.length > 0}
              disabled={!val.date &&
                !val.area &&
                !val.jobs &&
                !val.employees &&
                !val.workers}
              value={i}
            />
          </td>

          <td class="w-1/4 p-1">
            <LowLevelDateYearField
              bind:value={val.date}
              required={formfield.required}
              name={formfield.name}
            />
          </td>

          <td class="w-1/4 p-1">
            <LowLevelDecimalField
              bind:value={val.jobs}
              required={formfield.required}
              name={formfield.name}
              decimals=""
              unit=""
            />
          </td>
          <td class="w-1/4 p-1">
            <LowLevelDecimalField
              bind:value={val.employees}
              required={formfield.required}
              name={formfield.name}
              decimals=""
              unit=""
            />
          </td>
          <td class="w-1/4 p-1">
            <LowLevelDecimalField
              bind:value={val.workers}
              required={formfield.required}
              name={formfield.name}
              decimals=""
              unit=""
            />
          </td>

          <td class="p-1">
            <button type="button" on:click={addEntry}>
              <PlusIcon class="w-5 h-5 text-black" />
            </button>
            <button
              type="button"
              disabled={valueCopy.length <= 1}
              on:click={() => removeEntry(i)}
            >
              <MinusIcon class="w-5 h-5 text-red-600" />
            </button>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// frontend/src/components/Fields/Edit/JSONJobsField.vue
<template>
  <div class="whitespace-nowrap">
    <table class="w-100">
      <thead>
        <tr>
          <th>{{ $t("Current") }}</th>
          <th>{{ $t("Date") }}</th>
          <th>{{ $t("Jobs") }}</th>
          <th>{{ $t("Employees") }}</th>
          <th>{{ $t("Workers") }}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(val, i) in vals" :key="i" :class="{ 'is-current': val.current }">
          <td class="text-center" @click="updateCurrent(i)">
            <div class="form-check form-check-inline">
              <input
                :id="`${formfield.name}_current_${i}`"
                v-model="current"
                :name="`${formfield.name}_current`"
                :required="
                  vals.length > 0 &&
                  (vals[0].date || vals[0].jobs || vals[0].employees || vals[0].workers)
                "
                class="form-check-input"
                type="radio"
                :value="i"
              />
            </div>
          </td>
          <td>
            <LowLevelDateYearField
              v-model="val.date"
              :required="formfield.required"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.jobs"
              :required="formfield.required"
              :decimals="0"
              :min-value="0"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.employees"
              :required="formfield.required"
              :decimals="0"
              :min-value="0"
              @input="updateEntries"
            />
          </td>
          <td>
            <LowLevelDecimalField
              v-model="val.workers"
              :required="formfield.required"
              :decimals="0"
              :min-value="0"
              @input="updateEntries"
            />
          </td>

          <td class="buttons">
            <a class="btn" @click.stop="addEntry"><i class="fa fa-plus"></i></a>
            <a
              :class="{ disabled: vals.length <= 1 }"
              class="btn"
              @click.stop="removeEntry(i)"
            >
              <i class="fa fa-minus"></i
            ></a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";
  import LowLevelDateYearField from "./LowLevelDateYearField";
  import LowLevelDecimalField from "./LowLevelDecimalField";

  export default {
    components: { LowLevelDateYearField, LowLevelDecimalField },
    mixins: [JSONFieldMixin],
    computed: {
      filteredVals() {
        return this.vals.filter((x) => x.date || x.jobs || x.employees || x.workers);
      },
    },
  };
</script>
