// frontend/src/components/Fields/Edit/JSONDateChoiceField.vue
<template>
  <div class="whitespace-nowrap">
    <table class="w-100">
      <thead>
        <tr>
          <th>Current</th>
          <th>Date</th>
          <th>Choice</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(val, i) in vals" :key="i" :class="{ 'is-current': val.current }">
          <td class="text-center" @click="updateCurrent(i)">
            <div class="form-check form-check-inline">
              <input
                :id="`${formfield.name}_current_${i}`"
                v-model="current"
                :name="`${formfield.name}_current`"
                :required="vals.length > 0 && (vals[0].date || vals[0].choice)"
                class="form-check-input"
                type="radio"
                :value="i"
              />
            </div>
          </td>
          <td>
            <LowLevelDateYearField
              v-model="val.date"
              :required="formfield.required"
              @input="updateEntries"
            />
          </td>
          <td>
            <multiselect
              v-model="val.choice"
              :options="options"
              :placeholder="formfield.placeholder"
              :group-select="true"
              :custom-label="(x) => labels[x]"
              select-label=""
              @input="updateEntries"
            />
          </td>

          <td class="buttons">
            <a class="btn" @click.stop="addEntry"><i class="fa fa-plus"></i></a>
            <a
              :class="{ disabled: vals.length <= 1 }"
              class="btn"
              @click.stop="removeEntry(i)"
            >
              <i class="fa fa-minus"></i
            ></a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import JSONFieldMixin from "../JSONFieldMixin";
  import LowLevelDateYearField from "./LowLevelDateYearField";

  export default {
    components: { LowLevelDateYearField },
    mixins: [JSONFieldMixin],
    data() {
      return {
        options: [],
        labels: {},
      };
    },
    computed: {
      filteredVals() {
        return this.vals.filter((x) => x.date || x.choice);
      },
    },
    created() {
      this.options = Object.entries(this.formfield.choices).map(([k, v]) => {
        this.labels[k] = this.$t(v);
        return k;
      });
    },
  };
</script>

// frontend/src/components/Fields/Edit/JSONDateChoiceField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import { createValueCopy, syncValue } from "$components/Fields/JSONField"
  import MinusIcon from "$components/icons/MinusIcon.svelte"
  import PlusIcon from "$components/icons/PlusIcon.svelte"

  import type { FormField } from "../fields"
  import LowLevelDateYearField from "./LowLevelDateYearField.svelte"
  import TypedChoiceField from "./TypedChoiceField.svelte"

  interface JSONDateChoiceField {
    date?: string
    choice?: string
    current?: boolean
  }

  export let formfield: FormField
  export let value: Array<JSONDateChoiceField> | null

  let valueCopy = createValueCopy(value)
  let current = valueCopy.map(val => val.current).indexOf(true) ?? -1
  $: value = syncValue(val => !!val.choice, valueCopy)

  function updateCurrent(index) {
    valueCopy = valueCopy.map(val => ({ ...val, current: undefined }))
    valueCopy[index].current = true
    valueCopy = valueCopy
  }
  function addEntry() {
    valueCopy = [...valueCopy, {}]
  }
  function removeEntry(index) {
    if (current === index) {
      current = -1
    } else if (current > index) {
      current--
    }
    valueCopy = valueCopy.filter((val, i) => i !== index)
  }
</script>

<div class="json_date_choice_field whitespace-nowrap">
  <table class="w-full">
    <thead>
      <tr>
        <th class="pr-2 text-center font-normal">{$_("Current")}</th>
        <th class="font-normal">{$_("Date")}</th>
        <th class="font-normal">{$_("Choice")}</th>
        <th />
      </tr>
    </thead>
    <tbody>
      {#each valueCopy as val, i}
        <tr class:is-current={val.current}>
          <td class="p-1 text-center" on:click={() => updateCurrent(i)}>
            <input
              type="radio"
              bind:group={current}
              name="{formfield.name}_current"
              required={valueCopy.length > 0}
              disabled={!val.choice}
              value={i}
            />
          </td>
          <td class="w-1/4 p-1">
            <LowLevelDateYearField
              bind:value={val.date}
              name="{formfield.name}_{i}_date"
            />
          </td>
          <td class="w-3/4 p-1">
            <TypedChoiceField
              bind:value={val.choice}
              formfield={{ ...formfield, name: `${formfield.name}_${i}_choice` }}
              required={val.date}
            />
          </td>

          <td class="p-1">
            <button type="button" on:click={addEntry}>
              <PlusIcon class="h-5 w-5 text-black" />
            </button>
            <button
              type="button"
              disabled={valueCopy.length <= 1}
              on:click={() => removeEntry(i)}
            >
              <MinusIcon class="h-5 w-5 text-red-600" />
            </button>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>
