// newfront/src/components/Fields/Edit/LocationGoogleField.svelte
<script lang="ts">
  import { Loader } from "@googlemaps/js-api-loader?client";
  import { createEventDispatcher, onMount } from "svelte";
  import { _ } from "svelte-i18n";

  export let value = "";
  export let countryCode = "";

  let autocomplete;
  let inputField;

  const dispatch = createEventDispatcher();

  let loader: Loader;

  function locationAutocomplete() {
    if (!loader)
      loader = new Loader({
        apiKey: import.meta.env.VITE_GAPI_KEY,
        libraries: ["places"],
      });
    loader.load().then((google) => {
      autocomplete = new google.maps.places.Autocomplete(inputField, {
        fields: ["geometry"],
        strictBounds: true,
        componentRestrictions: countryCode ? { country: countryCode } : undefined,
      });
      autocomplete?.addListener("place_changed", () => {
        const geometry = autocomplete.getPlace().geometry;
        if (!geometry) return;
        dispatch("change", {
          latLng: [geometry.location?.lat(), geometry.location?.lng()],
          viewport: geometry.viewport,
        });
        value = inputField.value;
      });
    });
  }

  onMount(locationAutocomplete);
  // onDestroy(() => {
  //   console.log("onDestroy. loader", loader);
  // });
  //
  // afterUpdate(() => {
  //   console.log("afterUpdate. loader", loader);
  // });

  $: autocomplete?.setComponentRestrictions({ country: countryCode });
</script>

<div class="input-group">
  <input bind:this={inputField} bind:value placeholder={$_("Location")} class="inpt" />
  <!--  on:keydown|preventDefault=.enter.prevent=""-->
</div>

// frontend/src/components/Fields/Edit/LocationGoogleField.vue
<template>
  <div class="input-group">
    <input
      id="location-input"
      v-model="val"
      :placeholder="$t('Location')"
      :aria-label="$t('Location')"
      class="form-control"
      @keydown.enter.prevent=""
    />
  </div>
</template>

<script>
  import { Loader } from "@googlemaps/js-api-loader";

  const loader = new Loader({
    apiKey: import.meta.env.VITE_GAPI_KEY,
    libraries: ["places"],
  });

  export default {
    props: {
      value: { type: String, required: false, default: "" },
      countryCode: { type: String, required: false, default: "" },
    },
    data() {
      return { autocomplete: null };
    },
    computed: {
      val: {
        get() {
          return this.value;
        },
        set() {},
      },
    },
    watch: {
      countryCode(cCode) {
        this.autocomplete.setComponentRestrictions({ country: cCode });
      },
    },
    created() {
      this.$nextTick(() => {
        const input_field = document.getElementById("location-input");

        let opts = { fields: ["geometry"], strictBounds: true };
        if (this.countryCode)
          opts.componentRestrictions = { country: this.countryCode };

        loader.load().then(() => {
          // eslint-disable-next-line no-undef
          this.autocomplete = new google.maps.places.Autocomplete(input_field, opts);
          this.autocomplete.addListener("place_changed", () => {
            const geometry = this.autocomplete.getPlace().geometry;
            this.$emit("change", {
              latLng: [geometry.location.lat(), geometry.location.lng()],
              viewport: geometry.viewport,
            });
            this.$emit("input", input_field.value);
          });
        });
      });
    },
  };
</script>
