// frontend/src/components/Fields/Edit/LocationGoogleField.vue
<template>
  <div class="input-group">
    <input
      :id="`location-input-${randomhash}`"
      v-model="val"
      :placeholder="$t('Location')"
      :aria-label="$t('Location')"
      class="form-control"
      @keydown.enter.prevent=""
    />
  </div>
</template>

<script lang="ts">
  import { Loader } from "@googlemaps/js-api-loader";
  import Vue from "vue";

  const loader = new Loader({
    apiKey: import.meta.env.VITE_GAPI_KEY,
    libraries: ["places"],
  });

  export default Vue.extend({
    props: {
      value: { type: String, required: false, default: "" },
      countryCode: { type: String, required: false, default: "" },
    },
    data() {
      return {
        autocomplete: null as unknown,
        randomhash: Math.random().toString(36).substring(2),
      };
    },
    computed: {
      val: {
        get(): string {
          return this.value;
        },
        set(): void {},
      },
    },
    watch: {
      countryCode(cCode) {
        this.autocomplete.setComponentRestrictions({ country: cCode });
      },
    },
    created() {
      this.$nextTick(() => {
        const input_field = document.getElementById(
          `location-input-${this.randomhash}`
        ) as HTMLInputElement;
        if (!input_field) return;

        loader.load().then((google) => {
          const autocomplete = new google.maps.places.Autocomplete(input_field, {
            fields: ["geometry"],
            strictBounds: true,
            componentRestrictions: this.countryCode
              ? { country: this.countryCode }
              : undefined,
          });
          this.autocomplete = autocomplete;

          autocomplete?.addListener("place_changed", () => {
            const geometry = autocomplete.getPlace().geometry;
            if (!geometry) return;
            this.$emit("change", {
              latLng: [geometry.location?.lat(), geometry.location?.lng()],
              viewport: geometry.viewport,
            });
            this.$emit("input", input_field.value);
          });
        });
      });
    },
  });
</script>

// frontend/src/components/Fields/Edit/LocationGoogleField.svelte
<script lang="ts">
  import { Loader } from "@googlemaps/js-api-loader?client"
  import { createEventDispatcher, onMount } from "svelte"
  import { _ } from "svelte-i18n"

  export let value = ""
  export let countryCode = ""

  let autocomplete: google.maps.places.Autocomplete
  let inputField: HTMLInputElement

  const dispatch = createEventDispatcher()

  let apiKey = import.meta.env.VITE_GAPI_KEY
  let loader: Loader

  function locationAutocomplete() {
    if (!apiKey) return
    if (!loader)
      loader = new Loader({
        apiKey,
        libraries: ["places"],
      })
    loader.load().then(google => {
      // noinspection TypeScriptUnresolvedVariable,TypeScriptUnresolvedFunction
      autocomplete = new google.maps.places.Autocomplete(inputField, {
        fields: ["geometry"],
        strictBounds: true,
        componentRestrictions: countryCode ? { country: countryCode } : undefined,
      })
      autocomplete?.addListener("place_changed", () => {
        const geometry = autocomplete.getPlace().geometry
        if (!geometry) return
        dispatch("change", {
          latLng: [geometry.location?.lat(), geometry.location?.lng()],
          viewport: geometry.viewport,
        })
        value = inputField.value
      })
    })
  }

  onMount(locationAutocomplete)
  // onDestroy(() => {
  //   console.log("onDestroy. loader", loader);
  // });
  //
  // afterUpdate(() => {
  //   console.log("afterUpdate. loader", loader);
  // });

  $: autocomplete?.setComponentRestrictions({ country: countryCode })
</script>

<div class="input-group">
  <input bind:this={inputField} bind:value placeholder={$_("Location")} class="inpt" />
  <!--  on:keydown|preventDefault=.enter.prevent=""-->
</div>
