// newfront/src/components/Fields/Display/PointField.svelte
<script lang="ts">
  import type { FormField } from "$components/Fields/fields";

  export let formfield: FormField;
  export let value: object[];
  export let model: string;
</script>

<div class="point_field">
  {#if value.lat}
    <div>Lat: {parseFloat(value.lat.toFixed(8))}</div>
  {/if}
  {#if value.lng}
    <div>Lng: {parseFloat(value.lng.toFixed(8))}</div>{/if}
</div>

// frontend/src/components/Fields/Edit/PointField.vue
<template>
  <div>
    <div>
      Lat:
      <LowLevelDecimalField
        v-model="val.lat"
        :min-value="-90"
        :max-value="90"
        :decimals="8"
      />
    </div>
    <div>
      Lng:
      <LowLevelDecimalField
        v-model="val.lng"
        :min-value="-180"
        :max-value="180"
        :decimals="8"
      />
    </div>
  </div>
</template>

<script>
  import LowLevelDecimalField from "$components/Fields/Edit/LowLevelDecimalField";

  export default {
    components: { LowLevelDecimalField },
    props: {
      formfield: { type: Object, required: true },
      value: { type: Object, required: false, default: () => ({}) },
      model: { type: String, required: true },
    },
    data() {
      return {
        val: JSON.parse(JSON.stringify(this.value)),
      };
    },
    watch: {
      val: {
        deep: true,
        handler(v) {
          this.$emit("input", v);
          this.$store.dispatch("changeLocationPoint", v);
        },
      },
    },
  };
</script>
