// newfront/src/components/Fields/Edit/TextField.svelte
<script lang="ts">
  import type { FormField } from "../fields";

  export let formfield: FormField;
  export let value: string;
</script>

<div class="text_field">
  {#if formfield.class === "TextField"}
    <textarea
      bind:value
      placeholder={formfield.label}
      name={formfield.name}
      rows="5"
      class="inpt"
    />
  {:else if formfield.class === "URLField"}
    <input
      bind:value
      type="url"
      placeholder={formfield.label}
      name={formfield.name}
      maxlength={formfield.max_length}
    />
  {:else}
    <input
      bind:value
      type="text"
      placeholder={formfield.label}
      name={formfield.name}
      maxlength={formfield.max_length}
    />
  {/if}
</div>

// frontend/src/components/Fields/Edit/TextField.vue
<template>
  <div class="text_field">
    <div class="input-group">
      <!--        :id="`type-${formfield.name}`"-->
      <textarea
        v-if="formfield.class === 'TextField'"
        v-model="val"
        :placeholder="formfield.placeholder || formfield.label"
        :aria-label="formfield.placeholder || formfield.label"
        :name="formfield.name"
        rows="5"
        class="form-control"
      />
      <div v-else-if="formfield.choices" class="select">
        <select v-model="val" :name="formfield.name" class="form-control">
          <option v-if="!formfield.required" :value="null">--------</option>
          <option v-for="(v, k) in formfield.choices" :key="k" :value="k">
            {{ v }}
          </option>
        </select>
      </div>
      <input
        v-else
        v-model="val"
        :type="formfield.class === 'URLField' ? 'url' : formfield.type || 'text'"
        :placeholder="formfield.placeholder || formfield.label"
        :aria-label="formfield.placeholder || formfield.label"
        :name="formfield.name"
        class="form-control"
        :maxlength="formfield.max_length"
      />
    </div>
    <!--      <div v-if="formfield.unit" class="input-group-append">-->
    <!--        <span class="input-group-text">{{ formfield.unit }}</span>-->
    <!--      </div>-->
  </div>
</template>

<script>
  export default {
    props: {
      formfield: { type: Object, required: true },
      value: { type: String, required: false, default: "" },
      model: { type: String, required: true },
    },
    computed: {
      val: {
        get() {
          return this.value;
        },
        set(v) {
          this.$emit("input", v);
        },
      },
    },
  };
</script>
