// frontend/src/components/Deal/DealSubmodelSection.vue
<template>
  <section v-if="entries.length">
    <div class="d-flex">
      <div :class="wrapperClasses">
        <div v-for="(entry, index) in entries" :key="index" class="panel-body">
          <h3>
            {{ $t(modelName) }} <small>#{{ entry.id }}</small>
          </h3>
          <DisplayField
            v-for="fieldname in fields"
            :key="fieldname"
            :fieldname="fieldname"
            :value="entry[fieldname]"
            :model="model"
            :label-classes="labelClasses"
            :value-classes="valueClasses"
            :file-not-public="entry.file_not_public"
          />
        </div>
      </div>
      <slot />
    </div>
  </section>
</template>

<script lang="ts">
  import DisplayField from "$components/Fields/DisplayField.vue";
  import Vue from "vue";

  export default Vue.extend({
    components: { DisplayField },
    props: {
      model: { type: String, required: true },
      modelName: { type: String, required: true },
      entries: { type: Array, required: true },
      fields: { type: Array, required: true },
      labelClasses: {
        type: Array,
        default: () => ["display-field-label", "col-md-5", "col-lg-4"],
      },
      valueClasses: {
        type: Array,
        default: () => ["display-field-value", "col-md-7", "col-lg-8"],
      },
    },
    computed: {
      wrapperClasses() {
        if (this.$slots.default) return ["col-md-12", "col-lg-7", "col-xl-6"];
        else return ["w-100"];
      },
    },
  });
</script>

<style lang="scss" scoped>
  h3 small {
    font-size: 70%;
    color: #777;
  }
</style>

// newfront/src/components/Deal/DealSubmodelSection.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import { isEmpty } from "$lib/helpers";
  import DisplayField from "$components/Fields/DisplayField.svelte";

  export let model;
  export let modelName;
  export let entries = [];
  export let fields: string[];

  let wrapperClasses = $$slots.default ? "w-full lg:w-1/2" : "w-full";
</script>

{#if entries.length > 0}
  <section class="flex flex-wrap h-full">
    <div class={wrapperClasses}>
      {#each entries as entry, index}
        <div class="{model}-entry">
          <h3>
            {index + 1}. {$_(modelName)}
            <small class="text-sm text-gray-500">#{entry.id}</small>
          </h3>
          {#each fields as fieldname}
            {#if !isEmpty(entry[fieldname])}
              <DisplayField
                {fieldname}
                value={entry[fieldname]}
                {model}
                :file-not-public="entry.file_not_public"
              />
            {/if}
          {/each}
        </div>
      {/each}
    </div>
    <slot />
  </section>
{/if}
