// frontend/src/components/Deal/DealHistory.vue
<template>
  <div>
    <h3>History</h3>
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Created</th>
          <th v-if="user && user.is_authenticated">User</th>
          <th>Fully updated</th>
          <th>Status</th>
          <th>Comment</th>
          <th style="text-align: right;">
            Show / <a @click="compareVersions">Compare</a>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(version, i) in deal.versions" :key="i">
          <td>{{ version.revision.date_created | defaultdate }}</td>
          <td v-if="user && user.is_authenticated">
            {{ version.revision.user && version.revision.user.full_name }}
          </td>
          <td>
            <b-button
              v-b-tooltip.hover
              disabled
              :title="version.deal.fully_updated ? 'Fully updated' : 'Updated'"
              :class="[
                'fa',
                version.deal.fully_updated ? 'fa-check-circle' : 'fa-circle',
              ]"
            />
          </td>
          <td>
            {{ derive_status(version.deal.status, version.deal.draft_status) }}
          </td>
          <td>{{ version.revision.comment }}</td>
          <td style="white-space: nowrap; text-align: right;">
            <span v-if="i === deduced_position">Current</span>
            <span v-else>
              <router-link
                v-slot="{ href }"
                :to="{
                  name: 'deal_detail',
                  params: { dealId, dealVersion: version.revision.id },
                }"
              >
                <!-- this hack helps to understand that a new version is actually loading, atm -->
                <a :href="href">Show</a>
              </router-link>
            </span>
            <span class="ml-4" style="white-space: nowrap; text-align: right;">
              <input
                v-model="compare_from"
                type="radio"
                :value="version.revision.id"
                :disabled="version.revision.id >= compare_to"
              />

              <input
                v-model="compare_to"
                type="radio"
                :value="version.revision.id"
                :disabled="version.revision.id <= compare_from"
              />
            </span>
          </td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <button style="white-space: nowrap;" @click="compareVersions">
              Compare versions
            </button>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</template>

<script>
  import { mapState } from "vuex";

  export default {
    name: "DealHistory",
    props: ["deal", "dealId", "dealVersion"],
    data() {
      return {
        compare_from: null,
        compare_to: null,
      };
    },
    computed: {
      ...mapState({
        user: (state) => state.page.user,
      }),
      deduced_position() {
        if (this.deal.versions.length === 0) return 0;
        if (this.dealVersion) {
          return this.deal.versions.findIndex(
            (v) => +v.revision.id === +this.dealVersion
          );
        }
        for (const [i, v] of this.deal.versions.entries()) {
          if (v.deal.draft_status === null) return i;
        }
        return this.deal.versions.length - 1;
      },
    },
    mounted() {
      if (this.deal.versions.length >= 2) {
        this.compare_to = this.deal.versions[0].revision.id;
        this.compare_from = this.deal.versions[1].revision.id;
      }
    },
    methods: {
      derive_status(status, draft_status) {
        const status_map = {
          1: "Draft",
          2: "Live",
          3: "Updated",
          4: "Deleted",
        };
        const draft_status_map = {
          1: "Draft",
          2: "Review",
          3: "Activation",
          4: "Rejected",
          5: "To Delete",
        };

        if (draft_status) {
          return draft_status_map[draft_status];
        }

        let st = status_map[status];
        if (draft_status) {
          return `${st} + ${draft_status_map[draft_status]}`;
        }
        return st;
      },
      compareVersions() {
        this.$router.push({
          name: "deal_compare",
          params: {
            dealId: this.dealId,
            fromVersion: this.compare_from,
            toVersion: this.compare_to,
          },
        });
      },
    },
  };
</script>

// newfront/src/components/Deal/DealHistory.svelte
<script lang="ts">
  import dayjs from "dayjs";
  import { onMount } from "svelte";
  import { _ } from "svelte-i18n";
  import { page } from "$app/stores";
  import type { Deal, DealVersion } from "$lib/types/deal";

  export let deal: Deal;
  export let dealID: number;
  export let dealVersion: number;

  let compareFrom;
  let compareTo;

  onMount(() => {
    if (deal.versions?.length >= 2) {
      compareTo = deal.versions[0].id;
      compareFrom = deal.versions[1].id;
    }
  });

  function calcVersionList(versions: DealVersion[]) {
    versions = JSON.parse(JSON.stringify(versions));
    if (!$page.stuff.user.is_authenticated) {
      versions = versions.filter((v) => !(v.deal.confidential || v.deal.draft_status));
    }
    let currentActive = false;
    return versions.map((v) => {
      if (!v.deal.draft_status && !currentActive) {
        v.link = `/deal/${dealID}`;
        currentActive = true;
      } else v.link = `/deal/${dealID}/${v.id}`;
      return v;
    });
  }
  $: enriched_versions = calcVersionList(deal.versions ?? []);

  function calcDeducedPosition(versions) {
    if (versions.length === 0) return 0;
    if (dealVersion) {
      return versions.findIndex((v) => +v.id === +dealVersion);
    }
    for (const [i, v] of versions.entries()) {
      if (v.deal.draft_status === null) return i;
    }
    return versions.length - 1;
  }

  $: deduced_position = calcDeducedPosition(deal?.versions);

  const status_map = {
    1: "Draft",
    2: "Active", //"Live",
    3: "Active", // "Updated",
    4: "Deleted",
    5: "Rejected", // legacy
    6: "To Delete", // legacy
  };
  const draft_status_map = {
    1: "Draft",
    2: "Review",
    3: "Activation",
    4: "Rejected", // legacy
    5: "Deleted",
  };
  function derive_status(status, draft_status) {
    return draft_status ? draft_status_map[draft_status] : status_map[status];
  }
</script>

<div>
  <h3>{$_("Deal history")}</h3>
  <table class="table-auto w-full border-b-2 relative">
    <thead>
      <tr>
        <th>{$_("Created")}</th>
        {#if $page.stuff.user.is_authenticated} <th>{$_("User")}</th> {/if}
        <th>{$_("Fully updated")}</th>
        {#if $page.stuff.user.is_authenticated} <th>{$_("Status")}</th> {/if}
        <th class="text-right">
          {$_("Show")} /
          <a
            href={`/deal/${dealID}/compare/${compareFrom}/${compareTo}/`}
            class="text-nowrap"
          >
            {$_("Compare")}
          </a>
        </th>
      </tr>
    </thead>
    <tbody>
      {#each enriched_versions as version, i}
        <tr class="odd:bg-gray-100">
          <td>{dayjs(version.created_at).format("YYYY-MM-DD HH:mm")}</td>
          {#if $page.stuff.user.is_authenticated}
            <td>
              {version.created_by && version.created_by.full_name}
            </td>
          {/if}
          <td>
            <!--            <button-->
            <!--              disabled-->
            <!--              :title="version.deal.fully_updated ? 'Fully updated' : 'Updated'"-->
            <!--              :class="[-->
            <!--                'fa',-->
            <!--                version.deal.fully_updated ? 'fa-check-circle' : 'fa-circle',-->
            <!--              ]"-->
            <!--            />-->
          </td>
          {#if $page.stuff.user.is_authenticated}
            <td>
              {$_(derive_status(version?.deal?.status, version?.deal?.draft_status))}
            </td>
          {/if}
          <td class="text-right whitespace-nowrap">
            {#if i === deduced_position}
              {$_("Current")}
            {:else}
              <a href={version?.link}>{$_("Show")}</a>
            {/if}
            <span class="ml-4 text-right whitespace-nowrap">
              <input
                bind:group={compareFrom}
                type="radio"
                value={version?.id}
                disabled={version?.id >= compareTo}
              />

              <input
                bind:group={compareTo}
                type="radio"
                value={version?.id}
                disabled={version?.id <= compareFrom}
              />
            </span>
          </td>
        </tr>
      {/each}
    </tbody>
    <tfoot>
      <tr>
        <td />
        {#if $page.stuff.user.is_authenticated} <td /> {/if}
        <td />
        {#if $page.stuff.user.is_authenticated} <td /> {/if}
        {#if compareFrom && compareTo}
          <td>
            <a
              href={`/deal/${dealID}/compare/${compareFrom}/${compareTo}/`}
              class="btn btn-primary text-nowrap"
            >
              {$_("Compare versions")}
            </a>
          </td>
        {/if}
      </tr>
    </tfoot>
  </table>
</div>
