// frontend/src/components/Deal/DealEditSection.vue
<template>
  <b-tab :title="$t(title)" :active="active" @click="$emit('activated')">
    <div v-for="section in sections" :key="section.name" class="panel-body">
      <h3>{{ $t(section.name) }}</h3>
      <EditField
        v-for="fieldname in section.fields"
        :key="fieldname"
        :fieldname="fieldname"
        v-model="deal[fieldname]"
      />
    </div>

    <slot />
  </b-tab>
</template>

<script>
  import EditField from "components/Fields/EditField";

  export default {
    name: "DealEditSection",
    components: { EditField },
    props: {
      title: { type: String, required: true },
      sections: { type: Array, required: true },
      deal: { type: Object, required: true },
      active: { type: Boolean, default: false },
    },
    computed: {},
    methods: {},
  };
</script>

// newfront/src/components/Deal/DealEditSection.svelte
<script lang="ts">
  import type { Section } from "$lib/sections";
  import type { Deal } from "$lib/types/deal";
  import EditField from "$components/Fields/EditField.svelte";

  export let deal: Deal;
  export let sections: Section[] = [];
  export let id: string;
</script>

<section>
  <form {id}>
    {#each sections as subsection}
      <div class="mt-2 space-y-4">
        <h3 class="my-0">{subsection.name}</h3>
        {#each subsection.fields as fieldname}
          <EditField {fieldname} bind:value={deal[fieldname]} />
        {/each}
      </div>
    {/each}
    <slot />
  </form>
</section>
