// frontend/src/views/Login.vue
<template>
  <div class="login-wrapper">
    <div class="login-container">
      <form @submit.prevent="dispatchLogin">
        <label>
          Username
          <input
            v-model="username"
            class="form-control"
            type="text"
            autocomplete="username"
            placeholder="Username"
          />
        </label>
        <label>
          Password
          <input
            v-model="password"
            class="form-control"
            type="password"
            autocomplete="current-password"
            placeholder="Password"
          />
        </label>
        <button type="submit" class="btn btn-primary">
          {{ $t("Login") }}
        </button>
        <p class="mt-3 text-danger small">{{ login_failed_message }}</p>
      </form>
    </div>
  </div>
</template>

<script>
  export default {
    name: "Login",
    data() {
      return {
        username: null,
        password: null,
        login_failed_message: "",
      };
    },
    computed: {},
    methods: {
      dispatchLogin() {
        this.$store
          .dispatch("login", { username: this.username, password: this.password })
          .then(() => {
            this.$router.push(this.$route.query.next);
          })
          .catch((response) => {
            this.login_failed_message = response.error;
          });
      },
    },
  };
</script>

<style scoped>
  .login-wrapper {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 60vh;
  }
  .login-container {
    width: 350px;

    background: #4b4b4b;
    color: white;
    padding: 1rem;
    border-radius: 3px;
  }
  label {
    display: block;
    margin-bottom: 1rem;
  }
  input {
    display: block;
  }
</style>

// newfront/src/routes/login.svelte
<script lang="ts">
  import { dispatchLogin, user } from "$lib/stores";
  import { _ } from "svelte-i18n";
  import { page } from "$app/stores";
  import { onMount } from "svelte";
  import { goto } from "$app/navigation";

  let username = "";
  let password = "";
  let login_failed_message = "";

  onMount(() => {
    const next = $page.url.searchParams.get("next");
    if ($user?.is_authenticated && next) {
      goto(next);
    }
  });
  async function login() {
    const res = await dispatchLogin(username, password);
    console.log(res);
    if (res.status === true) {
      console.log("juchu!");
    } else {
      login_failed_message = res.error;
    }
  }
</script>

<div class=" h-4/6 flex justify-center items-center">
  <div class="w-80 bg-neutral-600 text-white rounded p-4">
    <form on:submit|preventDefault={login}>
      <label class="block mb-4">
        Username
        <input
          bind:value={username}
          autocomplete="username"
          class="form-control"
          placeholder="Username"
          type="text"
        />
      </label>
      <label class="block mb-4">
        Password
        <input
          bind:value={password}
          autocomplete="current-password"
          class="form-control"
          placeholder="Password"
          type="password"
        />
      </label>
      <button class="btn btn-primary" type="submit">
        {$_("Login")}
      </button>
      <p class="mt-3 text-danger small">{login_failed_message}</p>
    </form>
  </div>
</div>
