// frontend/src/components/Map/BigMapStandaloneLayerSwitcher.vue
<template>
  <div class="layerSwitcher" @mouseleave="shown = false">
    <div v-if="!shown" class="layerSwitcherIcon">
      <i class="fas fa-layer-group" @mouseover="shown = true"></i>
    </div>
    <div class="layerSwitcherOptions">
      <ul v-if="shown">
        <li v-for="layer in tileLayers" :key="layer.name">
          <div v-if="layer.name === visibleLayer">{{ layer.name }}</div>
          <a v-else @click.prevent="$store.dispatch('setCurrentLayer', layer.name)">
            {{ layer.name }}
          </a>
        </li>
      </ul>
    </div>
  </div>
</template>
<script>
  import { mapState } from "vuex";

  export default {
    name: "BigMapStandaloneLayerSwitcher",
    data() {
      return {
        shown: false,
      };
    },
    computed: {
      ...mapState({
        tileLayers: (state) => state.layers,
        visibleLayer: (state) => state.visibleLayer,
      }),
    },
  };
</script>

<style lang="scss">
  .layerSwitcher {
    position: absolute;
    top: 5px;
    right: 5px;
    z-index: 200;
    padding: 15px 15px 12px;
    background: white;
    color: var(--color-lm-orange);
    border-radius: 5px;

    .layerSwitcherIcon {
      position: absolute;
      top: 0;
      right: 0;

      margin-left: auto;
      margin-right: auto;
      left: 0;
      text-align: center;
    }

    .layerSwitcherOptions {
      ul {
        padding-left: 5px;
        list-style: none;

        div {
          color: black;
        }

        a {
          cursor: pointer;
        }
      }
    }
  }
</style>

// newfront/src/components/Map/BigMapStandaloneLayerSwitcher.svelte
<script>
  import LayerGroup from "$components/icons/LayerGroup.svelte";
  import { visibleLayer, baseLayers } from "./layers";

  let shown;
</script>

<div
  class="absolute top-[10px] right-[10px] z-10 bg-white px-2 pt-1 pb-2 rounded border-2 border-black/30"
  on:mouseleave={() => (shown = false)}
>
  {#if !shown}
    <LayerGroup
      class="h-5 w-5 inline text-orange"
      on:focus={() => (shown = true)}
      on:mouseover={() => (shown = true)}
    />
  {:else}
    <ul>
      {#each baseLayers as layer}
        <li class="p-1">
          {#if layer.name === $visibleLayer}
            <div>{layer.name}</div>
          {:else}
            <button
              on:click|preventDefault={() => visibleLayer.set(layer.name)}
              class="text-orange"
            >
              {layer.name}
            </button>
          {/if}
        </li>
      {/each}
    </ul>
  {/if}
</div>
