// frontend/src/components/QuasiStaticMap.vue
<template>
  <div class="static-map" @click="goToGlobalMap">
    <LoadingPulse v-if="!markersReady" />
    <div class="shield">
      <span class="hover-text">Go to map</span>
    </div>
    <BigMap
      :options="{
        zoomControl: false,
        dragging: false,
        doubleClickZoom: false,
        boxZoom: false,
      }"
      :center="[12, 30]"
      :container-style="{ 'min-height': '100%', height: '100%' }"
      :hide-layer-switcher="true"
      @ready="bigMapReady"
    ></BigMap>
  </div>
</template>
<script>
  import { markers_query } from "$store/queries";
  import { styleCircle } from "$utils/map_helper";

  import { DivIcon, FeatureGroup, Marker } from "leaflet";
  import { MarkerClusterGroup } from "leaflet.markercluster";

  import BigMap from "./BigMap";
  import LoadingPulse from "./Data/LoadingPulse";

  const ZOOM_LEVEL_COUNTRY = 4;

  export default {
    name: "QuasiStaticMap",
    components: { LoadingPulse, BigMap },
    props: {
      countryId: { type: Number, required: false, default: null },
      regionId: { type: Number, required: false, default: null },
    },
    data() {
      return {
        map: null,
        featureGroup: new FeatureGroup(),
        markersReady: true,
        markers: [],
      };
    },
    apollo: {
      markers: markers_query,
    },
    computed: {
      roc() {
        if (this.regionId) {
          return this.$store.getters.getCountryOrRegion({
            type: "region",
            id: this.regionId,
          });
        }
        if (this.countryId) {
          return this.$store.getters.getCountryOrRegion({
            type: "country",
            id: this.countryId,
          });
        }
        return null;
      },
    },
    watch: {
      markers() {
        this.drawMarkers();
      },
      roc() {
        this.clearMap();
        this.focusMap();
      },
    },
    methods: {
      bigMapReady(map) {
        map.addLayer(this.featureGroup);
        this.map = map;
        this.drawMarkers();
        this.focusMap();
      },
      clearMap() {
        this.featureGroup.clearLayers();
      },
      focusMap() {
        if (this.roc) {
          if (this.regionId) {
            this.map.fitBounds(
              [
                [this.roc.point_lat_min, this.roc.point_lon_min],
                [this.roc.point_lat_max, this.roc.point_lon_max],
              ],
              { animate: false }
            );
          } else {
            this.map.setView(
              [this.roc.point_lat, this.roc.point_lon],
              ZOOM_LEVEL_COUNTRY,
              { animate: false }
            );
          }
        } else {
          this.map.fitWorld({ animate: false });
        }
      },
      _drawGlobalMarkers() {
        for (let mark of this.markers) {
          let circle = new Marker(mark.coordinates, {
            icon: new DivIcon({ className: "landmatrix-custom-circle" }),
            regionId: mark.region_id,
          });
          this.featureGroup.addLayer(circle);

          let coun_reg = this.$store.getters.getCountryOrRegion({
            type: "region",
            id: mark.region_id,
          }).name;

          styleCircle(circle, mark.count / 50, coun_reg, true, 30);
        }
      },
      _drawRegionMarkers() {
        for (let mark of this.markers) {
          let circle = new Marker(mark.coordinates, {
            icon: new DivIcon({ className: "landmatrix-custom-circle" }),
            countryId: mark.country_id,
          });
          this.featureGroup.addLayer(circle);
          styleCircle(circle, mark.count / 20, mark.count, true, 15);
        }
      },
      _drawCountryMarkers() {
        // noinspection JSCheckFunctionSignatures
        let mcluster = new MarkerClusterGroup({ maxClusterRadius: 20 });
        for (let mark of this.markers) {
          let circle = new Marker(mark.coordinates);
          // this.featureGroup.addLayer(circle);
          mcluster.addLayer(circle);
        }
        this.featureGroup.addLayer(mcluster);
      },
      drawMarkers() {
        if (!this.map || this.markers.length === 0) return;
        if (!this.regionId && !this.countryId) this._drawGlobalMarkers();
        if (this.regionId) this._drawRegionMarkers();
        if (this.countryId) this._drawCountryMarkers();
      },
      goToGlobalMap() {
        if (this.countryId) {
          this.$store.dispatch("setFilter", {
            filter: "region_id",
            value: null,
          });
          this.$store.dispatch("setFilter", {
            filter: "country_id",
            value: this.countryId,
          });
        } else {
          this.$store.dispatch("setFilter", {
            filter: "country_id",
            value: null,
          });
          this.$store.dispatch("setFilter", {
            filter: "region_id",
            value: this.regionId,
          });
        }
        this.$router.push({ name: "map" });
      },
    },
  };
</script>

<style lang="scss">
  .static-map {
    width: 100%;
    min-height: 300px;
    height: 30vh;
    position: relative;
    border: 1px solid var(--color-lm-orange);
    border-radius: 3px;
    box-shadow: 3px 3px 5px rgba(black, 0.3);

    &:hover {
      cursor: pointer;
      box-shadow: 5px 5px 5px rgba(black, 0.3);
      border-color: var(--color-lm-orange-light);
      transition: box-shadow 300ms;
    }

    .shield {
      position: absolute;
      width: 100%;
      height: 100%;
      z-index: 1000;
      background-color: transparent;
      display: flex;
      transition: background-color 600ms;

      &:before {
        content: "";
        position: absolute;
        width: 100%;
        height: 100%;
      }

      .hover-text {
        visibility: hidden;
        opacity: 0;
        transition: 600ms;
        color: white;
        font-weight: bold;
        font-size: 4rem;
        align-self: center;
        text-align: center;
        width: 100%;
        z-index: 1;
      }

      &:hover {
        transition: 300ms;
        background-color: hsla(32, 97%, 55%, 0.2);

        .hover-text {
          transition: 300ms;
          opacity: 1;
          visibility: visible;
        }
      }
    }
  }
</style>

// newfront/src/components/Map/QuasiStaticMap.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import { getCountryOrRegion } from "$lib/helpers";
  // import { FeatureGroup } from "leaflet";
  import { countries } from "$lib/stores";
  import BigMap from "$components/Map/BigMap.svelte";

  // import { markers_query } from "$store/queries";
  // import { styleCircle } from "./map_helper";
  // import { DivIcon, FeatureGroup, Marker } from "leaflet";
  // import { MarkerClusterGroup } from "leaflet.markercluster/src";

  export let countryID: number;
  export let regionID: number;
  console.log(countryID, regionID);

  const ZOOM_LEVEL_COUNTRY = 4;

  let map = null;
  // let featureGroup = new FeatureGroup();
  let markersReady = true;
  let markers = [];

  // console.log($countries);
  const roc = regionID
    ? getCountryOrRegion(regionID, true)
    : getCountryOrRegion(countryID);
  // console.log(roc);
  //   watch: {
  //     markers() {
  //       this.drawMarkers();
  //     },
  //     roc() {
  //       this.clearMap();
  //       this.focusMap();
  //     },
  //   },
  //   methods: {
  async function bigMapReady(map) {
    // map.addLayer(this.featureGroup);
    this.map = map;
    // this.drawMarkers();
    // this.focusMap();
  }
  //     clearMap() {
  //       this.featureGroup.clearLayers();
  //     },
  //     focusMap() {
  //       if (this.roc) {
  //         if (this.regionId) {
  //           this.map.fitBounds(
  //             [
  //               [this.roc.point_lat_min, this.roc.point_lon_min],
  //               [this.roc.point_lat_max, this.roc.point_lon_max],
  //             ],
  //             { animate: false }
  //           );
  //         } else {
  //           this.map.setView(
  //             [this.roc.point_lat, this.roc.point_lon],
  //             ZOOM_LEVEL_COUNTRY,
  //             { animate: false }
  //           );
  //         }
  //       } else {
  //         this.map.fitWorld({ animate: false });
  //       }
  //     },
  //     _drawGlobalMarkers() {
  //       for (let mark of this.markers) {
  //         let circle = new Marker(mark.coordinates, {
  //           icon: new DivIcon({ className: "landmatrix-custom-circle" }),
  //           regionId: mark.region_id,
  //         });
  //         this.featureGroup.addLayer(circle);
  //
  //         let coun_reg = this.$store.getters.getCountryOrRegion({
  //           type: "region",
  //           id: mark.region_id,
  //         }).name;
  //
  //         styleCircle(circle, mark.count / 50, coun_reg, true, 30);
  //       }
  //     },
  //     _drawRegionMarkers() {
  //       for (let mark of this.markers) {
  //         let circle = new Marker(mark.coordinates, {
  //           icon: new DivIcon({ className: "landmatrix-custom-circle" }),
  //           countryId: mark.country_id,
  //         });
  //         this.featureGroup.addLayer(circle);
  //         styleCircle(circle, mark.count / 20, mark.count, true, 15);
  //       }
  //     },
  //     _drawCountryMarkers() {
  //       // noinspection JSCheckFunctionSignatures
  //       let mcluster = new MarkerClusterGroup({ maxClusterRadius: 20 });
  //       for (let mark of this.markers) {
  //         let circle = new Marker(mark.coordinates);
  //         // this.featureGroup.addLayer(circle);
  //         mcluster.addLayer(circle);
  //       }
  //       this.featureGroup.addLayer(mcluster);
  //     },
  //     drawMarkers() {
  //       if (!this.map || this.markers.length === 0) return;
  //       if (!this.regionId && !this.countryId) this._drawGlobalMarkers();
  //       if (this.regionId) this._drawRegionMarkers();
  //       if (this.countryId) this._drawCountryMarkers();
  //     },
  async function goToGlobalMap() {
    // if (countryID) {
    //   this.$store.dispatch("setFilter", {
    //     filter: "region_id",
    //     value: null,
    //   });
    //   this.$store.dispatch("setFilter", {
    //     filter: "country_id",
    //     value: this.countryId,
    //   });
    // } else {
    //   this.$store.dispatch("setFilter", {
    //     filter: "country_id",
    //     value: null,
    //   });
    //   this.$store.dispatch("setFilter", {
    //     filter: "region_id",
    //     value: this.regionId,
    //   });
    // }
    // this.$router.push({ name: "map" });
  }
</script>

<div
  class="mt-6 w-full min-h-[300px] h-[30vh] relative border border-orange shadow-md rounded cursor-pointer hover:border-orange-300"
  on:click={goToGlobalMap}
>
  <div
    class="group absolute w-full h-full z-[1000] bg-transparent flex hover:bg-orange/20 transition duration-300"
  >
    <span
      class="invisible opacity-0 self-center text-center w-full z-1 text-[4rem] font-bold text-white group-hover:opacity-100  group-hover:visible hover-text transition duration-500"
    >
      {$_("Go to map")}
    </span>
  </div>
  <BigMap
    options={{
      zoomControl: false,
      dragging: false,
      doubleClickZoom: false,
      boxZoom: false,
      center: [12, 30],
    }}
    containerClass="min-h-full h-full"
    hideLayerSwitcher={true}
    on:ready={bigMapReady}
  />
</div>
