// newfront/src/components/Data/DataContainer.svelte
<script lang="ts">
  // import ContextBarMap from "$components/Data/ContextBarMap.vue";
  // import ViewSwitcher from "$components/Data/ViewSwitcher.vue";
  import FilterBar from "./FilterBar.svelte";
</script>

<div class="relative p-0 w-full h-full">
  <!--    <ViewSwitcher />-->
  <FilterBar>
    <slot name="FilterBar" />
  </FilterBar>
  <!--    <ContextBarMap />-->
  <div class="w-full h-full">
    <slot />
  </div>
</div>

// frontend/src/views/Data/DataContainer.vue
<template>
  <div class="datacontainer">
    <ViewSwitcher />
    <FilterBar>
      <slot name="FilterBar"></slot>
    </FilterBar>
    <ContextBarMap />
    <div class="main-content">
      <slot></slot>
    </div>
  </div>
</template>

<script>
  import FilterBar from "$components/Data/FilterBar";
  import ContextBarMap from "$components/Data/ContextBarMap";
  import ViewSwitcher from "$components/Data/ViewSwitcher";

  export default {
    name: "DataContainer",
    components: { ContextBarMap, FilterBar, ViewSwitcher },
  };
</script>
<style lang="scss">
  .datacontainer {
    position: relative;
    padding: 0;
    width: 100%;
    height: calc(100vh - 60px - 31px);
    .main-content {
      width: 100%;
      height: 100%;
    }
  }
</style>
