// newfront/src/routes/account/login/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { _ } from "svelte-i18n";
  import { page } from "$app/stores";
  import { dispatchLogin } from "$lib/user";

  let username = "";
  let password = "";
  let login_failed_message = "";
  let login_success_message = $_("You are logged in.");

  let logged_in = false;
  let next: string;

  onMount(() => {
    next = $page.url.searchParams.get("next") || "/";

    if ($page.data.user?.is_authenticated) {
      window.location.href = next;
    }
  });

  async function login() {
    const res = await dispatchLogin(username, password, $page.data.urqlClient);
    if (res.status) {
      login_failed_message = "";
      logged_in = true;
      await setTimeout(() => (window.location.href = next), 100);
      // can't do this, because it's hard to populate "user" back to layout:
      // setTimeout(() => goto(next), 100);
    } else {
      login_failed_message = res.error;
    }
  }
</script>

<div class="test-login flex h-5/6 items-center justify-center">
  <div class="w-[540px] border border-neutral-600 p-4 text-black">
    <h1 class="mb-10">{$_("Login")}</h1>
    <form on:submit|preventDefault={login}>
      <label class="mb-4 block">
        Username
        <input
          bind:value={username}
          autocomplete="username"
          class="inpt"
          placeholder="Username"
          type="text"
          autofocus
        />
      </label>
      <label class="mb-4 block">
        Password
        <input
          bind:value={password}
          autocomplete="current-password"
          class="inpt"
          placeholder="Password"
          type="password"
        />
      </label>
      <button class="btn btn-primary w-full" type="submit">
        {$_("Login")}
      </button>
      <p class="mt-3">
        {logged_in ? login_success_message : login_failed_message}
      </p>
    </form>
    <div class="mt-12 text-right">
      <a href="/account/register/">
        {$_("New around here? Sign up")}
      </a>
    </div>
  </div>
</div>

// frontend/src/views/Login.vue
<template>
  <div class="login-wrapper">
    <div v-if="$store.getters.userAuthenticated">
      {{ $t("You are already logged in.") }}
    </div>
    <div v-else class="login-container">
      <form @submit.prevent="dispatchLogin">
        <label>
          Username
          <input
            v-model="username"
            class="form-control"
            type="text"
            autocomplete="username"
            placeholder="Username"
          />
        </label>
        <label>
          Password
          <input
            v-model="password"
            class="form-control"
            type="password"
            autocomplete="current-password"
            placeholder="Password"
          />
        </label>
        <button type="submit" class="btn btn-primary">
          {{ $t("Login") }}
        </button>
        <p class="mt-3 text-danger small">{{ login_failed_message }}</p>
      </form>
    </div>
  </div>
</template>

<script>
  export default {
    name: "Login",
    data() {
      return {
        username: null,
        password: null,
        login_failed_message: "",
      };
    },
    created() {
      if (this.$store.getters.userAuthenticated) {
        if (this.$route.query.next) this.$router.push(this.$route.query.next);
      }
    },
    methods: {
      dispatchLogin() {
        this.$store
          .dispatch("login", { username: this.username, password: this.password })
          .then(() => {
            this.$router.push(this.$route.query.next || "/");
          })
          .catch((response) => {
            this.login_failed_message = response.error;
          });
      },
    },
  };
</script>

<style scoped>
  .login-wrapper {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 60vh;
  }
  .login-container {
    width: 350px;

    background: #4b4b4b;
    color: white;
    padding: 1rem;
    border-radius: 3px;
  }
  label {
    display: block;
    margin-bottom: 1rem;
  }
  input {
    display: block;
  }
</style>
