// frontend/src/components/Fields/EditField.vue
<template>
  <div v-if="_visible" :class="wrapperClasses">
    <FieldLabel
      v-if="showLabel"
      :fieldname="fieldname"
      :label-classes="labelClasses"
      :model="model"
    />
    <div :class="valueClasses">
      <component
        :is="formfield.class"
        v-model="_value"
        :formfield="formfield"
        :model="model"
      />
    </div>
  </div>
</template>

<script>
  import ManyToManyField from "./Display/ManyToManyField";

  // import AutoField from "./Display/AutoField";
  import ArrayField from "./Edit/ArrayField";

  import BooleanField from "./Edit/BooleanField";
  import NullBooleanField from "./Edit/BooleanField";

  import DateField from "./Edit/DateField";
  // import DateTimeField from "./Display/DateField";
  import DecimalField from "./Edit/DecimalField";
  import FloatField from "./Edit/DecimalField";
  import IntegerField from "./Edit/DecimalField";

  import FileField from "./Edit/FileField";
  import ForeignKey from "./Edit/ForeignKeyField";
  import JSONActorsField from "./Edit/JSONActorsField";
  import JSONDateAreaChoicesField from "./Edit/JSONDateAreaChoicesField";
  import JSONDateAreaField from "./Edit/JSONDateAreaField";
  import JSONDateChoiceField from "./Edit/JSONDateChoiceField";
  import JSONExportsField from "./Edit/JSONExportsField";

  import JSONField from "./Edit/JSONField.vue";
  import JSONJobsField from "./Edit/JSONJobsField";
  import JSONLeaseField from "./Edit/JSONLeaseField";
  import LocationGoogleField from "./Edit/LocationGoogleField";
  import PointField from "./Edit/PointField";

  import CharField from "./Edit/TextField";
  import EmailField from "./Edit/TextField";
  import TextField from "./Edit/TextField";
  import URLField from "./Edit/TextField";
  import OCIDField from "./Edit/TextField";

  import FieldLabel from "./FieldLabel";

  export default {
    name: "EditField",
    components: {
      // AutoField,
      FieldLabel,
      ArrayField,
      BooleanField,
      CharField,
      DateField,
      // DateTimeField,
      DecimalField,
      EmailField,
      FileField,
      FloatField,
      ForeignKey,
      LocationGoogleField,
      ManyToManyField,
      IntegerField,
      JSONActorsField,
      JSONDateAreaChoicesField,
      JSONDateAreaField,
      JSONDateChoiceField,
      JSONExportsField,
      JSONField,
      JSONJobsField,
      JSONLeaseField,
      NullBooleanField,
      PointField,
      TextField,
      URLField,
      OCIDField,
    },
    props: {
      fieldname: { type: String, required: true },
      // eslint-disable-next-line vue/require-prop-types
      value: { required: true },
      model: { type: String, default: "deal" },
      showLabel: { type: Boolean, default: true },
      wrapperClasses: {
        type: Array,
        default: () => ["display-field-wrapper", "form-field", "row"],
      },
      labelClasses: {
        type: Array,
        default: () => ["display-field-label", "col-md-3", "col-lg-3"],
      },
      valueClasses: {
        type: Array,
        default: () => ["display-field-value", "col-md-9", "col-lg-9"],
      },
      fileNotPublic: { type: Boolean, default: false },
      visible: { type: Boolean, default: true },
    },
    computed: {
      _value: {
        get() {
          return this.value;
        },
        set(v) {
          this.$emit("input", v);
        },
      },
      _visible() {
        if (!this.visible) return false;
        if (this.formfield.class === "FileField") {
          return !this.fileNotPublic || this.$store.getters.userAuthenticated;
        }
        return true;
      },
      formfield() {
        return {
          name: this.fieldname,
          ...this.$store.state.formfields[this.model][this.fieldname],
        };
      },
    },
    methods: {},
  };
</script>

<style lang="scss">
  @import "src/scss/colors";

  .display-field-wrapper {
    margin-bottom: 0.7em;
    line-height: 1.2;
  }
  .display-field-label {
    font-weight: 500;
  }
  .display-field-value {
    line-height: 1.2;
    color: $lm_dark;
  }
</style>

// newfront/src/components/Fields/EditField.svelte
<script lang="ts">
  import { _ } from "svelte-i18n"

  import { formfields } from "$lib/stores"

  import DecimalField from "$components/Fields/Edit/DecimalField.svelte"
  import TextField from "$components/Fields/Edit/TextField.svelte"
  import type { FormField } from "$components/Fields/fields"

  import BooleanField from "./Edit/BooleanField.svelte"
  import CharField from "./Edit/CharField.svelte"
  import CountryForeignKey from "./Edit/CountryForeignKey.svelte"
  import CurrencyForeignKey from "./Edit/CurrencyForeignKey.svelte"
  import DateField from "./Edit/DateField.svelte"
  import EmailField from "./Edit/EmailField.svelte"
  import FileField from "./Edit/FileField.svelte"
  import InvestorForeignKey from "./Edit/InvestorForeignKey.svelte"
  import JSONActorsField from "./Edit/JSONActorsField.svelte"
  import JSONDateAreaChoicesField from "./Edit/JSONDateAreaChoicesField.svelte"
  import JSONDateAreaField from "./Edit/JSONDateAreaField.svelte"
  import JSONDateChoiceField from "./Edit/JSONDateChoiceField.svelte"
  import JSONExportsField from "./Edit/JSONExportsField.svelte"
  import JSONJobsField from "./Edit/JSONJobsField.svelte"
  import JSONLeaseField from "./Edit/JSONLeaseField.svelte"
  import SimpleArrayField from "./Edit/SimpleArrayField.svelte"
  import TypedChoiceField from "./Edit/TypedChoiceField.svelte"
  import URLField from "./Edit/URLField.svelte"

  export let fieldname: string
  export let value
  export let model = "deal"

  export let showLabel = true
  export let wrapperClasses = "mb-3 leading-5 flex flex-col xl:flex-row"
  export let labelClasses = "font-medium mb-1 w-full xl:w-1/4"
  export let valueClasses = "text-lm-dark mb-5 w-full xl:w-3/4"
  export let disabled = false

  //   computed: {
  //     _visible(): boolean {
  //       if (!this.visible) return false;
  //       if (this.fieldname === "file_not_public") return false;
  //       if (this.formfield.class === "FileField") {
  //         return !this.fileNotPublic || this.$store.getters.userAuthenticated;
  //       }
  //       return true;
  //     },

  let formfield: FormField
  $: formfield = { name: fieldname, ...$formfields[model][fieldname] }

  $: field = {
    CountryForeignKey: CountryForeignKey,
    CurrencyForeignKey: CurrencyForeignKey,
    DateField: DateField,
    DecimalField: DecimalField,
    EmailField: EmailField,
    FloatField: DecimalField,
    IntegerField: DecimalField,
    InvestorForeignKey: InvestorForeignKey,
    JSONActorsField: JSONActorsField,
    JSONDateAreaChoicesField: JSONDateAreaChoicesField,
    JSONDateAreaField: JSONDateAreaField,
    JSONDateChoiceField: JSONDateChoiceField,
    JSONExportsField: JSONExportsField,
    JSONJobsField: JSONJobsField,
    JSONLeaseField: JSONLeaseField,
    SimpleArrayField: SimpleArrayField,
    TypedChoiceField: TypedChoiceField,
    URLField: URLField,
  }[formfield.class]
</script>

<div class={wrapperClasses}>
  {#if showLabel}
    <div class={labelClasses}>
      {$_(formfield.label)}
    </div>
  {/if}
  <div class={valueClasses}>
    {#if formfield.class === "FileField"}
      <FileField bind:value {model} {formfield} on:change />
    {:else if formfield.class === "TextField"}
      <TextField bind:value {formfield} on:change />
    {:else if ["CharField", "OCIDField"].includes(formfield.class)}
      <CharField bind:value {formfield} on:change />
    {:else if ["BooleanField", "NullBooleanField"].includes(formfield.class)}
      <BooleanField bind:value {formfield} on:change />
    {:else if field}
      <svelte:component
        this={field}
        bind:value
        {model}
        {disabled}
        {formfield}
        on:change
      />
    {:else}
      <span class="italic text-red-600">Unknown field: {formfield.class}</span>
    {/if}
  </div>
</div>
